Entity Master : bank's legal structure

In [2]:
import pandas as pd
from pathlib import Path

entity_master = pd.DataFrame([
    {
        "entity_id": "ENT-GROUP-001",
        "legal_name": "Atlas Banking Group SA",
        "lei_code": "5493001KJTIIGC8Y1R12",
        "parent_entity_id": None,
        "country_code": "FR",
        "reporting_currency": "EUR",
        "boundary_type": "operational_control",
        "consolidation_method": "full",
        "in_scope_esg_flag": True,
        "regulatory_regime": "CSRD",
        "fiscal_year_end": "12-31"
    },
    {
        "entity_id": "ENT-FR-002",
        "legal_name": "Atlas Retail Bank France SA",
        "lei_code": "5493003H3B70FQD3AL11",
        "parent_entity_id": "ENT-GROUP-001",
        "country_code": "FR",
        "reporting_currency": "EUR",
        "boundary_type": "financial_control",
        "consolidation_method": "full",
        "in_scope_esg_flag": True,
        "regulatory_regime": "CSRD",
        "fiscal_year_end": "12-31"
    },
    {
        "entity_id": "ENT-DE-003",
        "legal_name": "Atlas Bank Deutschland AG",
        "lei_code": "529900T8BM49AURSDO55",
        "parent_entity_id": "ENT-GROUP-001",
        "country_code": "DE",
        "reporting_currency": "EUR",
        "boundary_type": "financial_control",
        "consolidation_method": "full",
        "in_scope_esg_flag": True,
        "regulatory_regime": "CSRD",
        "fiscal_year_end": "12-31"
    },
    {
        "entity_id": "ENT-NL-004",
        "legal_name": "Atlas Bank Netherlands NV",
        "lei_code": "724500K88LOP4WKQK477",
        "parent_entity_id": "ENT-GROUP-001",
        "country_code": "NL",
        "reporting_currency": "EUR",
        "boundary_type": "financial_control",
        "consolidation_method": "full",
        "in_scope_esg_flag": True,
        "regulatory_regime": "CSRD",
        "fiscal_year_end": "12-31"
    },
    {
        "entity_id": "ENT-UK-005",
        "legal_name": "Atlas Capital Markets UK Ltd",
        "lei_code": "213800D1EI4B9WTWWD28",
        "parent_entity_id": "ENT-GROUP-001",
        "country_code": "GB",
        "reporting_currency": "GBP",
        "boundary_type": "operational_control",
        "consolidation_method": "full",
        "in_scope_esg_flag": True,
        "regulatory_regime": "voluntary",
        "fiscal_year_end": "12-31"
    },
    {
        "entity_id": "ENT-ES-006",
        "legal_name": "Atlas Leasing Spain SL",
        "lei_code": "95980020140005090163",
        "parent_entity_id": "ENT-GROUP-001",
        "country_code": "ES",
        "reporting_currency": "EUR",
        "boundary_type": "financial_control",
        "consolidation_method": "full",
        "in_scope_esg_flag": True,
        "regulatory_regime": "CSRD",
        "fiscal_year_end": "12-31"
    },
    {
        "entity_id": "ENT-IT-007",
        "legal_name": "Atlas Consumer Finance Italia SpA",
        "lei_code": "815600EAD78C57FCE690",
        "parent_entity_id": "ENT-GROUP-001",
        "country_code": "IT",
        "reporting_currency": "EUR",
        "boundary_type": "financial_control",
        "consolidation_method": "full",
        "in_scope_esg_flag": True,
        "regulatory_regime": "CSRD",
        "fiscal_year_end": "12-31"
    },
    {
        "entity_id": "ENT-BE-008",
        "legal_name": "Atlas Bank Belgium SA",
        "lei_code": "5493007HL4QLY7HM2P19",
        "parent_entity_id": "ENT-GROUP-001",
        "country_code": "BE",
        "reporting_currency": "EUR",
        "boundary_type": "financial_control",
        "consolidation_method": "full",
        "in_scope_esg_flag": True,
        "regulatory_regime": "CSRD",
        "fiscal_year_end": "12-31"
    },
    {
        "entity_id": "ENT-LU-009",
        "legal_name": "Atlas Asset Management Luxembourg SA",
        "lei_code": "222100SLJ4P1HJAG9W32",
        "parent_entity_id": "ENT-GROUP-001",
        "country_code": "LU",
        "reporting_currency": "EUR",
        "boundary_type": "equity_share",
        "consolidation_method": "equity_method",
        "in_scope_esg_flag": True,
        "regulatory_regime": "CSRD",
        "fiscal_year_end": "12-31"
    },
    {
        "entity_id": "ENT-US-010",
        "legal_name": "Atlas Securities USA Inc.",
        "lei_code": "5493001KJTIIGC8Y1R34",
        "parent_entity_id": "ENT-GROUP-001",
        "country_code": "US",
        "reporting_currency": "USD",
        "boundary_type": "operational_control",
        "consolidation_method": "full",
        "in_scope_esg_flag": True,
        "regulatory_regime": "SEC_climate",
        "fiscal_year_end": "12-31"
    }
])

out = Path(r"Data/entity_master_raw.csv")
out.parent.mkdir(parents=True, exist_ok=True)

entity_master.to_csv(out, index=False)

entity_master

,entity_id,legal_name,lei_code,parent_entity_id,country_code,reporting_currency,boundary_type,consolidation_method,in_scope_esg_flag,regulatory_regime,fiscal_year_end
0,ENT-GROUP-001,Atlas Banking Group SA,5493001KJTIIGC8Y1R12,NaN,FR,EUR,operational_control,full,True,CSRD,12-31
1,ENT-FR-002,Atlas Retail Bank France SA,5493003H3B70FQD3AL11,ENT-GROUP-001,FR,EUR,financial_control,full,True,CSRD,12-31
2,ENT-DE-003,Atlas Bank Deutschland AG,529900T8BM49AURSDO55,ENT-GROUP-001,DE,EUR,financial_control,full,True,CSRD,12-31
3,ENT-NL-004,Atlas Bank Netherlands NV,724500K88LOP4WKQK477,ENT-GROUP-001,NL,EUR,financial_control,full,True,CSRD,12-31
4,ENT-UK-005,Atlas Capital Markets UK Ltd,213800D1EI4B9WTWWD28,ENT-GROUP-001,GB,GBP,operational_control,full,True,voluntary,12-31
5,ENT-ES-006,Atlas Leasing Spain SL,95980020140005090163,ENT-GROUP-001,ES,EUR,financial_control,full,True,CSRD,12-31
6,ENT-IT-007,Atlas Consumer Finance Italia SpA,815600EAD78C57FCE690,ENT-GROUP-001,IT,EUR,financial_control,full,True,CSRD,12-31
7,ENT-BE-008,Atlas Bank Belgium SA,5493007HL4QLY7HM2P19,ENT-GROUP-001,BE,EUR,financial_control,full,True,CSRD,12-31
8,ENT-LU-009,Atlas Asset Management Luxembourg SA,222100SLJ4P1HJAG9W32,ENT-GROUP-001,LU,EUR,equity_share,equity_method,True,CSRD,12-31
9,ENT-US-010,Atlas Securities USA Inc.,5493001KJTIIGC8Y1R34,ENT-GROUP-001,US,USD,operational_control,full,True,SEC_climate,12-31

Emission Factors : A lookup table of published emission factors

In [3]:
import csv
from datetime import datetime
from pathlib import Path

# =========================================================
# PATHS
# =========================================================
entity_path = Path("Data/entity_master_raw.csv")
out_path = Path("Data/emission_factors_raw.csv")
out_path.parent.mkdir(parents=True, exist_ok=True)

# =========================================================
# HELPERS
# =========================================================
def to_bool(value) -> bool:
    return str(value).strip().lower() in {"true", "1", "yes", "y"}

def clean_code(code: str) -> str:
    """
    Make a code safe for factor_id construction.
    Example:
    C24.10 -> C2410
    GRID_ELECTRICITY -> GRIDELECTRICITY
    """
    return (
        str(code)
        .strip()
        .upper()
        .replace(".", "")
        .replace("-", "")
        .replace(" ", "_")
    )

def make_factor_id(nace_code: str, year: int, country_code: str, factor_scope: str) -> str:
    """
    Composite ID.
    I include scope as well so IDs stay unique even if
    the same nace_code/year/country appears with multiple scopes later.
    """
    return f"EF-{clean_code(nace_code)}-{year}-{country_code}-{factor_scope.upper()}"

# =========================================================
# LOAD IN-SCOPE COUNTRIES FROM ENTITY MASTER
# =========================================================
countries = []

with entity_path.open("r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        if to_bool(row["in_scope_esg_flag"]):
            countries.append(row["country_code"].strip())

countries = sorted(set(countries))

# =========================================================
# REFERENCE YEARS
# =========================================================
years = list(range(2019, 2025))

# =========================================================
# COUNTRY GRID ELECTRICITY FACTORS
# unit = tCO2e/MWh
# source = IEA
# =========================================================
grid_2024 = {
    "FR": 0.055,
    "DE": 0.360,
    "NL": 0.300,
    "GB": 0.180,
    "ES": 0.150,
    "IT": 0.250,
    "BE": 0.170,
    "LU": 0.120,
    "US": 0.370,
}

# =========================================================
# SECTOR FINANCED-EMISSION INTENSITY FACTORS
# unit = tCO2e/eur_million_revenue
# source = PCAF
# =========================================================
sector_factors_2024 = [
    ("A01.11", "scope1", 520.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("B05.10", "scope1", 5200.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("B06.10", "scope1", 3900.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("C10.11", "scope1", 680.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("C20.16", "scope1", 890.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("C23.51", "scope1", 4100.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("C24.10", "scope1", 1420.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("D35.11", "scope1", 2400.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("F41.20", "scope1", 310.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("G46.90", "scope1", 180.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("H49.41", "scope1", 1250.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("H51.10", "scope1", 3100.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("J62.01", "scope1", 45.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("K64.19", "scope1", 18.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("K64.30", "scope1", 12.0, "tCO2e/eur_million_revenue", "PCAF", 4),
    ("L68.20", "scope1", 80.0, "tCO2e/eur_million_revenue", "PCAF", 4),
]

# =========================================================
# FUEL FACTORS FOR OWN OPERATIONS
# We keep them in the same table using synthetic activity codes
# because your design uses one unified factor lookup table.
# source = DEFRA
# =========================================================
fuel_factors = [
    ("FUEL_NATGAS", "scope1", 0.202, "tCO2e/MWh", "DEFRA", 3),
    ("FUEL_DIESEL", "scope1", 0.267, "tCO2e/MWh", "DEFRA", 3),
    ("FUEL_PETROL", "scope1", 0.249, "tCO2e/MWh", "DEFRA", 3),
    ("FUEL_LPG", "scope1", 0.227, "tCO2e/MWh", "DEFRA", 3),
]

# =========================================================
# BUILD ROWS
# TARGET COLUMNS:
# factor_id, nace_code, year, country_code, factor_scope,
# emission_factor, unit, source, pcaf_quality_score, last_updated
# =========================================================
rows = []
last_updated = datetime.now().strftime("%Y-%m-%d")

# 1) Grid electricity factors by country/year
for country in countries:
    baseline = grid_2024.get(country, 0.280)
    for year in years:
        factor = baseline * (1 + 0.045 * (2024 - year))

        nace_code = "GRID_ELECTRICITY"
        factor_scope = "scope2"

        rows.append({
            "factor_id": make_factor_id(nace_code, year, country, factor_scope),
            "nace_code": nace_code,
            "year": year,
            "country_code": country,
            "factor_scope": factor_scope,
            "emission_factor": round(factor, 6),
            "unit": "tCO2e/MWh",
            "source": "IEA",
            "pcaf_quality_score": 3,
            "last_updated": last_updated,
        })

# 2) Sector financed-emission factors by year
# Use GLOBAL to represent non-country-specific factors
for nace_code, factor_scope, base, unit, source, quality in sector_factors_2024:
    for year in years:
        factor = base * (1 + 0.03 * (2024 - year))
        country_code = "GLOBAL"

        rows.append({
            "factor_id": make_factor_id(nace_code, year, country_code, factor_scope),
            "nace_code": nace_code,
            "year": year,
            "country_code": country_code,
            "factor_scope": factor_scope,
            "emission_factor": round(factor, 6),
            "unit": unit,
            "source": source,
            "pcaf_quality_score": quality,
            "last_updated": last_updated,
        })

# 3) Fuel combustion factors by country/year
for nace_code, factor_scope, base, unit, source, quality in fuel_factors:
    for country in countries:
        for year in years:
            rows.append({
                "factor_id": make_factor_id(nace_code, year, country, factor_scope),
                "nace_code": nace_code,
                "year": year,
                "country_code": country,
                "factor_scope": factor_scope,
                "emission_factor": round(base, 6),
                "unit": unit,
                "source": source,
                "pcaf_quality_score": quality,
                "last_updated": last_updated,
            })

# =========================================================
# WRITE CSV
# =========================================================
fieldnames = [
    "factor_id",
    "nace_code",
    "year",
    "country_code",
    "factor_scope",
    "emission_factor",
    "unit",
    "source",
    "pcaf_quality_score",
    "last_updated",
]

with out_path.open("w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

# =========================================================
# VALIDATION CHECKS
# =========================================================
unique_key_check = set()
duplicates = 0
non_positive = 0
bad_quality = 0
bad_scope = 0
bad_source = 0

allowed_scopes = {"scope1", "scope2", "scope3_upstream", "scope3_downstream"}
allowed_sources = {"PCAF", "IEA", "DEFRA", "EPA", "sector_study"}

for r in rows:
    key = (
        r["nace_code"],
        r["year"],
        r["country_code"],
        r["factor_scope"],
        r["unit"],
    )

    if key in unique_key_check:
        duplicates += 1
    unique_key_check.add(key)

    if r["emission_factor"] <= 0:
        non_positive += 1

    if r["pcaf_quality_score"] not in [1, 2, 3, 4, 5]:
        bad_quality += 1

    if r["factor_scope"] not in allowed_scopes:
        bad_scope += 1

    if r["source"] not in allowed_sources:
        bad_source += 1

print(f"Generated: {out_path}")
print(f"Rows: {len(rows)}")
print(f"In-scope countries from entity_master: {countries}")
print(f"Duplicate composite keys: {duplicates}")
print(f"Non-positive factors: {non_positive}")
print(f"Invalid quality scores: {bad_quality}")
print(f"Invalid scopes: {bad_scope}")
print(f"Invalid sources: {bad_source}")

print("\nPreview:")
for row in rows[:8]:
    print(row)

Generated: Data\emission_factors_raw.csv
Rows: 366
In-scope countries from entity_master: ['BE', 'DE', 'ES', 'FR', 'GB', 'IT', 'LU', 'NL', 'US']
Duplicate composite keys: 0
Non-positive factors: 0
Invalid quality scores: 0
Invalid scopes: 0
Invalid sources: 0

Preview:
{'factor_id': 'EF-GRID_ELECTRICITY-2019-BE-SCOPE2', 'nace_code': 'GRID_ELECTRICITY', 'year': 2019, 'country_code': 'BE', 'factor_scope': 'scope2', 'emission_factor': 0.20825, 'unit': 'tCO2e/MWh', 'source': 'IEA', 'pcaf_quality_score': 3, 'last_updated': '2026-05-07'}
{'factor_id': 'EF-GRID_ELECTRICITY-2020-BE-SCOPE2', 'nace_code': 'GRID_ELECTRICITY', 'year': 2020, 'country_code': 'BE', 'factor_scope': 'scope2', 'emission_factor': 0.2006, 'unit': 'tCO2e/MWh', 'source': 'IEA', 'pcaf_quality_score': 3, 'last_updated': '2026-05-07'}
{'factor_id': 'EF-GRID_ELECTRICITY-2021-BE-SCOPE2', 'nace_code': 'GRID_ELECTRICITY', 'year': 2021, 'country_code': 'BE', 'factor_scope': 'scope2', 'emission_factor': 0.19295, 'unit': 'tCO2e/MWh', 'source': 'IEA', 'pcaf_quality_score': 3, 'last_updated': '2026-05-07'}
{'factor_id': 'EF-GRID_ELECTRICITY-2022-BE-SCOPE2', 'nace_code': 'GRID_ELECTRICITY', 'year': 2022, 'country_code': 'BE', 'factor_scope': 'scope2', 'emission_factor': 0.1853, 'unit': 'tCO2e/MWh', 'source': 'IEA', 'pcaf_quality_score': 3, 'last_updated': '2026-05-07'}
{'factor_id': 'EF-GRID_ELECTRICITY-2023-BE-SCOPE2', 'nace_code': 'GRID_ELECTRICITY', 'year': 2023, 'country_code': 'BE', 'factor_scope': 'scope2', 'emission_factor': 0.17765, 'unit': 'tCO2e/MWh', 'source': 'IEA', 'pcaf_quality_score': 3, 'last_updated': '2026-05-07'}
{'factor_id': 'EF-GRID_ELECTRICITY-2024-BE-SCOPE2', 'nace_code': 'GRID_ELECTRICITY', 'year': 2024, 'country_code': 'BE', 'factor_scope': 'scope2', 'emission_factor': 0.17, 'unit': 'tCO2e/MWh', 'source': 'IEA', 'pcaf_quality_score': 3, 'last_updated': '2026-05-07'}
{'factor_id': 'EF-GRID_ELECTRICITY-2019-DE-SCOPE2', 'nace_code': 'GRID_ELECTRICITY', 'year': 2019, 'country_code': 'DE', 'factor_scope': 'scope2', 'emission_factor': 0.441, 'unit': 'tCO2e/MWh', 'source': 'IEA', 'pcaf_quality_score': 3, 'last_updated': '2026-05-07'}
{'factor_id': 'EF-GRID_ELECTRICITY-2020-DE-SCOPE2', 'nace_code': 'GRID_ELECTRICITY', 'year': 2020, 'country_code': 'DE', 'factor_scope': 'scope2', 'emission_factor': 0.4248, 'unit': 'tCO2e/MWh', 'source': 'IEA', 'pcaf_quality_score': 3, 'last_updated': '2026-05-07'}

Geo Risk : A geospatial reference table mapping locations (postcode or lat/lon) to climate hazard scores

In [4]:
import pandas as pd
import numpy as np
from pathlib import Path

rng = np.random.default_rng(42)

# =========================================================
# PATHS
# =========================================================
entity_path = Path("Data/entity_master_raw.csv")
out_path = Path("Data/geo_risk_db_raw.csv")
out_path.parent.mkdir(parents=True, exist_ok=True)

# =========================================================
# LOAD IN-SCOPE COUNTRIES
# =========================================================
entity_master = pd.read_csv(entity_path)

in_scope_mask = (
    entity_master["in_scope_esg_flag"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("true")
)

countries = sorted(entity_master.loc[in_scope_mask, "country_code"].dropna().unique())

# =========================================================
# GEOGRAPHIC SEEDS
# tuple = (city, postcode_prefix, base_lat, base_lon, coastal_flag, river_km)
# coastal_flag and river_km are generation drivers only, not final output columns
# =========================================================
country_city_seeds = {
    "FR": [
        ("Paris", "75001", 48.8566, 2.3522, False, 4.0),
        ("Lyon", "69001", 45.7640, 4.8357, False, 1.2),
        ("Marseille", "13001", 43.2965, 5.3698, True, 2.5),
        ("Nice", "06000", 43.7102, 7.2620, True, 1.5),
        ("Bordeaux", "33000", 44.8378, -0.5792, False, 0.8),
        ("Lille", "59000", 50.6292, 3.0573, False, 1.8),
    ],
    "DE": [
        ("Berlin", "10115", 52.5200, 13.4050, False, 3.0),
        ("Hamburg", "20095", 53.5511, 9.9937, True, 0.7),
        ("Munich", "80331", 48.1351, 11.5820, False, 1.4),
        ("Frankfurt", "60311", 50.1109, 8.6821, False, 0.6),
        ("Cologne", "50667", 50.9375, 6.9603, False, 0.5),
        ("Dusseldorf", "40210", 51.2277, 6.7735, False, 0.7),
    ],
    "NL": [
        ("Amsterdam", "1011", 52.3676, 4.9041, True, 0.5),
        ("Rotterdam", "3011", 51.9244, 4.4777, True, 0.4),
        ("The Hague", "2511", 52.0705, 4.3007, True, 0.6),
        ("Utrecht", "3511", 52.0907, 5.1214, False, 0.9),
    ],
    "GB": [
        ("London", "EC1A", 51.5072, -0.1276, False, 0.8),
        ("Manchester", "M1", 53.4808, -2.2426, False, 1.2),
        ("Liverpool", "L1", 53.4084, -2.9916, True, 0.6),
        ("Bristol", "BS1", 51.4545, -2.5879, True, 1.0),
    ],
    "ES": [
        ("Madrid", "28001", 40.4168, -3.7038, False, 3.0),
        ("Barcelona", "08001", 41.3874, 2.1686, True, 1.2),
        ("Valencia", "46001", 39.4699, -0.3763, True, 0.8),
        ("Seville", "41001", 37.3891, -5.9845, False, 2.2),
    ],
    "IT": [
        ("Rome", "00100", 41.9028, 12.4964, True, 1.4),
        ("Milan", "20100", 45.4642, 9.1900, False, 1.1),
        ("Venice", "30100", 45.4408, 12.3155, True, 0.2),
        ("Naples", "80100", 40.8518, 14.2681, True, 0.9),
    ],
    "BE": [
        ("Brussels", "1000", 50.8503, 4.3517, False, 1.0),
        ("Antwerp", "2000", 51.2194, 4.4025, True, 0.6),
        ("Ghent", "9000", 51.0543, 3.7174, False, 0.9),
    ],
    "LU": [
        ("Luxembourg City", "1111", 49.6116, 6.1319, False, 1.5),
        ("Esch-sur-Alzette", "4000", 49.4958, 5.9806, False, 1.2),
    ],
    "US": [
        ("New York", "10001", 40.7128, -74.0060, True, 0.7),
        ("Miami", "33101", 25.7617, -80.1918, True, 1.0),
        ("Houston", "77001", 29.7604, -95.3698, True, 0.8),
        ("Chicago", "60601", 41.8781, -87.6298, False, 1.2),
        ("San Francisco", "94102", 37.7749, -122.4194, True, 0.9),
    ],
}

# =========================================================
# HELPERS
# =========================================================
def build_postcode(country: str, postcode_prefix: str, i: int) -> str:
    if country == "GB":
        return f"{postcode_prefix} {i+1}AA"
    if country == "LU":
        return f"L-{int(postcode_prefix) + i:04d}"
    return f"{postcode_prefix}-{i+1:02d}"

def expected_flood_class(score: float) -> str:
    if score < 2.5:
        return "low"
    if score < 5.0:
        return "medium"
    if score < 7.5:
        return "high"
    return "very_high"

# =========================================================
# GENERATION
# =========================================================
rows = []
geo_counter = 1
data_vintage = "2024-01-01"
inland_high_slr_records = 0

for country in countries:
    for city, postcode_prefix, base_lat, base_lon, coastal_flag, river_km in country_city_seeds.get(country, []):
        for i in range(15):
            lat = base_lat + rng.normal(0, 0.035)
            lon = base_lon + rng.normal(0, 0.045)
            postcode = build_postcode(country, postcode_prefix, i)

            river_proximity_km = max(0.05, river_km + rng.normal(0, 0.6))
            near_river = river_proximity_km < 1.0

            # Flood
            flood = rng.beta(4, 2) * 8 if near_river else rng.beta(2, 5) * 4
            if coastal_flag:
                flood += rng.uniform(0.5, 1.8)
            flood = float(np.clip(flood, 0, 10))

            # Heat
            heat = ((52 - lat) * 0.8) + rng.normal(0, 0.5)
            if country in ["ES", "IT", "US"]:
                heat += rng.uniform(0.8, 2.2)
            if country in ["NL", "BE", "GB", "DE", "LU"]:
                heat -= rng.uniform(0.0, 0.8)
            heat = float(np.clip(heat, 0, 10))

            # Sea-level rise + storm surge as hidden drivers
            if coastal_flag:
                slr = rng.uniform(0.05, 0.45)
                storm_surge = rng.beta(3, 2) * 8
            else:
                slr = rng.uniform(0.0, 0.05)
                storm_surge = rng.beta(1, 6) * 2

            # Wildfire
            if country in ["ES", "IT"]:
                wildfire = rng.beta(3, 2) * 8
            elif country == "US":
                wildfire = rng.beta(2.5, 2.5) * 7
            elif country == "FR":
                wildfire = rng.beta(2, 3) * 5
            else:
                wildfire = rng.beta(1, 6) * 2
            wildfire = float(np.clip(wildfire, 0, 10))

            # Composites
            acute = float(np.clip((0.50 * flood) + (0.30 * wildfire) + (0.20 * storm_surge), 0, 10))
            chronic = float(np.clip((0.55 * heat) + (0.35 * (slr * 10)) + (0.10 * wildfire), 0, 10))

            flood_class = expected_flood_class(flood)

            if (not coastal_flag) and (slr > 0.1):
                inland_high_slr_records += 1

            rows.append({
                "geo_id": f"GEO-{country}-{geo_counter:05d}",
                "postcode": postcode,
                "country_code": country,
                "lat": round(lat, 6),
                "lon": round(lon, 6),
                "flood_zone_class": flood_class,
                "flood_risk_score": round(flood, 2),
                "heat_stress_score": round(heat, 2),
                "sea_level_rise_m_2050": round(float(slr), 3),
                "wildfire_risk_score": round(wildfire, 2),
                "acute_risk_composite": round(acute, 2),
                "chronic_risk_composite": round(chronic, 2),
                "data_vintage": data_vintage,
            })

            geo_counter += 1

geo_risk_db = pd.DataFrame(rows)

# =========================================================
# VALIDATION
# =========================================================
score_cols = [
    "flood_risk_score",
    "heat_stress_score",
    "wildfire_risk_score",
    "acute_risk_composite",
    "chronic_risk_composite",
]

validation = {
    "rows": len(geo_risk_db),
    "countries_from_entity_master": countries,
    "countries_in_geo_risk_db": sorted(geo_risk_db["country_code"].unique()),
    "duplicate_country_postcodes": int(geo_risk_db.duplicated(["country_code", "postcode"]).sum()),
    "duplicate_geo_ids": int(geo_risk_db["geo_id"].duplicated().sum()),
    "scores_outside_0_10": int(((geo_risk_db[score_cols] < 0) | (geo_risk_db[score_cols] > 10)).sum().sum()),
    "bad_flood_zone_class": int(
        (geo_risk_db["flood_zone_class"] != geo_risk_db["flood_risk_score"].apply(expected_flood_class)).sum()
    ),
    "negative_slr_records": int((geo_risk_db["sea_level_rise_m_2050"] < 0).sum()),
    "inland_high_slr_records": inland_high_slr_records,
    "bad_data_vintage": int((geo_risk_db["data_vintage"] != data_vintage).sum()),
}

# =========================================================
# SAVE
# =========================================================
geo_risk_db.to_csv(out_path, index=False)

print(f"Generated: {out_path}")
for k, v in validation.items():
    print(f"{k}: {v}")

geo_risk_db.head(10)

Generated: Data\geo_risk_db_raw.csv
rows: 570
countries_from_entity_master: ['BE', 'DE', 'ES', 'FR', 'GB', 'IT', 'LU', 'NL', 'US']
countries_in_geo_risk_db: ['BE', 'DE', 'ES', 'FR', 'GB', 'IT', 'LU', 'NL', 'US']
duplicate_country_postcodes: 0
duplicate_geo_ids: 0
scores_outside_0_10: 0
bad_flood_zone_class: 1
negative_slr_records: 0
inland_high_slr_records: 0
bad_data_vintage: 0

,geo_id,postcode,country_code,lat,lon,flood_zone_class,flood_risk_score,heat_stress_score,sea_level_rise_m_2050,wildfire_risk_score,acute_risk_composite,chronic_risk_composite,data_vintage
0,GEO-BE-00001,1000-01,BE,50.860965,4.304901,low,2.29,0.65,0.023,0.11,1.18,0.45,2024-01-01
1,GEO-BE-00002,1000-02,BE,50.863206,4.308550,low,1.30,0.21,0.010,0.10,0.71,0.16,2024-01-01
2,GEO-BE-00003,1000-03,BE,50.832372,4.315080,low,2.15,0.91,0.042,0.37,1.24,0.68,2024-01-01
3,GEO-BE-00004,1000-04,BE,50.880800,4.361762,low,0.89,0.37,0.028,0.70,0.67,0.37,2024-01-01
4,GEO-BE-00005,1000-05,BE,50.855996,4.378080,low,1.75,0.14,0.012,0.30,0.97,0.15,2024-01-01
5,GEO-BE-00006,1000-06,BE,50.872196,4.337779,low,0.79,1.02,0.025,0.13,0.44,0.66,2024-01-01
6,GEO-BE-00007,1000-07,BE,50.791243,4.286580,high,5.87,0.99,0.036,0.43,3.13,0.71,2024-01-01
7,GEO-BE-00008,1000-08,BE,50.865505,4.362398,medium,4.71,0.45,0.032,0.21,2.43,0.38,2024-01-01
8,GEO-BE-00009,1000-09,BE,50.901516,4.298206,high,6.63,0.00,0.024,0.08,3.40,0.09,2024-01-01
9,GEO-BE-00010,1000-10,BE,50.775678,4.363747,high,5.30,0.95,0.028,0.11,2.70,0.63,2024-01-01

Counterparty Master : legal entity the bank lends to

In [ ]:
import pandas as pd
import numpy as np
import string
from pathlib import Path

# =========================================================
# CONFIG
# =========================================================
rng = np.random.default_rng(42)
DATA_DIR = Path("Data")
N_OPERATING_ROWS = 20_000
REPORTING_YEAR = 2024
USD_TO_EUR = 0.92

# =========================================================
# LOAD REFERENCE TABLES
# =========================================================
entity_master = pd.read_csv(DATA_DIR / "entity_master_raw.csv")
emission_factors = pd.read_csv(DATA_DIR / "emission_factors_raw.csv")

entity_master.columns = (
    entity_master.columns.str.strip().str.lower().str.replace(" ", "_", regex=False)
)

emission_factors.columns = (
    emission_factors.columns.str.strip().str.lower().str.replace(" ", "_", regex=False)
)

# =========================================================
# VALIDATE REFERENCES
# =========================================================
for col in ["in_scope_esg_flag", "country_code"]:
    if col not in entity_master.columns:
        raise KeyError(f"entity_master_raw.csv must contain column: {col}")

for col in ["nace_code", "emission_factor"]:
    if col not in emission_factors.columns:
        raise KeyError(f"emission_factors_raw.csv must contain column: {col}")

in_scope_countries = (
    entity_master.loc[
        entity_master["in_scope_esg_flag"].astype(str).str.lower().eq("true"),
        "country_code",
    ]
    .dropna()
    .astype(str)
    .str.upper()
    .unique()
    .tolist()
)

if not in_scope_countries:
    raise ValueError("No in-scope countries found in entity_master_raw.csv")

# =========================================================
# BUILD SECTOR REFERENCE FROM EMISSION FACTORS
# =========================================================
if "nace_description" not in emission_factors.columns:
    nace_description_map = {
        "C24.10": "Manufacture of basic iron and steel",
        "G46.90": "Wholesale trade",
        "F41.20": "Construction of buildings",
        "L68.20": "Real estate activities",
        "H49.41": "Freight transport by road",
        "D35.11": "Production of electricity",
        "B06.10": "Extraction of crude petroleum",
        "A01.11": "Growing of cereals",
        "J62.01": "Computer programming activities",
        "K64.19": "Other monetary intermediation",
    }

    emission_factors["nace_description"] = (
        emission_factors["nace_code"]
        .astype(str)
        .map(nace_description_map)
        .fillna("Sector activity")
    )

if "factor_scope" in emission_factors.columns:
    sector_mask = emission_factors["factor_scope"].astype(str).eq("sector_intensity")
elif "factor_type" in emission_factors.columns:
    sector_mask = emission_factors["factor_type"].astype(str).eq("sector_intensity")
else:
    sector_mask = pd.Series(True, index=emission_factors.index)

sector_ref = (
    emission_factors.loc[
        sector_mask
        & emission_factors["nace_code"].notna()
        & emission_factors["emission_factor"].notna(),
        ["nace_code", "nace_description", "emission_factor"],
    ]
    .drop_duplicates(subset=["nace_code"])
    .reset_index(drop=True)
)

if sector_ref.empty:
    sector_ref = pd.DataFrame(
        {
            "nace_code": ["C24.10", "G46.90", "F41.20", "L68.20", "H49.41"],
            "nace_description": [
                "Manufacture of basic iron and steel",
                "Wholesale trade",
                "Construction of buildings",
                "Real estate activities",
                "Freight transport by road",
            ],
            "emission_factor": [1420, 180, 310, 80, 550],
        }
    )

sector_ref["nace_code"] = sector_ref["nace_code"].astype(str)
sector_ref["nace_description"] = sector_ref["nace_description"].astype(str)
sector_ref["emission_factor"] = sector_ref["emission_factor"].astype(float)

# =========================================================
# SEED SOVEREIGN MACRO VALUES
# Synthetic seeded values inspired by IMF/IEA-style public statistics.
# PPP GDP values are converted to EUR using USD_TO_EUR.
# Extend these dictionaries if entity_master contains more countries.
# =========================================================
ppp_gdp_2023_usd = {
    "US": 27_360_000_000_000,
    "CN": 34_640_000_000_000,
    "DE": 5_540_000_000_000,
    "FR": 4_090_000_000_000,
    "GB": 3_980_000_000_000,
    "IT": 3_190_000_000_000,
    "ES": 2_540_000_000_000,
    "NL": 1_350_000_000_000,
    "BE": 780_000_000_000,
    "LU": 100_000_000_000,
    "TN": 180_000_000_000,
}

national_scope1_2023 = {
    "US": 4_650_000_000,
    "CN": 10_800_000_000,
    "DE": 590_000_000,
    "FR": 280_000_000,
    "GB": 320_000_000,
    "IT": 310_000_000,
    "ES": 230_000_000,
    "NL": 140_000_000,
    "BE": 95_000_000,
    "LU": 8_000_000,
    "TN": 35_000_000,
}

national_scope2_2023 = {
    "US": 1_480_000_000,
    "CN": 3_900_000_000,
    "DE": 210_000_000,
    "FR": 55_000_000,
    "GB": 95_000_000,
    "IT": 110_000_000,
    "ES": 85_000_000,
    "NL": 50_000_000,
    "BE": 35_000_000,
    "LU": 3_000_000,
    "TN": 12_000_000,
}

govt_revenue_base_eur = {
    "FR": 1_500_000_000_000,
    "DE": 1_900_000_000_000,
    "NL": 420_000_000_000,
    "GB": 1_250_000_000_000,
    "IT": 1_050_000_000_000,
    "ES": 620_000_000_000,
    "BE": 300_000_000_000,
    "LU": 28_000_000_000,
    "US": 7_000_000_000_000,
    "TN": 18_000_000_000,
}

# =========================================================
# HELPER FUNCTIONS
# =========================================================
def random_lei(i: int) -> str:
    chars = string.ascii_uppercase + string.digits
    body = "".join(rng.choice(list(chars), size=14))
    return f"SYN{i:05d}{body}"[:18] + f"{rng.integers(10, 99)}"


def make_name(segment: str, country: str, nace_desc: str, i: int) -> str:
    sector_word = str(nace_desc).split(" ")[0].replace(",", "")

    if segment == "sovereign":
        return f"Sovereign Government of {country}"

    if segment == "project_finance":
        return f"{country} {sector_word} Infrastructure Project {i:05d}"

    suffix = {
        "large_corporate": "PLC",
        "listed_corporate": "Listed PLC",
        "sme": "Ltd",
        "retail": "Individual",
    }.get(segment, "Corp")

    return f"{country} {sector_word} {suffix} {i:05d}"


# =========================================================
# GENERATE NON-SOVEREIGN COUNTERPARTIES
# Sovereign rows are added separately after this.
# =========================================================
segment_probs = {
    "sme": 0.52,
    "large_corporate": 0.26,
    "retail": 0.12,
    "listed_corporate": 0.08,
    "project_finance": 0.02,
}

segments = rng.choice(
    list(segment_probs.keys()),
    size=N_OPERATING_ROWS,
    p=list(segment_probs.values()),
)

countries = rng.choice(in_scope_countries, size=N_OPERATING_ROWS, replace=True)

sector_weights = sector_ref["emission_factor"].astype(float).clip(lower=1)
sector_weights = sector_weights / sector_weights.sum()

sector_idx = rng.choice(
    sector_ref.index,
    size=N_OPERATING_ROWS,
    replace=True,
    p=sector_weights.to_numpy(),
)

nace_codes = sector_ref.loc[sector_idx, "nace_code"].to_numpy(dtype=str)
nace_descs = sector_ref.loc[sector_idx, "nace_description"].to_numpy(dtype=str)
emission_intensity = sector_ref.loc[sector_idx, "emission_factor"].astype(float).to_numpy()

listed_flag = segments == "listed_corporate"
segment_out = np.where(segments == "listed_corporate", "large_corporate", segments)

sme = segments == "sme"
large = (segments == "large_corporate") | (segments == "listed_corporate")
retail = segments == "retail"
project = segments == "project_finance"

annual_revenue = np.full(N_OPERATING_ROWS, np.nan)
employee_count = np.full(N_OPERATING_ROWS, np.nan)

annual_revenue[sme] = rng.lognormal(
    mean=np.log(5_000_000),
    sigma=1.1,
    size=sme.sum(),
)

annual_revenue[large] = rng.lognormal(
    mean=np.log(600_000_000),
    sigma=0.9,
    size=large.sum(),
)

annual_revenue[retail] = rng.lognormal(
    mean=np.log(45_000),
    sigma=0.45,
    size=retail.sum(),
)

annual_revenue[project] = rng.lognormal(
    mean=np.log(80_000_000),
    sigma=0.75,
    size=project.sum(),
)

employee_count[sme] = rng.integers(5, 250, size=sme.sum())
employee_count[large] = rng.integers(250, 45_000, size=large.sum())
employee_count[retail] = 1
employee_count[project] = rng.integers(5, 500, size=project.sum())

asset_multiplier = np.where(
    large,
    rng.uniform(1.2, 3.5, N_OPERATING_ROWS),
    np.where(
        sme,
        rng.uniform(0.8, 2.2, N_OPERATING_ROWS),
        np.where(
            project,
            rng.uniform(3.0, 8.0, N_OPERATING_ROWS),
            rng.uniform(0.05, 0.4, N_OPERATING_ROWS),
        ),
    ),
)

total_assets = annual_revenue * asset_multiplier

# =========================================================
# NEW REQUIRED FIELDS: BOOK EQUITY, DEBT, EVIC
# =========================================================
equity_ratio = rng.uniform(0.3, 0.6, N_OPERATING_ROWS)

book_equity = total_assets * equity_ratio
total_debt = total_assets - book_equity

pb_ratio = np.clip(
    rng.lognormal(
        mean=np.log(2.0),
        sigma=0.4,
        size=N_OPERATING_ROWS,
    ),
    0.8,
    8.0,
)

market_cap = np.where(
    listed_flag,
    book_equity * pb_ratio,
    np.nan,
)

minority_interest = np.where(
    listed_flag,
    market_cap * rng.uniform(0.00, 0.05, N_OPERATING_ROWS),
    np.nan,
)

evic = np.where(
    listed_flag,
    market_cap + total_debt + np.nan_to_num(minority_interest, nan=0.0),
    book_equity + total_debt,
)

# =========================================================
# BORROWER EMISSIONS
# =========================================================
scope1 = np.where(
    ~retail,
    (annual_revenue / 1_000_000)
    * (emission_intensity / 10)
    * rng.lognormal(mean=0, sigma=0.35, size=N_OPERATING_ROWS),
    np.nan,
)

scope2 = np.where(
    ~retail,
    scope1 * rng.uniform(0.12, 0.35, N_OPERATING_ROWS),
    np.nan,
)

scope3 = np.where(
    ~retail,
    scope1 * rng.uniform(0.4, 3.0, N_OPERATING_ROWS),
    np.nan,
)

project_emissions = np.where(
    project,
    np.maximum(
        (
            np.nan_to_num(scope1, nan=0.0)
            + np.nan_to_num(scope2, nan=0.0)
        )
        * rng.uniform(0.8, 2.5, N_OPERATING_ROWS),
        10.0,
    ),
    np.nan,
)

# =========================================================
# ESG / DATA QUALITY ATTRIBUTES
# =========================================================
source_types = rng.choice(
    [
        "audited_report",
        "cdp_disclosure",
        "estimated_sector_avg",
        "proxy_model",
    ],
    size=N_OPERATING_ROWS,
    p=[0.08, 0.12, 0.55, 0.25],
)

source_types = np.where(
    project,
    "project_finance_model",
    source_types,
)

verification_flag = np.isin(
    source_types,
    ["audited_report", "cdp_disclosure"],
)

pcaf_quality_score = np.select(
    [
        source_types == "audited_report",
        source_types == "cdp_disclosure",
        source_types == "estimated_sector_avg",
        source_types == "project_finance_model",
    ],
    [2, 3, 4, 3],
    default=5,
).astype(int)

heavy_sector = (
    np.char.startswith(nace_codes.astype(str), "B")
    | np.char.startswith(nace_codes.astype(str), "C")
)

transition_base = np.where(heavy_sector, 6.5, 4.2)

transition_risk = np.clip(
    rng.normal(transition_base, 1.2),
    0,
    10,
)

sbti_target_flag = (
    (~retail)
    & (rng.random(N_OPERATING_ROWS) < np.where(large, 0.28, 0.08))
)

# =========================================================
# BUILD OPERATING COUNTERPARTY MASTER
# =========================================================
operating_df = pd.DataFrame(
    {
        "counterparty_id": [f"CP-{i:07d}" for i in range(1, N_OPERATING_ROWS + 1)],
        "legal_name": [
            make_name(seg, country, desc, i)
            for i, (seg, country, desc)
            in enumerate(zip(segments, countries, nace_descs), start=1)
        ],
        "lei_code": [random_lei(i) for i in range(1, N_OPERATING_ROWS + 1)],
        "segment": segment_out,
        "country_code": countries,
        "nace_code": nace_codes,
        "nace_description": nace_descs,

        "annual_revenue_eur": np.round(annual_revenue, 2),
        "govt_revenue_eur": np.nan,
        "ppp_adjusted_gdp_eur": np.nan,

        "total_assets_eur": np.round(total_assets, 2),
        "book_equity_eur": np.round(book_equity, 2),
        "total_debt_eur": np.round(total_debt, 2),
        "market_cap_eur": np.round(market_cap, 2),
        "minority_interest_eur": np.round(minority_interest, 2),
        "pb_ratio": np.where(listed_flag, np.round(pb_ratio, 4), np.nan),
        "evic_eur": np.round(evic, 2),

        "employee_count": pd.Series(employee_count).round().astype("Int64"),

        "borrower_scope1_tco2e": np.round(scope1, 2),
        "borrower_scope2_tco2e": np.round(scope2, 2),
        "borrower_scope3_tco2e": np.round(scope3, 2),
        "project_emissions_tco2e": np.round(project_emissions, 2),

        "national_scope1_tco2e": np.nan,
        "national_scope2_tco2e": np.nan,
        "national_scope3_tco2e": np.nan,

        "data_source_type": source_types,
        "verification_flag": verification_flag,
        "pcaf_quality_score": pcaf_quality_score,
        "transition_risk_score": np.round(transition_risk, 2),
        "sbti_target_flag": sbti_target_flag,
        "listed_flag": listed_flag,

        "reporting_year": REPORTING_YEAR,
        "created_from": "synthetic_counterparty_generation_v5_core_tables_aligned",
    }
)

# =========================================================
# GENERATE SOVEREIGN COUNTERPARTIES
# One row per in-scope country from entity_master.
# =========================================================
sovereign_rows = []
start_id = N_OPERATING_ROWS + 1

for offset, country in enumerate(sorted(in_scope_countries), start=0):
    cp_num = start_id + offset

    ppp_usd = ppp_gdp_2023_usd.get(country, 650_000_000_000) * rng.uniform(0.92, 1.08)
    ppp_eur = ppp_usd * USD_TO_EUR

    nat_s1 = national_scope1_2023.get(country, 120_000_000) * rng.uniform(0.90, 1.10)
    nat_s2 = national_scope2_2023.get(country, 35_000_000) * rng.uniform(0.90, 1.10)
    nat_s3 = (nat_s1 + nat_s2) * rng.uniform(3.0, 6.0)

    sovereign_rows.append(
        {
            "counterparty_id": f"CP-{cp_num:07d}",
            "legal_name": f"Sovereign Government of {country}",
            "lei_code": random_lei(cp_num),
            "segment": "sovereign",
            "country_code": country,
            "nace_code": "O84.11",
            "nace_description": "General public administration activities",

            "annual_revenue_eur": np.nan,
            "govt_revenue_eur": round(
                govt_revenue_base_eur.get(country, 150_000_000_000)
                * rng.uniform(0.90, 1.10),
                2,
            ),
            "ppp_adjusted_gdp_eur": round(ppp_eur, 2),

            "total_assets_eur": np.nan,
            "book_equity_eur": np.nan,
            "total_debt_eur": np.nan,
            "market_cap_eur": np.nan,
            "minority_interest_eur": np.nan,
            "pb_ratio": np.nan,
            "evic_eur": np.nan,

            "employee_count": pd.NA,

            "borrower_scope1_tco2e": np.nan,
            "borrower_scope2_tco2e": np.nan,
            "borrower_scope3_tco2e": np.nan,
            "project_emissions_tco2e": np.nan,

            "national_scope1_tco2e": round(nat_s1, 2),
            "national_scope2_tco2e": round(nat_s2, 2),
            "national_scope3_tco2e": round(nat_s3, 2),

            "data_source_type": "national_statistics",
            "verification_flag": True,
            "pcaf_quality_score": 3,
            "transition_risk_score": round(
                float(np.clip(rng.normal(3.5, 1.0), 0, 10)),
                2,
            ),
            "sbti_target_flag": False,
            "listed_flag": False,

            "reporting_year": REPORTING_YEAR,
            "created_from": "synthetic_counterparty_generation_v5_core_tables_aligned",
        }
    )

sovereign_df = pd.DataFrame(sovereign_rows)

counterparty_master = pd.concat(
    [operating_df, sovereign_df],
    ignore_index=True,
)

counterparty_master["employee_count"] = counterparty_master["employee_count"].astype("Int64")

# =========================================================
# CLEAN CONSISTENCY RULES
# =========================================================
sovereign_mask = counterparty_master["segment"].eq("sovereign")
project_mask = counterparty_master["segment"].eq("project_finance")
listed_mask = counterparty_master["listed_flag"].astype(bool)

company_only_cols = [
    "annual_revenue_eur",
    "total_assets_eur",
    "book_equity_eur",
    "total_debt_eur",
    "market_cap_eur",
    "minority_interest_eur",
    "pb_ratio",
    "evic_eur",
    "employee_count",
    "borrower_scope1_tco2e",
    "borrower_scope2_tco2e",
    "borrower_scope3_tco2e",
    "project_emissions_tco2e",
]

for col in company_only_cols:
    counterparty_master.loc[sovereign_mask, col] = np.nan

counterparty_master.loc[sovereign_mask, "listed_flag"] = False
counterparty_master.loc[sovereign_mask, "sbti_target_flag"] = False
counterparty_master.loc[sovereign_mask, "data_source_type"] = "national_statistics"
counterparty_master.loc[sovereign_mask, "pcaf_quality_score"] = 3

missing_project_emissions = (
    project_mask
    & counterparty_master["project_emissions_tco2e"].isna()
)

counterparty_master.loc[
    missing_project_emissions,
    "project_emissions_tco2e",
] = (
    counterparty_master.loc[
        missing_project_emissions,
        ["borrower_scope1_tco2e", "borrower_scope2_tco2e"],
    ]
    .sum(axis=1)
    .mul(1.2)
    .round(2)
)

# =========================================================
# VALIDATION
# =========================================================
valid_nace_set = set(sector_ref["nace_code"].astype(str)) | {"O84.11"}

listed_evic_expected = (
    counterparty_master["market_cap_eur"].fillna(0)
    + counterparty_master["total_debt_eur"].fillna(0)
    + counterparty_master["minority_interest_eur"].fillna(0)
)

unlisted_evic_expected = (
    counterparty_master["book_equity_eur"].fillna(0)
    + counterparty_master["total_debt_eur"].fillna(0)
)

listed_evic_diff = (
    listed_evic_expected
    - counterparty_master["evic_eur"].fillna(0)
).abs()

unlisted_company_mask = (~listed_mask) & (~sovereign_mask)

unlisted_evic_diff = (
    unlisted_evic_expected
    - counterparty_master["evic_eur"].fillna(0)
).abs()

validation = {
    "rows_total": len(counterparty_master),
    "operating_rows": len(operating_df),
    "sovereign_rows": int(sovereign_mask.sum()),
    "unique_counterparty_id": bool(counterparty_master["counterparty_id"].is_unique),

    "segments": counterparty_master["segment"].value_counts(dropna=False).to_dict(),

    "listed_rows": int(listed_mask.sum()),
    "listed_missing_evic": int((listed_mask & counterparty_master["evic_eur"].isna()).sum()),
    "listed_bad_evic_formula": int((listed_mask & (listed_evic_diff > 0.10)).sum()),

    "unlisted_missing_evic": int(
        (unlisted_company_mask & counterparty_master["evic_eur"].isna()).sum()
    ),
    "unlisted_bad_evic_formula": int(
        (unlisted_company_mask & (unlisted_evic_diff > 0.10)).sum()
    ),

    "sovereign_missing_ppp_gdp": int(
        (sovereign_mask & counterparty_master["ppp_adjusted_gdp_eur"].isna()).sum()
    ),
    "sovereign_missing_national_scope1": int(
        (sovereign_mask & counterparty_master["national_scope1_tco2e"].isna()).sum()
    ),
    "sovereign_missing_national_scope2": int(
        (sovereign_mask & counterparty_master["national_scope2_tco2e"].isna()).sum()
    ),
    "sovereign_missing_national_scope3": int(
        (sovereign_mask & counterparty_master["national_scope3_tco2e"].isna()).sum()
    ),
    "sovereign_wrong_source": int(
        (
            sovereign_mask
            & ~counterparty_master["data_source_type"].eq("national_statistics")
        ).sum()
    ),
    "sovereign_wrong_pcaf_score": int(
        (
            sovereign_mask
            & ~counterparty_master["pcaf_quality_score"].eq(3)
        ).sum()
    ),

    "project_finance_rows": int(project_mask.sum()),
    "project_finance_missing_project_emissions": int(
        (project_mask & counterparty_master["project_emissions_tco2e"].isna()).sum()
    ),

    "invalid_nace_codes": int(
        (~counterparty_master["nace_code"].astype(str).isin(valid_nace_set)).sum()
    ),
}

# =========================================================
# SAVE OUTPUT
# =========================================================
out_csv = DATA_DIR / "counterparty_master_raw.csv"
counterparty_master.to_csv(out_csv, index=False)

print(f"Generated CSV: {out_csv}")
print("\nValidation:")
for key, value in validation.items():
    print(f"{key}: {value}")

print("\nPreview:")
print(counterparty_master.head(10))

Generated CSV: Data\counterparty_master_raw.csv

Validation:
rows_total: 20009
operating_rows: 20000
sovereign_rows: 9
unique_counterparty_id: True
segments: {'sme': 10373, 'large_corporate': 6828, 'retail': 2394, 'project_finance': 405, 'sovereign': 9}
listed_rows: 1586
listed_missing_evic: 0
listed_bad_evic_formula: 0
unlisted_missing_evic: 0
unlisted_bad_evic_formula: 0
sovereign_missing_ppp_gdp: 0
sovereign_missing_national_scope1: 0
sovereign_missing_national_scope2: 0
sovereign_missing_national_scope3: 0
sovereign_wrong_source: 0
sovereign_wrong_pcaf_score: 0
project_finance_rows: 405
project_finance_missing_project_emissions: 0
invalid_nace_codes: 0

Preview:
  counterparty_id                        legal_name              lei_code  \
0      CP-0000001          US Manufacture PLC 00001  SYN000017C9XC3XCUW30
1      CP-0000002          BE Manufacture Ltd 00002  SYN00002Q3S5EU44V898
2      CP-0000003       DE Freight Individual 00003  SYN000035OV536PFOC75
3      CP-0000004          US Manufacture PLC 00004  SYN00004UZTLL7CUYU11
4      CP-0000005          US Manufacture Ltd 00005  SYN00005GVUKASUIK373
5      CP-0000006   FR Manufacture Listed PLC 00006  SYN00006XFW3EKW1B415
6      CP-0000007          FR Manufacture PLC 00007  SYN00007YRDV1JDX3Q88
7      CP-0000008  NL Construction Individual 00008  SYN000089E5GQ3OWIZ12
8      CP-0000009          LU Manufacture Ltd 00009  SYN00009XJW68CUB3757
9      CP-0000010              IT Freight Ltd 00010  SYN00010D81J13EQY852

           segment country_code nace_code  \
0  large_corporate           US    C24.10
1              sme           BE    C24.10
2           retail           DE    H49.41
3  large_corporate           US    C24.10
4              sme           US    C24.10
5  large_corporate           FR    C24.10
6  large_corporate           FR    C24.10
7           retail           NL    F41.20
8              sme           LU    C24.10
9              sme           IT    H49.41

                      nace_description  annual_revenue_eur  govt_revenue_eur  \
0  Manufacture of basic iron and steel        5.346690e+08               NaN
1  Manufacture of basic iron and steel        5.271349e+06               NaN
2            Freight transport by road        8.728679e+04               NaN
3  Manufacture of basic iron and steel        9.158921e+08               NaN
4  Manufacture of basic iron and steel        1.955669e+06               NaN
5  Manufacture of basic iron and steel        2.645588e+08               NaN
6  Manufacture of basic iron and steel        5.037529e+08               NaN
7            Construction of buildings        4.064075e+04               NaN
8  Manufacture of basic iron and steel        8.285566e+06               NaN
9            Freight transport by road        6.030400e+06               NaN

   ppp_adjusted_gdp_eur  ...  national_scope2_tco2e  national_scope3_tco2e  \
0                   NaN  ...                    NaN                    NaN
1                   NaN  ...                    NaN                    NaN
2                   NaN  ...                    NaN                    NaN
3                   NaN  ...                    NaN                    NaN
4                   NaN  ...                    NaN                    NaN
5                   NaN  ...                    NaN                    NaN
6                   NaN  ...                    NaN                    NaN
7                   NaN  ...                    NaN                    NaN
8                   NaN  ...                    NaN                    NaN
9                   NaN  ...                    NaN                    NaN

       data_source_type  verification_flag  pcaf_quality_score  \
0  estimated_sector_avg              False                   4
1           proxy_model              False                   5
2           proxy_model              False                   5
3  estimated_sector_avg              False                   4
4           proxy_model              False                   5
5        cdp_disclosure               True                   3
6        audited_report               True                   2
7  estimated_sector_avg              False                   4
8           proxy_model              False                   5
9           proxy_model              False                   5

   transition_risk_score  sbti_target_flag  listed_flag  reporting_year  \
0                   4.86              True        False            2024
1                   6.97              True        False            2024
2                   2.31             False        False            2024
3                   6.24             False        False            2024
4                   7.24             False        False            2024
5                   6.36             False         True            2024
6                   6.49              True        False            2024
7                   4.12             False        False            2024
8                   6.33             False        False            2024
9                   5.42             False        False            2024

                                        created_from
0  synthetic_counterparty_generation_v5_core_tabl...
1  synthetic_counterparty_generation_v5_core_tabl...
2  synthetic_counterparty_generation_v5_core_tabl...
3  synthetic_counterparty_generation_v5_core_tabl...
4  synthetic_counterparty_generation_v5_core_tabl...
5  synthetic_counterparty_generation_v5_core_tabl...
6  synthetic_counterparty_generation_v5_core_tabl...
7  synthetic_counterparty_generation_v5_core_tabl...
8  synthetic_counterparty_generation_v5_core_tabl...
9  synthetic_counterparty_generation_v5_core_tabl...

[10 rows x 33 columns]

Loan Book

In [4]:
import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# CONFIG
# =========================================================
rng = np.random.default_rng(42)

DATA_DIR = Path("Data")
OUTPUT_PATH = DATA_DIR / "loan_book_raw.csv"

N_FACILITIES = 50_000
REPORTING_DATE = pd.Timestamp("2024-12-31")

# =========================================================
# LOAD DEPENDENCIES
# =========================================================
entity_master = pd.read_csv(DATA_DIR / "entity_master_raw.csv")
counterparty_master = pd.read_csv(DATA_DIR / "counterparty_master_raw.csv")

# Normalize booleans
if "in_scope_esg_flag" in entity_master.columns:
    entity_master["in_scope_esg_flag"] = (
        entity_master["in_scope_esg_flag"]
        .astype(str)
        .str.lower()
        .eq("true")
    )

if "listed_flag" in counterparty_master.columns:
    counterparty_master["listed_flag"] = (
        counterparty_master["listed_flag"]
        .astype(str)
        .str.lower()
        .eq("true")
    )
else:
    counterparty_master["listed_flag"] = False

# =========================================================
# REQUIRED COLUMN CHECKS
# =========================================================
required_entity_cols = [
    "entity_id",
    "country_code",
    "in_scope_esg_flag",
]

required_counterparty_cols = [
    "counterparty_id",
    "segment",
    "country_code",
    "nace_code",
    "annual_revenue_eur",
    "listed_flag",
    "book_equity_eur",
    "total_debt_eur",
    "evic_eur",
    "ppp_adjusted_gdp_eur",
    "national_scope1_tco2e",
    "national_scope2_tco2e",
    "national_scope3_tco2e",
    "project_emissions_tco2e",
]

missing_entity_cols = [c for c in required_entity_cols if c not in entity_master.columns]
missing_cp_cols = [c for c in required_counterparty_cols if c not in counterparty_master.columns]

if missing_entity_cols:
    raise ValueError(f"entity_master is missing required columns: {missing_entity_cols}")

if missing_cp_cols:
    raise ValueError(f"counterparty_master is missing required columns: {missing_cp_cols}")

# Keep only in-scope ESG entities
entities = (
    entity_master.loc[
        entity_master["in_scope_esg_flag"].eq(True),
        ["entity_id", "country_code"]
    ]
    .dropna()
    .drop_duplicates()
    .reset_index(drop=True)
)

if entities.empty:
    raise ValueError("No in-scope ESG entities found in entity_master.")

cp = counterparty_master.copy()
cp["segment"] = cp["segment"].astype(str)

# =========================================================
# MAKE SURE ALL COUNTERPARTIES APPEAR AT LEAST ONCE
# =========================================================
n_counterparties = len(cp)

if N_FACILITIES < n_counterparties:
    N_FACILITIES = n_counterparties

# First part: every counterparty once
mandatory_cp_ids = cp["counterparty_id"].to_numpy()

# Remaining rows: random sample from counterparties
remaining_n = N_FACILITIES - n_counterparties
extra_cp_ids = rng.choice(
    cp["counterparty_id"].to_numpy(),
    size=remaining_n,
    replace=True
)

all_cp_ids = np.concatenate([mandatory_cp_ids, extra_cp_ids])

loan_base = pd.DataFrame({
    "facility_id": [f"FAC-{i:07d}" for i in range(1, N_FACILITIES + 1)],
    "counterparty_id": all_cp_ids,
})

# Merge counterparty attributes
loan_base = loan_base.merge(
    cp[
        [
            "counterparty_id",
            "segment",
            "country_code",
            "nace_code",
            "annual_revenue_eur",
            "listed_flag",
            "book_equity_eur",
            "total_debt_eur",
            "evic_eur",
            "ppp_adjusted_gdp_eur",
            "national_scope1_tco2e",
            "national_scope2_tco2e",
            "national_scope3_tco2e",
            "project_emissions_tco2e",
        ]
    ],
    on="counterparty_id",
    how="left"
)

# =========================================================
# ASSIGN PCAF ASSET CLASS
# =========================================================
def choose_asset_class(row):
    segment = str(row["segment"])

    if segment == "sovereign":
        return "sovereign_bond"

    if segment == "project_finance":
        return "project_finance"

    if segment == "retail":
        return rng.choice(
            ["mortgage", "motor_vehicle", "business_loan"],
            p=[0.65, 0.25, 0.10]
        )

    if segment == "sme":
        return rng.choice(
            ["business_loan", "commercial_re", "motor_vehicle", "project_finance"],
            p=[0.62, 0.25, 0.08, 0.05]
        )

    if segment in ["large_corporate", "listed_corporate"]:
        return rng.choice(
            ["business_loan", "commercial_re", "project_finance"],
            p=[0.65, 0.30, 0.05]
        )

    return rng.choice(
        ["business_loan", "commercial_re", "mortgage", "motor_vehicle", "project_finance"],
        p=[0.45, 0.20, 0.20, 0.10, 0.05]
    )

loan_base["pcaf_asset_class"] = loan_base.apply(choose_asset_class, axis=1)

# =========================================================
# FIX PROJECT FINANCE NACE LOGIC
# Some project finance rows should be renewable-energy projects.
# =========================================================
project_mask = loan_base["pcaf_asset_class"].eq("project_finance")

renewable_project_mask = (
    project_mask
    & (rng.random(N_FACILITIES) < 0.35)
)

loan_base.loc[renewable_project_mask, "nace_code"] = "D35.11"

# =========================================================
# ASSIGN ENTITY
# =========================================================
loan_base["entity_id"] = rng.choice(
    entities["entity_id"].to_numpy(),
    size=N_FACILITIES,
    replace=True
)

# Rename borrower country to avoid confusion with booking entity
loan_base = loan_base.rename(columns={"country_code": "borrower_country_code"})

# Add booking country from selected entity
entity_country_map = entities.set_index("entity_id")["country_code"].to_dict()
loan_base["booking_country_code"] = loan_base["entity_id"].map(entity_country_map)

# =========================================================
# PRODUCT TYPE
# =========================================================
product_type_map = {
    "business_loan": ["term_loan", "revolver"],
    "mortgage": ["mortgage"],
    "commercial_re": ["commercial_mortgage", "term_loan"],
    "motor_vehicle": ["vehicle_loan", "leasing"],
    "sovereign_bond": ["sovereign_bond"],
    "project_finance": ["project_loan", "project_equity"],
}

product_type = []

for asset_class in loan_base["pcaf_asset_class"]:
    choices = product_type_map[asset_class]

    if asset_class == "business_loan":
        product_type.append(rng.choice(choices, p=[0.75, 0.25]))

    elif asset_class == "commercial_re":
        product_type.append(rng.choice(choices, p=[0.75, 0.25]))

    elif asset_class == "motor_vehicle":
        product_type.append(rng.choice(choices, p=[0.70, 0.30]))

    elif asset_class == "project_finance":
        product_type.append(rng.choice(choices, p=[0.85, 0.15]))

    else:
        product_type.append(choices[0])

loan_base["product_type"] = product_type

# =========================================================
# INSTRUMENT TYPE AND CONTROL LOGIC
# =========================================================
loan_base["instrument_type"] = pd.Series(pd.NA, index=loan_base.index, dtype="object")

project_mask = loan_base["pcaf_asset_class"].eq("project_finance")

loan_base.loc[project_mask, "instrument_type"] = loan_base.loc[
    project_mask,
    "product_type"
].map({
    "project_loan": "debt",
    "project_equity": "equity",
})

loan_base["has_control"] = False

project_equity_mask = (
    loan_base["pcaf_asset_class"].eq("project_finance")
    & loan_base["instrument_type"].eq("equity")
)

loan_base.loc[project_equity_mask, "has_control"] = (
    rng.random(project_equity_mask.sum()) < 0.60
)

# =========================================================
# BALANCES
# =========================================================
asset_class = loan_base["pcaf_asset_class"].to_numpy()
segment = loan_base["segment"].astype(str).to_numpy()

base_balance = np.select(
    [
        asset_class == "mortgage",
        asset_class == "commercial_re",
        asset_class == "motor_vehicle",
        asset_class == "sovereign_bond",
        asset_class == "project_finance",
        asset_class == "business_loan",
    ],
    [
        rng.lognormal(mean=np.log(250_000), sigma=0.55, size=N_FACILITIES),
        rng.lognormal(mean=np.log(3_000_000), sigma=0.85, size=N_FACILITIES),
        rng.lognormal(mean=np.log(35_000), sigma=0.35, size=N_FACILITIES),
        rng.lognormal(mean=np.log(25_000_000), sigma=0.90, size=N_FACILITIES),
        rng.lognormal(mean=np.log(12_000_000), sigma=0.95, size=N_FACILITIES),
        rng.lognormal(mean=np.log(900_000), sigma=1.05, size=N_FACILITIES),
    ],
    default=rng.lognormal(mean=np.log(750_000), sigma=1.00, size=N_FACILITIES)
)

segment_multiplier = pd.Series(segment).map({
    "retail": 0.25,
    "sme": 1.0,
    "large_corporate": 7.0,
    "listed_corporate": 10.0,
    "sovereign": 20.0,
    "project_finance": 12.0,
}).fillna(1.0).to_numpy()

outstanding_balance = base_balance * segment_multiplier

outstanding_balance = np.clip(
    outstanding_balance,
    5_000,
    500_000_000
)

committed_limit = outstanding_balance * rng.uniform(
    1.02,
    1.60,
    size=N_FACILITIES
)

ead = outstanding_balance * rng.uniform(
    1.00,
    1.25,
    size=N_FACILITIES
)

# For controlled project equity, exposure equals investment amount
controlled_project_equity = (
    loan_base["pcaf_asset_class"].eq("project_finance")
    & loan_base["instrument_type"].eq("equity")
    & loan_base["has_control"].eq(True)
)

committed_limit[controlled_project_equity.to_numpy()] = outstanding_balance[
    controlled_project_equity.to_numpy()
]

ead[controlled_project_equity.to_numpy()] = outstanding_balance[
    controlled_project_equity.to_numpy()
]

loan_base["outstanding_balance_eur"] = outstanding_balance.round(2)
loan_base["committed_limit_eur"] = committed_limit.round(2)
loan_base["ead_eur"] = ead.round(2)

# =========================================================
# VEHICLE-SPECIFIC DENOMINATORS
# =========================================================
loan_base["vehicle_value_at_origination_eur"] = np.nan
loan_base["vehicle_annual_emissions_tco2e"] = np.nan

vehicle_mask = loan_base["pcaf_asset_class"].eq("motor_vehicle")

vehicle_ltv_at_origination = rng.uniform(
    0.55,
    0.82,
    size=vehicle_mask.sum()
)

loan_base.loc[vehicle_mask, "vehicle_value_at_origination_eur"] = (
    loan_base.loc[vehicle_mask, "outstanding_balance_eur"].to_numpy()
    / vehicle_ltv_at_origination
).round(2)

vehicle_emissions_gco2_per_km = rng.uniform(
    100,
    220,
    size=vehicle_mask.sum()
)

vehicle_annual_km = rng.uniform(
    12_000,
    22_000,
    size=vehicle_mask.sum()
)

loan_base.loc[vehicle_mask, "vehicle_annual_emissions_tco2e"] = (
    vehicle_emissions_gco2_per_km
    * vehicle_annual_km
    / 1_000_000
).round(3)

# Compatibility alias if later code expects old name
loan_base["vehicle_value_eur"] = loan_base["vehicle_value_at_origination_eur"]

# =========================================================
# PROJECT FINANCE DENOMINATORS
# =========================================================
loan_base["total_project_cost_eur"] = np.nan
loan_base["project_annual_emissions_tco2e"] = np.nan

project_mask = loan_base["pcaf_asset_class"].eq("project_finance")

project_bank_share = rng.uniform(
    0.25,
    0.65,
    size=project_mask.sum()
)

loan_base.loc[project_mask, "total_project_cost_eur"] = (
    loan_base.loc[project_mask, "outstanding_balance_eur"].to_numpy()
    / project_bank_share
).round(2)

renewable_project_mask = (
    loan_base["pcaf_asset_class"].eq("project_finance")
    & loan_base["nace_code"].eq("D35.11")
)

infrastructure_project_mask = (
    loan_base["pcaf_asset_class"].eq("project_finance")
    & ~loan_base["nace_code"].eq("D35.11")
)

loan_base.loc[renewable_project_mask, "project_annual_emissions_tco2e"] = (
    rng.lognormal(
        mean=np.log(500),
        sigma=0.8,
        size=renewable_project_mask.sum()
    )
).round(2)

loan_base.loc[infrastructure_project_mask, "project_annual_emissions_tco2e"] = (
    rng.lognormal(
        mean=np.log(5_000),
        sigma=0.7,
        size=infrastructure_project_mask.sum()
    )
).round(2)

# If counterparty has project_emissions_tco2e, use it as fallback where needed
missing_project_emissions = (
    project_mask
    & loan_base["project_annual_emissions_tco2e"].isna()
    & loan_base["project_emissions_tco2e"].notna()
)

loan_base.loc[missing_project_emissions, "project_annual_emissions_tco2e"] = (
    loan_base.loc[missing_project_emissions, "project_emissions_tco2e"]
)

# =========================================================
# DATES
# =========================================================
origination_start = pd.Timestamp("2015-01-01")
origination_days = (REPORTING_DATE - origination_start).days

origination_dates = (
    origination_start
    + pd.to_timedelta(
        rng.integers(0, origination_days, size=N_FACILITIES),
        unit="D"
    )
)

maturity_years = []

for asset in loan_base["pcaf_asset_class"]:
    if asset == "mortgage":
        maturity_years.append(rng.integers(10, 31))

    elif asset == "commercial_re":
        maturity_years.append(rng.integers(5, 16))

    elif asset == "sovereign_bond":
        maturity_years.append(rng.integers(2, 31))

    elif asset == "project_finance":
        maturity_years.append(rng.integers(7, 26))

    elif asset == "motor_vehicle":
        maturity_years.append(rng.integers(2, 8))

    else:
        maturity_years.append(rng.integers(1, 9))

maturity_dates = [
    origination_date + pd.DateOffset(years=int(years))
    for origination_date, years in zip(origination_dates, maturity_years)
]

loan_base["origination_date"] = origination_dates.date
loan_base["maturity_date"] = [d.date() for d in maturity_dates]
loan_base["reporting_date"] = REPORTING_DATE.date()

# =========================================================
# CURRENCY
# =========================================================
loan_base["currency"] = rng.choice(
    ["EUR", "USD", "GBP"],
    size=N_FACILITIES,
    p=[0.88, 0.08, 0.04]
)

# =========================================================
# GREEN LABEL
# =========================================================
green_prob = np.select(
    [
        loan_base["pcaf_asset_class"].eq("project_finance"),
        loan_base["pcaf_asset_class"].eq("commercial_re"),
        loan_base["pcaf_asset_class"].eq("mortgage"),
        loan_base["pcaf_asset_class"].eq("business_loan"),
        loan_base["pcaf_asset_class"].eq("motor_vehicle"),
        loan_base["pcaf_asset_class"].eq("sovereign_bond"),
    ],
    [
        0.22,
        0.13,
        0.09,
        0.06,
        0.04,
        0.03,
    ],
    default=0.03
)

loan_base["green_label_flag"] = rng.random(N_FACILITIES) < green_prob

# Avoid np.where string + np.nan dtype error
loan_base["green_taxonomy"] = pd.Series(pd.NA, index=loan_base.index, dtype="object")

green_mask = loan_base["green_label_flag"].eq(True)

loan_base.loc[green_mask, "green_taxonomy"] = rng.choice(
    ["EU Taxonomy", "LMA GLP", "ICMA GBP"],
    size=green_mask.sum(),
    p=[0.55, 0.25, 0.20]
)

# =========================================================
# DATA QUALITY SCORE
# =========================================================
loan_base["data_quality_score"] = rng.choice(
    [1, 2, 3, 4, 5],
    size=N_FACILITIES,
    p=[0.05, 0.12, 0.33, 0.35, 0.15]
)

# Project finance modelled emissions are usually lower-quality than verified company data
loan_base.loc[
    loan_base["pcaf_asset_class"].eq("project_finance"),
    "data_quality_score"
] = rng.choice(
    [2, 3, 4, 5],
    size=loan_base["pcaf_asset_class"].eq("project_finance").sum(),
    p=[0.15, 0.35, 0.35, 0.15]
)

# Sovereign statistics are national-statistics based
loan_base.loc[
    loan_base["pcaf_asset_class"].eq("sovereign_bond"),
    "data_quality_score"
] = 3

# =========================================================
# ATTRIBUTION DENOMINATOR TYPE
# =========================================================
loan_base["attribution_denominator_type"] = pd.Series(
    "unknown",
    index=loan_base.index,
    dtype="object"
)

# Business loans:
# - listed companies use EVIC
# - unlisted companies use revenue as approximation in this synthetic model
business_mask = loan_base["pcaf_asset_class"].eq("business_loan")

loan_base.loc[
    business_mask & loan_base["listed_flag"].eq(True),
    "attribution_denominator_type"
] = "evic_eur"

loan_base.loc[
    business_mask & loan_base["listed_flag"].eq(False),
    "attribution_denominator_type"
] = "annual_revenue_eur"

# Sovereign bonds use PPP-adjusted GDP denominator
loan_base.loc[
    loan_base["pcaf_asset_class"].eq("sovereign_bond"),
    "attribution_denominator_type"
] = "ppp_adjusted_gdp_eur"

# Motor vehicles use vehicle value at origination
loan_base.loc[
    loan_base["pcaf_asset_class"].eq("motor_vehicle"),
    "attribution_denominator_type"
] = "vehicle_value_at_origination_eur"

# Project finance:
# - control equity = 100%
# - otherwise use total project cost
loan_base.loc[
    loan_base["pcaf_asset_class"].eq("project_finance")
    & loan_base["has_control"].eq(True),
    "attribution_denominator_type"
] = "control_equals_100_percent"

loan_base.loc[
    loan_base["pcaf_asset_class"].eq("project_finance")
    & loan_base["has_control"].eq(False),
    "attribution_denominator_type"
] = "total_project_cost_eur"

# Mortgage and commercial RE use collateral table later
loan_base.loc[
    loan_base["pcaf_asset_class"].isin(["mortgage", "commercial_re"]),
    "attribution_denominator_type"
] = "collateral_value_at_origination_eur"

# =========================================================
# FINAL COLUMN ORDER
# =========================================================
loan_book = loan_base[
    [
        "facility_id",
        "entity_id",
        "booking_country_code",
        "counterparty_id",
        "segment",
        "product_type",
        "pcaf_asset_class",
        "instrument_type",
        "has_control",
        "nace_code",
        "borrower_country_code",

        "outstanding_balance_eur",
        "committed_limit_eur",
        "ead_eur",

        "annual_revenue_eur",
        "listed_flag",
        "book_equity_eur",
        "total_debt_eur",
        "evic_eur",

        "ppp_adjusted_gdp_eur",
        "national_scope1_tco2e",
        "national_scope2_tco2e",
        "national_scope3_tco2e",

        "vehicle_value_at_origination_eur",
        "vehicle_value_eur",
        "vehicle_annual_emissions_tco2e",

        "total_project_cost_eur",
        "project_annual_emissions_tco2e",

        "origination_date",
        "maturity_date",
        "currency",

        "green_label_flag",
        "green_taxonomy",
        "data_quality_score",

        "attribution_denominator_type",
        "reporting_date",
    ]
].copy()

# =========================================================
# VALIDATION
# =========================================================
validation = {
    "loan_book_rows": len(loan_book),
    "counterparty_rows": len(counterparty_master),
    "unique_facility_id": int(loan_book["facility_id"].is_unique),

    "counterparty_ids_missing_from_loan_book": int(
        (~counterparty_master["counterparty_id"].isin(loan_book["counterparty_id"])).sum()
    ),

    "loan_rows_with_missing_counterparty_id": int(
        loan_book["counterparty_id"].isna().sum()
    ),

    "asset_class_counts": loan_book["pcaf_asset_class"].value_counts().to_dict(),

    "bad_sovereign_label_rows": int(
        loan_book["pcaf_asset_class"].eq("sovereign").sum()
    ),

    "sovereign_bond_rows": int(
        loan_book["pcaf_asset_class"].eq("sovereign_bond").sum()
    ),

    "project_finance_rows": int(
        loan_book["pcaf_asset_class"].eq("project_finance").sum()
    ),

    "motor_vehicle_missing_vehicle_value_at_origination": int(
        (
            loan_book["pcaf_asset_class"].eq("motor_vehicle")
            & loan_book["vehicle_value_at_origination_eur"].isna()
        ).sum()
    ),

    "motor_vehicle_missing_vehicle_annual_emissions": int(
        (
            loan_book["pcaf_asset_class"].eq("motor_vehicle")
            & loan_book["vehicle_annual_emissions_tco2e"].isna()
        ).sum()
    ),

    "project_finance_missing_total_project_cost": int(
        (
            loan_book["pcaf_asset_class"].eq("project_finance")
            & loan_book["total_project_cost_eur"].isna()
        ).sum()
    ),

    "project_finance_missing_instrument_type": int(
        (
            loan_book["pcaf_asset_class"].eq("project_finance")
            & loan_book["instrument_type"].isna()
        ).sum()
    ),

    "project_finance_missing_project_emissions": int(
        (
            loan_book["pcaf_asset_class"].eq("project_finance")
            & loan_book["project_annual_emissions_tco2e"].isna()
        ).sum()
    ),

    "business_loan_listed_missing_evic": int(
        (
            loan_book["pcaf_asset_class"].eq("business_loan")
            & loan_book["listed_flag"].eq(True)
            & loan_book["evic_eur"].isna()
        ).sum()
    ),

    "sovereign_bond_missing_ppp_gdp": int(
        (
            loan_book["pcaf_asset_class"].eq("sovereign_bond")
            & loan_book["ppp_adjusted_gdp_eur"].isna()
        ).sum()
    ),

    "outstanding_greater_than_committed_limit": int(
        (
            loan_book["outstanding_balance_eur"]
            > loan_book["committed_limit_eur"]
        ).sum()
    ),

    "ead_less_than_outstanding": int(
        (
            loan_book["ead_eur"]
            < loan_book["outstanding_balance_eur"]
        ).sum()
    ),
}

print("VALIDATION")
for key, value in validation.items():
    print(f"{key}: {value}")

# Hard validation errors
if validation["counterparty_ids_missing_from_loan_book"] != 0:
    raise ValueError("Some counterparty_master IDs are missing from loan_book.")

if validation["bad_sovereign_label_rows"] != 0:
    raise ValueError("Found old sovereign label. Use sovereign_bond only.")

if validation["motor_vehicle_missing_vehicle_value_at_origination"] != 0:
    raise ValueError("Some motor_vehicle rows are missing vehicle_value_at_origination_eur.")

if validation["project_finance_missing_total_project_cost"] != 0:
    raise ValueError("Some project_finance rows are missing total_project_cost_eur.")

if validation["project_finance_missing_instrument_type"] != 0:
    raise ValueError("Some project_finance rows are missing instrument_type.")

if validation["outstanding_greater_than_committed_limit"] != 0:
    raise ValueError("Some rows have outstanding_balance_eur > committed_limit_eur.")

if validation["ead_less_than_outstanding"] != 0:
    raise ValueError("Some rows have ead_eur < outstanding_balance_eur.")

# =========================================================
# SAVE
# =========================================================
loan_book.to_csv(OUTPUT_PATH, index=False)

print(f"\nSaved: {OUTPUT_PATH}")
print(loan_book.head())

VALIDATION
loan_book_rows: 50000
counterparty_rows: 20009
unique_facility_id: 1
counterparty_ids_missing_from_loan_book: 0
loan_rows_with_missing_counterparty_id: 0
asset_class_counts: {np.str_('business_loan'): 27582, np.str_('commercial_re'): 11792, np.str_('mortgage'): 3890, np.str_('motor_vehicle'): 3598, np.str_('project_finance'): 3115, 'sovereign_bond': 23}
bad_sovereign_label_rows: 0
sovereign_bond_rows: 23
project_finance_rows: 3115
motor_vehicle_missing_vehicle_value_at_origination: 0
motor_vehicle_missing_vehicle_annual_emissions: 0
project_finance_missing_total_project_cost: 0
project_finance_missing_instrument_type: 0
project_finance_missing_project_emissions: 0
business_loan_listed_missing_evic: 0
sovereign_bond_missing_ppp_gdp: 0
outstanding_greater_than_committed_limit: 0
ead_less_than_outstanding: 0

Saved: Data\loan_book_raw.csv
   facility_id   entity_id booking_country_code counterparty_id  \
0  FAC-0000001  ENT-LU-009                   LU      CP-0000001
1  FAC-0000002  ENT-US-010                   US      CP-0000002
2  FAC-0000003  ENT-FR-002                   FR      CP-0000003
3  FAC-0000004  ENT-LU-009                   LU      CP-0000004
4  FAC-0000005  ENT-ES-006                   ES      CP-0000005

           segment         product_type pcaf_asset_class instrument_type  \
0  large_corporate            term_loan    business_loan            <NA>
1              sme            term_loan    business_loan            <NA>
2           retail             mortgage         mortgage            <NA>
3  large_corporate  commercial_mortgage    commercial_re            <NA>
4              sme            term_loan    business_loan            <NA>

   has_control nace_code  ... total_project_cost_eur  \
0        False    C24.10  ...                    NaN
1        False    C24.10  ...                    NaN
2        False    H49.41  ...                    NaN
3        False    C24.10  ...                    NaN
4        False    C24.10  ...                    NaN

   project_annual_emissions_tco2e  origination_date  maturity_date  currency  \
0                             NaN        2018-04-08     2022-04-08       EUR
1                             NaN        2022-04-27     2029-04-27       EUR
2                             NaN        2022-07-22     2041-07-22       EUR
3                             NaN        2019-05-20     2030-05-20       EUR
4                             NaN        2019-05-10     2021-05-10       EUR

   green_label_flag  green_taxonomy  data_quality_score  \
0             False            <NA>                   4
1             False            <NA>                   4
2             False            <NA>                   4
3             False            <NA>                   3
4             False            <NA>                   3

          attribution_denominator_type  reporting_date
0                   annual_revenue_eur      2024-12-31
1                   annual_revenue_eur      2024-12-31
2  collateral_value_at_origination_eur      2024-12-31
3  collateral_value_at_origination_eur      2024-12-31
4                   annual_revenue_eur      2024-12-31

[5 rows x 36 columns]

Collateral Register : Collateral items acting as security against a loan

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

rng = np.random.default_rng(42)

# =========================
# CONFIG
# =========================
DATA_DIR = Path("Data")

# If needed, use full Windows path instead:
# DATA_DIR = Path(r"C:\Users\HP\Documents\IFRS_Reporting\Data")

# =========================
# LOAD DEPENDENCIES
# =========================
loan_book = pd.read_csv(DATA_DIR / "loan_book_raw.csv")
entity_master = pd.read_csv(DATA_DIR / "entity_master_raw.csv")
geo_risk_db = pd.read_csv(DATA_DIR / "geo_risk_db_raw.csv")
emission_factors = pd.read_csv(DATA_DIR / "emission_factors_raw.csv")

# Clean column names
loan_book.columns = (
    loan_book.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

entity_master.columns = (
    entity_master.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

geo_risk_db.columns = (
    geo_risk_db.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

emission_factors.columns = (
    emission_factors.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

# Support old geo naming if needed
if "geo_id" not in geo_risk_db.columns and "geo_id" in geo_risk_db.columns:
    geo_risk_db = geo_risk_db.rename(columns={"geo_id": "geo_id"})

# Support updated loan_book naming
if "country_code" not in loan_book.columns:
    if "borrower_country_code" in loan_book.columns:
        loan_book["country_code"] = loan_book["borrower_country_code"]
    elif "booking_country_code" in loan_book.columns:
        loan_book["country_code"] = loan_book["booking_country_code"]
    else:
        raise ValueError("loan_book must contain country_code, borrower_country_code, or booking_country_code")

# Normalize entity boolean
if entity_master["in_scope_esg_flag"].dtype == object:
    entity_master["in_scope_esg_flag"] = (
        entity_master["in_scope_esg_flag"]
        .astype(str)
        .str.lower()
        .eq("true")
    )

# Required updated geo columns
required_geo_cols = [
    "geo_id",
    "postcode",
    "country_code",
    "lat",
    "lon",
    "flood_zone_class",
    "flood_risk_score",
    "heat_stress_score",
    "sea_level_rise_m_2050",
    "acute_risk_composite",
    "chronic_risk_composite",
]

missing_geo_cols = [c for c in required_geo_cols if c not in geo_risk_db.columns]
if missing_geo_cols:
    raise ValueError(f"geo_risk_db is missing required columns: {missing_geo_cols}")

required_loan_cols = [
    "facility_id",
    "counterparty_id",
    "entity_id",
    "pcaf_asset_class",
    "outstanding_balance_eur",
    "origination_date",
    "reporting_date",
    "country_code",
]

missing_loan_cols = [c for c in required_loan_cols if c not in loan_book.columns]
if missing_loan_cols:
    raise ValueError(f"loan_book is missing required columns: {missing_loan_cols}")

# Keep only in-scope ESG entities
in_scope_entities = set(
    entity_master.loc[
        entity_master["in_scope_esg_flag"],
        "entity_id"
    ]
)

loan_book = loan_book[
    loan_book["entity_id"].isin(in_scope_entities)
].copy()

# =========================
# GRID EMISSION FACTOR HELPER
# =========================
fallback_grid_factors = {
    "DE": 0.380,
    "FR": 0.052,
    "GB": 0.207,
    "NL": 0.340,
    "IT": 0.272,
    "ES": 0.180,
    "BE": 0.170,
    "LU": 0.090,
    "US": 0.390,
    "TN": 0.410,
}

def get_grid_factor(country_code, reporting_year=2024):
    """
    Returns tCO2e/MWh grid factor.
    Tries to use emission_factors table first by country_code.
    Falls back to synthetic country-level defaults.
    """
    country_code = str(country_code).upper()
    ef = emission_factors.copy()

    if not {"country_code", "emission_factor"}.issubset(ef.columns):
        return fallback_grid_factors.get(country_code, 0.250)

    mask = ef["country_code"].astype(str).str.upper().eq(country_code)

    if "year" in ef.columns:
        mask = mask & ef["year"].astype(str).eq(str(reporting_year))

    scope_filter_applied = False

    if "factor_type" in ef.columns:
        ft_mask = ef["factor_type"].astype(str).str.contains(
            "grid|electricity|scope2",
            case=False,
            na=False,
        )
        if ft_mask.any():
            mask = mask & ft_mask
            scope_filter_applied = True

    if not scope_filter_applied and "factor_scope" in ef.columns:
        fs_mask = ef["factor_scope"].astype(str).str.contains(
            "grid|electricity|scope2",
            case=False,
            na=False,
        )
        if fs_mask.any():
            mask = mask & fs_mask
            scope_filter_applied = True

    if not scope_filter_applied and "source" in ef.columns:
        src_mask = ef["source"].astype(str).str.contains(
            "grid|electricity|iea",
            case=False,
            na=False,
        )
        if src_mask.any():
            mask = mask & src_mask

    matched = ef[mask]

    if len(matched) > 0:
        return float(matched["emission_factor"].iloc[0])

    # Country-only fallback from emission_factors if detailed filter does not match
    country_only = ef[ef["country_code"].astype(str).str.upper().eq(country_code)]
    if len(country_only) > 0:
        return float(country_only["emission_factor"].iloc[0])

    return fallback_grid_factors.get(country_code, 0.250)

# =========================
# COLLATERAL GENERATION
# =========================
# Collateral exists mainly for mortgage and commercial real estate facilities.
secured = loan_book[
    loan_book["pcaf_asset_class"].isin(["mortgage", "commercial_re"])
].copy().reset_index(drop=True)

if secured.empty:
    raise ValueError("No mortgage or commercial_re rows found in loan_book. Cannot generate collateral_register.")

is_mortgage = secured["pcaf_asset_class"].eq("mortgage").to_numpy()

# Mortgage: usually secured by at least one property.
# Commercial RE: some facilities are unsecured or partially secured.
collateral_counts = np.where(
    is_mortgage,
    rng.choice([1, 2, 3], p=[0.68, 0.27, 0.05], size=len(secured)),
    rng.choice([0, 1, 2, 3], p=[0.35, 0.45, 0.15, 0.05], size=len(secured)),
)

secured["collateral_count"] = collateral_counts
secured = secured[secured["collateral_count"] > 0].copy()

collateral = secured.loc[
    secured.index.repeat(secured["collateral_count"])
].reset_index(drop=True)

n = len(collateral)

collateral["collateral_sequence"] = (
    collateral.groupby("facility_id").cumcount() + 1
)

is_mortgage_expanded = collateral["pcaf_asset_class"].eq("mortgage").to_numpy()

# Collateral type conditional on product/asset class
collateral_type = np.where(
    is_mortgage_expanded,
    rng.choice(["residential_property", "land"], p=[0.90, 0.10], size=n),
    rng.choice(["commercial_property", "land", "equipment"], p=[0.70, 0.20, 0.10], size=n),
)

# =========================
# ALLOCATED BALANCE
# =========================
allocated_balance = (
    collateral["outstanding_balance_eur"].to_numpy()
    / collateral["collateral_count"].to_numpy()
)

# =========================
# ORIGINATION LTV AND COLLATERAL VALUE AT ORIGINATION
# =========================
residential_mask = collateral_type == "residential_property"
commercial_mask = collateral_type == "commercial_property"
land_mask = collateral_type == "land"
equipment_mask = collateral_type == "equipment"

ltv_at_origination = np.full(n, np.nan)

ltv_at_origination[residential_mask] = (
    rng.beta(5, 3, size=int(residential_mask.sum())) * 0.45 + 0.35
)

ltv_at_origination[commercial_mask] = (
    rng.beta(5, 3, size=int(commercial_mask.sum())) * 0.40 + 0.35
)

# For land and equipment, keep a realistic collateral LTV so collateral value can still exist.
other_mask = land_mask | equipment_mask
ltv_at_origination[other_mask] = (
    rng.beta(4, 4, size=int(other_mask.sum())) * 0.55 + 0.25
)

ltv_at_origination = np.clip(ltv_at_origination, 0.10, 0.95)

collateral_value_at_origination = allocated_balance / ltv_at_origination

# =========================
# CURRENT COLLATERAL VALUE DRIFT
# collateral_value_eur = origination value × (1 + annual_return) ^ years_held
# =========================
origination_date = pd.to_datetime(collateral["origination_date"])
reporting_date = pd.to_datetime(collateral["reporting_date"])

years_held = (
    (reporting_date - origination_date).dt.days.clip(lower=0) / 365.25
).to_numpy()

annual_return = rng.normal(0.03, 0.08, size=n)
annual_return = np.clip(annual_return, -0.35, 0.35)

collateral_value = collateral_value_at_origination * np.power(
    1 + annual_return,
    years_held,
)

# Safety floor to avoid impossible current values
collateral_value = np.maximum(collateral_value, allocated_balance * 0.20)

current_ltv_ratio = allocated_balance / collateral_value

# =========================
# GEO ENRICHMENT FROM geo_risk_db
# =========================
selected_geo_parts = []

for country, group in collateral.groupby("country_code", sort=False):
    geo_country = geo_risk_db[
        geo_risk_db["country_code"].astype(str).str.upper().eq(str(country).upper())
    ].reset_index(drop=True)

    if geo_country.empty:
        geo_country = geo_risk_db.reset_index(drop=True)

    selected = geo_country.iloc[
        rng.integers(0, len(geo_country), size=len(group))
    ].reset_index(drop=True)

    selected.index = group.index
    selected_geo_parts.append(selected)

selected_geo = pd.concat(selected_geo_parts).sort_index()

sea_level_rise_flag = (
    selected_geo["sea_level_rise_m_2050"].astype(float) >= 0.10
)

# =========================
# EPC, FLOOR AREA, BUILDING EMISSIONS
# =========================
epc_energy_intensity_map = {
    "A": 50,
    "B": 100,
    "C": 170,
    "D": 250,
    "E": 340,
    "F": 450,
    "G": 600,
}

epc_ratings = np.array(["A", "B", "C", "D", "E", "F", "G"])
epc_probs = np.array([0.03, 0.08, 0.27, 0.30, 0.20, 0.10, 0.02])

# Initialize as object because EPC values are letters
epc_rating = np.full(n, None, dtype=object)
floor_area_m2 = np.full(n, np.nan)
epc_energy_intensity_kwh_m2_year = np.full(n, np.nan)
grid_emission_factor_tco2e_mwh = np.full(n, np.nan)
building_emissions_tco2e = np.full(n, np.nan)

building_collateral_mask = residential_mask | commercial_mask

# EPC applies to buildings only
epc_rating[building_collateral_mask] = rng.choice(
    epc_ratings,
    p=epc_probs,
    size=int(building_collateral_mask.sum()),
)

# Floor area per requirement
floor_area_m2[residential_mask] = np.clip(
    rng.lognormal(mean=np.log(120), sigma=0.5, size=int(residential_mask.sum())),
    30,
    500,
)

floor_area_m2[commercial_mask] = np.clip(
    rng.lognormal(mean=np.log(800), sigma=0.7, size=int(commercial_mask.sum())),
    100,
    50_000,
)

# Energy intensity by EPC
for rating, intensity in epc_energy_intensity_map.items():
    rating_mask = epc_rating == rating
    epc_energy_intensity_kwh_m2_year[rating_mask] = intensity

# Grid factors by country from emission_factors joined on country_code logic
reporting_years = reporting_date.dt.year.fillna(2024).astype(int)

for idx in range(n):
    if building_collateral_mask[idx]:
        grid_emission_factor_tco2e_mwh[idx] = get_grid_factor(
            selected_geo["country_code"].iloc[idx],
            reporting_years.iloc[idx],
        )

# building_emissions_tco2e = floor_area × EPC intensity × grid EF / 1000
building_emissions_tco2e[building_collateral_mask] = (
    floor_area_m2[building_collateral_mask]
    * epc_energy_intensity_kwh_m2_year[building_collateral_mask]
    * grid_emission_factor_tco2e_mwh[building_collateral_mask]
    / 1000
)

# =========================
# VALUATION DATE
# =========================
days_between = (
    reporting_date - origination_date
).dt.days.clip(lower=0).to_numpy()

offsets = np.array([
    rng.integers(0, int(days) + 1) if days > 0 else 0
    for days in days_between
])

valuation_date = origination_date + pd.to_timedelta(offsets, unit="D")

# =========================
# FINAL TABLE
# =========================
collateral_register = pd.DataFrame({
    "collateral_id": [f"COL-{i:08d}" for i in range(1, n + 1)],
    "facility_id": collateral["facility_id"].to_numpy(),
    "counterparty_id": collateral["counterparty_id"].to_numpy(),
    "entity_id": collateral["entity_id"].to_numpy(),

    "collateral_type": collateral_type,
    "allocated_outstanding_balance_eur": np.round(allocated_balance, 2),

    # Required origination/current collateral values
    "ltv_at_origination": np.round(ltv_at_origination, 4),
    "collateral_value_at_origination_eur": np.round(collateral_value_at_origination, 2),
    "annual_return_assumption": np.round(annual_return, 6),
    "years_held": np.round(years_held, 4),
    "collateral_value_eur": np.round(collateral_value, 2),
    "ltv_ratio": np.round(current_ltv_ratio, 4),
    "valuation_date": valuation_date.dt.strftime("%Y-%m-%d"),

    # Building emissions inputs for PCAF mortgage/commercial RE logic
    "floor_area_m2": np.round(floor_area_m2, 1),
    "epc_rating": epc_rating,
    "epc_energy_intensity_kwh_m2_year": np.round(epc_energy_intensity_kwh_m2_year, 2),
    "grid_emission_factor_tco2e_mwh": np.round(grid_emission_factor_tco2e_mwh, 6),
    "building_emissions_tco2e": np.round(building_emissions_tco2e, 4),

    # Geo join fields / physical climate risk enrichment
    "geo_id": selected_geo["geo_id"].to_numpy(),
    "postcode": selected_geo["postcode"].astype(str).to_numpy(),
    "lat": selected_geo["lat"].astype(float).round(6).to_numpy(),
    "lon": selected_geo["lon"].astype(float).round(6).to_numpy(),
    "country_code": selected_geo["country_code"].to_numpy(),
    "flood_zone_class": selected_geo["flood_zone_class"].to_numpy(),
    "flood_risk_score": selected_geo["flood_risk_score"].astype(float).round(2).to_numpy(),
    "heat_stress_score": selected_geo["heat_stress_score"].astype(float).round(2).to_numpy(),
    "sea_level_rise_m_2050": selected_geo["sea_level_rise_m_2050"].astype(float).round(3).to_numpy(),
    "sea_level_rise_flag": sea_level_rise_flag.to_numpy(),
    "acute_risk_composite": selected_geo["acute_risk_composite"].astype(float).round(2).to_numpy(),
    "chronic_risk_composite": selected_geo["chronic_risk_composite"].astype(float).round(2).to_numpy(),

    "valuation_method": rng.choice(
        ["internal_model", "external_appraisal", "indexed_valuation"],
        p=[0.45, 0.35, 0.20],
        size=n,
    ),

    "reporting_date": collateral["reporting_date"].to_numpy(),
    "data_source": "synthetic_collateral_register",
    "created_from": "synthetic_collateral_register_generation_v5_origination_value_floor_area",
})

# =========================
# SAVE
# =========================
out_path = DATA_DIR / "collateral_register_raw.csv"
collateral_register.to_csv(out_path, index=False)

# =========================
# VALIDATION
# =========================
valid_geo_ids = set(geo_risk_db["geo_id"].astype(str))
valid_postcodes = set(geo_risk_db["postcode"].astype(str))

building_rows = collateral_register["collateral_type"].isin([
    "residential_property",
    "commercial_property",
])

residential_rows = collateral_register["collateral_type"].eq("residential_property")
commercial_rows = collateral_register["collateral_type"].eq("commercial_property")
non_building_rows = ~building_rows

origination_ltv_recalc = (
    collateral_register["allocated_outstanding_balance_eur"]
    / collateral_register["collateral_value_at_origination_eur"]
)

current_ltv_recalc = (
    collateral_register["allocated_outstanding_balance_eur"]
    / collateral_register["collateral_value_eur"]
)

recalculated_building_emissions = (
    collateral_register["floor_area_m2"]
    * collateral_register["epc_energy_intensity_kwh_m2_year"]
    * collateral_register["grid_emission_factor_tco2e_mwh"]
    / 1000
)

building_emission_diff = (
    collateral_register["building_emissions_tco2e"]
    - recalculated_building_emissions
).abs()

validation = {
    "collateral_rows": len(collateral_register),
    "unique_collateral_id": int(collateral_register["collateral_id"].is_unique),

    "facility_id_missing_from_loan_book": int(
        (~collateral_register["facility_id"].isin(loan_book["facility_id"])).sum()
    ),
    "counterparty_id_missing_from_loan_book": int(
        (~collateral_register["counterparty_id"].isin(loan_book["counterparty_id"])).sum()
    ),
    "entity_id_missing_from_entity_master": int(
        (~collateral_register["entity_id"].isin(entity_master["entity_id"])).sum()
    ),
    "geo_id_missing_from_geo_risk_db": int(
        (~collateral_register["geo_id"].astype(str).isin(valid_geo_ids)).sum()
    ),
    "postcode_missing_from_geo_risk_db": int(
        (~collateral_register["postcode"].astype(str).isin(valid_postcodes)).sum()
    ),

    "missing_collateral_value_at_origination": int(
        collateral_register["collateral_value_at_origination_eur"].isna().sum()
    ),
    "bad_ltv_at_origination_recalculation": int(
        ((collateral_register["ltv_at_origination"] - origination_ltv_recalc).abs() > 0.0003).sum()
    ),
    "bad_current_ltv_recalculation": int(
        ((collateral_register["ltv_ratio"] - current_ltv_recalc).abs() > 0.0003).sum()
    ),
    "ltv_at_origination_outside_0_10_0_95": int(
        (
            (collateral_register["ltv_at_origination"] < 0.10)
            | (collateral_register["ltv_at_origination"] > 0.95)
        ).sum()
    ),

    "valuation_date_after_reporting_date": int(
        (
            pd.to_datetime(collateral_register["valuation_date"])
            > pd.to_datetime(collateral_register["reporting_date"])
        ).sum()
    ),

    "residential_floor_area_outside_30_500": int(
        (
            residential_rows
            & (
                (collateral_register["floor_area_m2"] < 30)
                | (collateral_register["floor_area_m2"] > 500)
            )
        ).sum()
    ),
    "commercial_floor_area_outside_100_50000": int(
        (
            commercial_rows
            & (
                (collateral_register["floor_area_m2"] < 100)
                | (collateral_register["floor_area_m2"] > 50_000)
            )
        ).sum()
    ),
    "non_building_with_floor_area": int(
        (non_building_rows & collateral_register["floor_area_m2"].notna()).sum()
    ),

    "building_missing_epc_rating": int(
        (building_rows & collateral_register["epc_rating"].isna()).sum()
    ),
    "building_missing_energy_intensity": int(
        (building_rows & collateral_register["epc_energy_intensity_kwh_m2_year"].isna()).sum()
    ),
    "building_missing_grid_factor": int(
        (building_rows & collateral_register["grid_emission_factor_tco2e_mwh"].isna()).sum()
    ),
    "building_missing_building_emissions": int(
        (building_rows & collateral_register["building_emissions_tco2e"].isna()).sum()
    ),
    "building_emissions_bad_recalculation": int(
        (building_rows & (building_emission_diff > 0.01)).sum()
    ),
    "non_building_with_building_emissions": int(
        (non_building_rows & collateral_register["building_emissions_tco2e"].notna()).sum()
    ),

    "flood_risk_outside_0_10": int(
        ((collateral_register["flood_risk_score"] < 0) | (collateral_register["flood_risk_score"] > 10)).sum()
    ),
    "heat_stress_outside_0_10": int(
        ((collateral_register["heat_stress_score"] < 0) | (collateral_register["heat_stress_score"] > 10)).sum()
    ),
    "acute_risk_outside_0_10": int(
        ((collateral_register["acute_risk_composite"] < 0) | (collateral_register["acute_risk_composite"] > 10)).sum()
    ),
    "chronic_risk_outside_0_10": int(
        ((collateral_register["chronic_risk_composite"] < 0) | (collateral_register["chronic_risk_composite"] > 10)).sum()
    ),
    "sea_level_flag_not_derived": int(
        (
            collateral_register["sea_level_rise_flag"]
            != (collateral_register["sea_level_rise_m_2050"] >= 0.10)
        ).sum()
    ),
}

print(f"Generated: {out_path}")
print("\nValidation:")
for key, value in validation.items():
    print(f"{key}: {value}")

print("\nPreview:")
print(collateral_register.head(10))

Generated: Data\collateral_register_raw.csv

Validation:
collateral_rows: 15981
unique_collateral_id: 1
facility_id_missing_from_loan_book: 0
counterparty_id_missing_from_loan_book: 0
entity_id_missing_from_entity_master: 0
geo_id_missing_from_geo_risk_db: 0
postcode_missing_from_geo_risk_db: 0
missing_collateral_value_at_origination: 0
bad_ltv_at_origination_recalculation: 0
bad_current_ltv_recalculation: 0
ltv_at_origination_outside_0_10_0_95: 0
valuation_date_after_reporting_date: 0
residential_floor_area_outside_30_500: 0
commercial_floor_area_outside_100_50000: 0
non_building_with_floor_area: 0
building_missing_epc_rating: 0
building_missing_energy_intensity: 0
building_missing_grid_factor: 0
building_missing_building_emissions: 0
building_emissions_bad_recalculation: 4
non_building_with_building_emissions: 0
flood_risk_outside_0_10: 0
heat_stress_outside_0_10: 0
acute_risk_outside_0_10: 0
chronic_risk_outside_0_10: 0
sea_level_flag_not_derived: 0

Preview:
  collateral_id  facility_id counterparty_id   entity_id  \
0  COL-00000001  FAC-0000003      CP-0000003  ENT-FR-002
1  COL-00000002  FAC-0000003      CP-0000003  ENT-FR-002
2  COL-00000003  FAC-0000004      CP-0000004  ENT-LU-009
3  COL-00000004  FAC-0000004      CP-0000004  ENT-LU-009
4  COL-00000005  FAC-0000014      CP-0000014  ENT-LU-009
5  COL-00000006  FAC-0000014      CP-0000014  ENT-LU-009
6  COL-00000007  FAC-0000018      CP-0000018  ENT-NL-004
7  COL-00000008  FAC-0000018      CP-0000018  ENT-NL-004
8  COL-00000009  FAC-0000019      CP-0000019  ENT-US-010
9  COL-00000010  FAC-0000019      CP-0000019  ENT-US-010

        collateral_type  allocated_outstanding_balance_eur  \
0  residential_property                           45936.62
1  residential_property                           45936.62
2   commercial_property                         3479415.94
3                  land                         3479415.94
4  residential_property                           40377.02
5  residential_property                           40377.02
6   commercial_property                         1218837.90
7   commercial_property                         1218837.90
8  residential_property                           21033.24
9  residential_property                           21033.24

   ltv_at_origination  collateral_value_at_origination_eur  \
0              0.7646                             60078.40
1              0.6020                             76309.76
2              0.6564                           5300897.38
3              0.6926                           5023589.31
4              0.7043                             57329.93
5              0.5616                             71901.93
6              0.5131                           2375244.78
7              0.5929                           2055729.09
8              0.6488                             32417.01
9              0.6732                             31245.88

   annual_return_assumption  years_held  ...  flood_risk_score  \
0                 -0.131443      2.4449  ...              4.39
1                  0.038551      2.4449  ...              1.18
2                  0.025465      5.6181  ...              5.39
3                  0.035035      5.6181  ...              7.05
4                  0.048670      4.6872  ...              1.10
5                  0.068393      4.6872  ...              1.98
6                  0.074707      7.0281  ...              0.96
7                  0.014912      7.0281  ...              0.33
8                  0.105214      2.0260  ...              0.51
9                  0.023613      2.0260  ...              0.62

   heat_stress_score sea_level_rise_m_2050  sea_level_rise_flag  \
0               0.24                 0.026                False
1               3.09                 0.046                False
2              10.00                 0.140                 True
3              10.00                 0.277                 True
4               7.42                 0.035                False
5              10.00                 0.050                False
6               1.75                 0.039                False
7               1.86                 0.048                False
8               0.00                 0.044                False
9               1.26                 0.039                False

  acute_risk_composite  chronic_risk_composite    valuation_method  \
0                 2.45                    0.25      internal_model
1                 0.74                    1.89  external_appraisal
2                 5.03                    6.36  external_appraisal
3                 5.42                    6.81   indexed_valuation
4                 2.13                    4.72   indexed_valuation
5                 3.33                    6.10  external_appraisal
6                 0.54                    1.10      internal_model
7                 0.26                    1.22  external_appraisal
8                 0.42                    0.19   indexed_valuation
9                 0.50                    0.86      internal_model

   reporting_date                    data_source  \
0      2024-12-31  synthetic_collateral_register
1      2024-12-31  synthetic_collateral_register
2      2024-12-31  synthetic_collateral_register
3      2024-12-31  synthetic_collateral_register
4      2024-12-31  synthetic_collateral_register
5      2024-12-31  synthetic_collateral_register
6      2024-12-31  synthetic_collateral_register
7      2024-12-31  synthetic_collateral_register
8      2024-12-31  synthetic_collateral_register
9      2024-12-31  synthetic_collateral_register

                                        created_from
0  synthetic_collateral_register_generation_v5_or...
1  synthetic_collateral_register_generation_v5_or...
2  synthetic_collateral_register_generation_v5_or...
3  synthetic_collateral_register_generation_v5_or...
4  synthetic_collateral_register_generation_v5_or...
5  synthetic_collateral_register_generation_v5_or...
6  synthetic_collateral_register_generation_v5_or...
7  synthetic_collateral_register_generation_v5_or...
8  synthetic_collateral_register_generation_v5_or...
9  synthetic_collateral_register_generation_v5_or...

[10 rows x 34 columns]

In [12]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path("Data")

counterparty_master = pd.read_csv(DATA_DIR / "counterparty_master_raw.csv")
loan_book = pd.read_csv(DATA_DIR / "loan_book_raw.csv")

missing_counterparties = loan_book[
    ~loan_book["counterparty_id"].isin(counterparty_master["counterparty_id"])
]

print("Loan rows with missing counterparty_id:", len(missing_counterparties))
print("Unique missing counterparty_ids:", missing_counterparties["counterparty_id"].nunique())

print("Counterparty rows:", len(counterparty_master))
print("Loan book rows:", len(loan_book))
print("Unique counterparties used in loan book:", loan_book["counterparty_id"].nunique())

Loan rows with missing counterparty_id: 0
Unique missing counterparty_ids: 0
Counterparty rows: 20000
Loan book rows: 50000
Unique counterparties used in loan book: 17503

Utility Bills : The bank's own energy and fuel consumption

In [6]:
import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# CONFIG
# =========================================================
rng = np.random.default_rng(42)

DATA_DIR = Path("Data")
SITE_OUTPUT_PATH = DATA_DIR / "site_inventory_raw.csv"
UTILITY_OUTPUT_PATH = DATA_DIR / "utility_bills_raw.csv"

N_SITES = 120

# =========================================================
# LOAD DEPENDENCIES
# =========================================================
entity_master = pd.read_csv(DATA_DIR / "entity_master_raw.csv")
emission_factors = pd.read_csv(DATA_DIR / "emission_factors_raw.csv")

# Clean column names
entity_master.columns = (
    entity_master.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

emission_factors.columns = (
    emission_factors.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

# =========================================================
# REQUIRED COLUMN CHECKS
# =========================================================
required_entity_cols = [
    "entity_id",
    "legal_name",
    "country_code",
    "in_scope_esg_flag",
]

missing_entity_cols = [
    col for col in required_entity_cols
    if col not in entity_master.columns
]

if missing_entity_cols:
    raise ValueError(f"entity_master is missing required columns: {missing_entity_cols}")

# Normalize boolean
entity_master["in_scope_esg_flag"] = (
    entity_master["in_scope_esg_flag"]
    .astype(str)
    .str.lower()
    .eq("true")
)

# Keep only in-scope entities
entities = (
    entity_master.loc[
        entity_master["in_scope_esg_flag"].eq(True),
        ["entity_id", "legal_name", "country_code"]
    ]
    .dropna(subset=["entity_id", "country_code"])
    .drop_duplicates()
    .reset_index(drop=True)
)

if entities.empty:
    raise ValueError("No in-scope ESG entities found in entity_master_raw.csv")

entities["country_code"] = entities["country_code"].astype(str).str.upper()

# =========================================================
# EMISSION FACTOR HELPER KEYS
# This table remains raw utility data.
# Final emissions should be calculated later in the reporting-ready layer.
# =========================================================
def infer_emission_factor_key(meter_type: str) -> str:
    if meter_type == "electricity":
        return "scope2_location_electricity_grid"
    if meter_type == "natural_gas":
        return "scope1_natural_gas_combustion"
    if meter_type == "diesel_fleet":
        return "scope1_diesel_combustion"
    return "unknown"


# =========================================================
# SITE INVENTORY GENERATION
# One site belongs to one reporting entity.
# Utility bills are generated per site / meter / quarter.
# =========================================================
site_types = ["hq", "branch", "data_centre", "office"]
site_type_probs = [0.08, 0.62, 0.10, 0.20]

site_entities = entities.iloc[
    rng.integers(0, len(entities), size=N_SITES)
].reset_index(drop=True)

site_type = rng.choice(
    site_types,
    p=site_type_probs,
    size=N_SITES
)

floor_area_m2 = np.where(
    site_type == "hq",
    rng.integers(8_000, 35_000, size=N_SITES),
    np.where(
        site_type == "data_centre",
        rng.integers(2_000, 12_000, size=N_SITES),
        np.where(
            site_type == "office",
            rng.integers(1_000, 8_000, size=N_SITES),
            rng.integers(120, 1_500, size=N_SITES)
        )
    )
)

fleet_size = np.where(
    site_type == "hq",
    rng.integers(10, 80, size=N_SITES),
    np.where(
        site_type == "branch",
        rng.integers(0, 8, size=N_SITES),
        rng.integers(0, 20, size=N_SITES)
    )
)

site_inventory = pd.DataFrame({
    "site_id": [f"SITE-{i:05d}" for i in range(1, N_SITES + 1)],
    "entity_id": site_entities["entity_id"].to_numpy(),
    "site_name": [
        f"{st.upper()}-{country}-{i:03d}"
        for i, (st, country)
        in enumerate(zip(site_type, site_entities["country_code"]), start=1)
    ],
    "site_type": site_type,
    "country_code": site_entities["country_code"].to_numpy(),
    "grid_region": site_entities["country_code"].to_numpy(),
    "floor_area_m2": floor_area_m2,
    "fleet_size": fleet_size,
    "data_source": "synthetic_site_inventory",
})

# =========================================================
# UTILITY BILL GENERATION
# =========================================================
quarters = pd.date_range("2019-01-01", "2024-10-01", freq="QS")

rows = []
bill_id = 1

# Synthetic energy prices
electricity_price = {
    2019: 0.145,
    2020: 0.150,
    2021: 0.165,
    2022: 0.260,
    2023: 0.235,
    2024: 0.220,
}

gas_price = {
    2019: 0.055,
    2020: 0.052,
    2021: 0.065,
    2022: 0.145,
    2023: 0.120,
    2024: 0.105,
}

diesel_price = {
    2019: 1.25,
    2020: 1.10,
    2021: 1.30,
    2022: 1.75,
    2023: 1.65,
    2024: 1.58,
}

for _, site in site_inventory.iterrows():

    # Annual electricity intensity kWh/m²/year
    if site["site_type"] == "data_centre":
        elec_intensity = rng.normal(900, 120)
    elif site["site_type"] == "hq":
        elec_intensity = rng.normal(185, 25)
    elif site["site_type"] == "office":
        elec_intensity = rng.normal(150, 22)
    else:
        elec_intensity = rng.normal(135, 20)

    elec_intensity = max(elec_intensity, 40)
    annual_elec_kwh = elec_intensity * site["floor_area_m2"]

    # Gas used mainly for heating
    gas_site_flag = rng.random() < (
        0.70 if site["site_type"] != "data_centre" else 0.35
    )

    annual_gas_kwh = (
        rng.normal(75, 20) * site["floor_area_m2"]
        if gas_site_flag
        else 0
    )

    annual_gas_kwh = max(annual_gas_kwh, 0)

    for q in quarters:
        year = q.year
        month = q.month

        # Seasonal multipliers
        elec_season = 1.30 if month in [1, 10] else (1.10 if month == 7 else 1.00)
        gas_season = 2.50 if month == 1 else (0.20 if month == 7 else 1.00)

        elec_kwh = max(
            (annual_elec_kwh / 4)
            * elec_season
            * rng.normal(1.0, 0.06),
            1
        )

        gas_kwh = max(
            (annual_gas_kwh / 4)
            * gas_season
            * rng.normal(1.0, 0.10),
            0
        )

        # -------------------------
        # Electricity bill
        # -------------------------
        meter_type = "electricity"

        rows.append({
            "bill_id": f"BILL-{bill_id:08d}",
            "site_id": site["site_id"],
            "entity_id": site["entity_id"],
            "site_name": site["site_name"],
            "site_type": site["site_type"],
            "country_code": site["country_code"],
            "grid_region": site["grid_region"],

            "meter_type": meter_type,
            "scope_category": "scope2_location",

            "billing_period_start": q.strftime("%Y-%m-%d"),
            "billing_period_end": (q + pd.offsets.QuarterEnd()).strftime("%Y-%m-%d"),

            "quantity": round(elec_kwh, 2),
            "unit": "kWh",
            "unit_price_eur": electricity_price[year],
            "cost_eur": round(elec_kwh * electricity_price[year], 2),

            "floor_area_m2": site["floor_area_m2"],
            "fleet_size": site["fleet_size"],

            "emission_factor_key": infer_emission_factor_key(meter_type),
            "emission_factor_country_code": site["country_code"],

            "invoice_status": rng.choice(
                ["submitted", "estimated", "corrected"],
                p=[0.88, 0.09, 0.03]
            ),

            "data_source": "synthetic_utility_invoice",
            "reporting_year": year,
        })

        bill_id += 1

        # -------------------------
        # Natural gas bill
        # -------------------------
        if gas_kwh > 25:
            meter_type = "natural_gas"

            rows.append({
                "bill_id": f"BILL-{bill_id:08d}",
                "site_id": site["site_id"],
                "entity_id": site["entity_id"],
                "site_name": site["site_name"],
                "site_type": site["site_type"],
                "country_code": site["country_code"],
                "grid_region": site["grid_region"],

                "meter_type": meter_type,
                "scope_category": "scope1",

                "billing_period_start": q.strftime("%Y-%m-%d"),
                "billing_period_end": (q + pd.offsets.QuarterEnd()).strftime("%Y-%m-%d"),

                "quantity": round(gas_kwh, 2),
                "unit": "kWh",
                "unit_price_eur": gas_price[year],
                "cost_eur": round(gas_kwh * gas_price[year], 2),

                "floor_area_m2": site["floor_area_m2"],
                "fleet_size": site["fleet_size"],

                "emission_factor_key": infer_emission_factor_key(meter_type),
                "emission_factor_country_code": site["country_code"],

                "invoice_status": rng.choice(
                    ["submitted", "estimated", "corrected"],
                    p=[0.86, 0.11, 0.03]
                ),

                "data_source": "synthetic_utility_invoice",
                "reporting_year": year,
            })

            bill_id += 1

        # -------------------------
        # Diesel fleet bill
        # -------------------------
        if site["fleet_size"] > 0:
            meter_type = "diesel_fleet"

            km_per_vehicle_q = rng.poisson(2_800)

            litres = max(
                site["fleet_size"]
                * km_per_vehicle_q
                * rng.normal(0.065, 0.008),
                1
            )

            rows.append({
                "bill_id": f"BILL-{bill_id:08d}",
                "site_id": site["site_id"],
                "entity_id": site["entity_id"],
                "site_name": site["site_name"],
                "site_type": site["site_type"],
                "country_code": site["country_code"],
                "grid_region": site["grid_region"],

                "meter_type": meter_type,
                "scope_category": "scope1",

                "billing_period_start": q.strftime("%Y-%m-%d"),
                "billing_period_end": (q + pd.offsets.QuarterEnd()).strftime("%Y-%m-%d"),

                "quantity": round(litres, 2),
                "unit": "litres",
                "unit_price_eur": diesel_price[year],
                "cost_eur": round(litres * diesel_price[year], 2),

                "floor_area_m2": site["floor_area_m2"],
                "fleet_size": site["fleet_size"],

                "emission_factor_key": infer_emission_factor_key(meter_type),
                "emission_factor_country_code": site["country_code"],

                "invoice_status": rng.choice(
                    ["submitted", "estimated", "corrected"],
                    p=[0.90, 0.07, 0.03]
                ),

                "data_source": "synthetic_utility_invoice",
                "reporting_year": year,
            })

            bill_id += 1

utility_bills = pd.DataFrame(rows)

# =========================================================
# VALIDATION
# =========================================================
utility_bills["billing_period_start_dt"] = pd.to_datetime(
    utility_bills["billing_period_start"]
)

utility_bills["billing_period_end_dt"] = pd.to_datetime(
    utility_bills["billing_period_end"]
)

# Electricity plausibility check
elec = utility_bills[
    utility_bills["meter_type"].eq("electricity")
].copy()

annual_elec = (
    elec.groupby(
        ["site_id", "reporting_year", "site_type", "floor_area_m2"],
        as_index=False
    )["quantity"]
    .sum()
)

annual_elec["kwh_m2_year"] = (
    annual_elec["quantity"]
    / annual_elec["floor_area_m2"]
)

office_like = annual_elec[
    annual_elec["site_type"].isin(["hq", "branch", "office"])
]

valid_site_ids = set(site_inventory["site_id"].astype(str))
valid_entity_ids = set(entity_master["entity_id"].astype(str))

validation = {
    "utility_bill_rows": len(utility_bills),
    "site_inventory_rows": len(site_inventory),
    "unique_bill_id": int(utility_bills["bill_id"].is_unique),

    "quantity_non_positive": int(
        (utility_bills["quantity"] <= 0).sum()
    ),

    "bad_billing_period_order": int(
        (
            utility_bills["billing_period_start_dt"]
            >= utility_bills["billing_period_end_dt"]
        ).sum()
    ),

    "site_id_missing_from_site_inventory": int(
        (~utility_bills["site_id"].astype(str).isin(valid_site_ids)).sum()
    ),

    "entity_id_missing_from_entity_master": int(
        (~utility_bills["entity_id"].astype(str).isin(valid_entity_ids)).sum()
    ),

    "electricity_in_scope1_records": int(
        (
            utility_bills["meter_type"].eq("electricity")
            & utility_bills["scope_category"].eq("scope1")
        ).sum()
    ),

    "scope_mismatch_fuel_records": int(
        (
            utility_bills["meter_type"].isin(["natural_gas", "diesel_fleet"])
            & ~utility_bills["scope_category"].eq("scope1")
        ).sum()
    ),

    "office_like_electricity_kwh_m2_outside_80_260": int(
        (
            (office_like["kwh_m2_year"] < 80)
            | (office_like["kwh_m2_year"] > 260)
        ).sum()
    ),

    "missing_emission_factor_key": int(
        utility_bills["emission_factor_key"].isna().sum()
    ),
}

# Drop temporary datetime columns before saving
utility_bills = utility_bills.drop(
    columns=["billing_period_start_dt", "billing_period_end_dt"]
)

# =========================================================
# SAVE OUTPUTS
# =========================================================
site_inventory.to_csv(SITE_OUTPUT_PATH, index=False)
utility_bills.to_csv(UTILITY_OUTPUT_PATH, index=False)

print(f"Generated site dependency: {SITE_OUTPUT_PATH}")
print(f"Generated utility bills table: {UTILITY_OUTPUT_PATH}")

print("\nValidation:")
for key, value in validation.items():
    print(f"{key}: {value}")

print("\nPreview:")
print(utility_bills.head(10))

Generated site dependency: Data\site_inventory_raw.csv
Generated utility bills table: Data\utility_bills_raw.csv

Validation:
utility_bill_rows: 7344
site_inventory_rows: 120
unique_bill_id: 1
quantity_non_positive: 0
bad_billing_period_order: 0
site_id_missing_from_site_inventory: 0
entity_id_missing_from_entity_master: 0
electricity_in_scope1_records: 0
scope_mismatch_fuel_records: 0
office_like_electricity_kwh_m2_outside_80_260: 1
missing_emission_factor_key: 0

Preview:
         bill_id     site_id      entity_id      site_name site_type  \
0  BILL-00000001  SITE-00001  ENT-GROUP-001  BRANCH-FR-001    branch
1  BILL-00000002  SITE-00001  ENT-GROUP-001  BRANCH-FR-001    branch
2  BILL-00000003  SITE-00001  ENT-GROUP-001  BRANCH-FR-001    branch
3  BILL-00000004  SITE-00001  ENT-GROUP-001  BRANCH-FR-001    branch
4  BILL-00000005  SITE-00001  ENT-GROUP-001  BRANCH-FR-001    branch
5  BILL-00000006  SITE-00001  ENT-GROUP-001  BRANCH-FR-001    branch
6  BILL-00000007  SITE-00001  ENT-GROUP-001  BRANCH-FR-001    branch
7  BILL-00000008  SITE-00001  ENT-GROUP-001  BRANCH-FR-001    branch
8  BILL-00000009  SITE-00001  ENT-GROUP-001  BRANCH-FR-001    branch
9  BILL-00000010  SITE-00001  ENT-GROUP-001  BRANCH-FR-001    branch

  country_code grid_region    meter_type   scope_category  \
0           FR          FR   electricity  scope2_location
1           FR          FR  diesel_fleet           scope1
2           FR          FR   electricity  scope2_location
3           FR          FR  diesel_fleet           scope1
4           FR          FR   electricity  scope2_location
5           FR          FR  diesel_fleet           scope1
6           FR          FR   electricity  scope2_location
7           FR          FR  diesel_fleet           scope1
8           FR          FR   electricity  scope2_location
9           FR          FR  diesel_fleet           scope1

  billing_period_start  ...    unit  unit_price_eur cost_eur  floor_area_m2  \
0           2019-01-01  ...     kWh           0.145  2403.17            312
1           2019-01-01  ...  litres           1.250   251.57            312
2           2019-04-01  ...     kWh           0.145  1681.42            312
3           2019-04-01  ...  litres           1.250   179.11            312
4           2019-07-01  ...     kWh           0.145  1939.47            312
5           2019-07-01  ...  litres           1.250   241.50            312
6           2019-10-01  ...     kWh           0.145  2531.72            312
7           2019-10-01  ...  litres           1.250   248.11            312
8           2020-01-01  ...     kWh           0.150  2511.52            312
9           2020-01-01  ...  litres           1.100   182.52            312

   fleet_size               emission_factor_key  emission_factor_country_code  \
0           1  scope2_location_electricity_grid                            FR
1           1          scope1_diesel_combustion                            FR
2           1  scope2_location_electricity_grid                            FR
3           1          scope1_diesel_combustion                            FR
4           1  scope2_location_electricity_grid                            FR
5           1          scope1_diesel_combustion                            FR
6           1  scope2_location_electricity_grid                            FR
7           1          scope1_diesel_combustion                            FR
8           1  scope2_location_electricity_grid                            FR
9           1          scope1_diesel_combustion                            FR

  invoice_status                data_source reporting_year
0      estimated  synthetic_utility_invoice           2019
1      submitted  synthetic_utility_invoice           2019
2      submitted  synthetic_utility_invoice           2019
3      submitted  synthetic_utility_invoice           2019
4      corrected  synthetic_utility_invoice           2019
5      submitted  synthetic_utility_invoice           2019
6      submitted  synthetic_utility_invoice           2019
7      submitted  synthetic_utility_invoice           2019
8      submitted  synthetic_utility_invoice           2020
9      submitted  synthetic_utility_invoice           2020

[10 rows x 22 columns]

ESG KPI Tracker

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

rng = np.random.default_rng(42)

DATA_DIR = Path("Data")

# =========================================================
# LOAD TABLES
# =========================================================
entity_master = pd.read_csv(DATA_DIR / "entity_master_raw.csv")
utility_bills = pd.read_csv(DATA_DIR / "utility_bills_raw.csv")
emission_factors = pd.read_csv(DATA_DIR / "emission_factors_raw.csv")
loan_book = pd.read_csv(DATA_DIR / "loan_book_raw.csv")
counterparty_master = pd.read_csv(DATA_DIR / "counterparty_master_raw.csv")

collateral_path = DATA_DIR / "collateral_register_raw.csv"
collateral_register = pd.read_csv(collateral_path) if collateral_path.exists() else pd.DataFrame()

# Normalize columns
for df in [entity_master, utility_bills, emission_factors, loan_book, counterparty_master, collateral_register]:
    if len(df) > 0:
        df.columns = (
            df.columns
            .str.strip()
            .str.lower()
            .str.replace(" ", "_")
        )

# Normalize booleans
for df in [entity_master, loan_book, counterparty_master]:
    for col in df.columns:
        if col.endswith("_flag") or col in ["has_control", "listed_flag"]:
            df[col] = df[col].astype(str).str.lower().map({
                "true": True,
                "false": False,
                "1": True,
                "0": False
            }).fillna(df[col])

years = list(range(2019, 2025))

# =========================================================
# ENTITY LIST
# =========================================================
entity_master["in_scope_esg_flag"] = (
    entity_master["in_scope_esg_flag"]
    .astype(str)
    .str.lower()
    .eq("true")
)

entities = entity_master.loc[
    entity_master["in_scope_esg_flag"],
    ["entity_id", "legal_name", "country_code"]
].copy()

entity_ids = entities["entity_id"].tolist()

# =========================================================
# EMISSION FACTOR HELPERS
# =========================================================
def get_factor(country_code, year, nace_code=None, factor_scope=None, fallback=np.nan):
    ef = emission_factors.copy()

    mask = pd.Series(True, index=ef.index)

    if "country_code" in ef.columns:
        mask &= ef["country_code"].astype(str).isin([str(country_code), "GLOBAL"])

    if "year" in ef.columns:
        mask &= ef["year"].astype(int).eq(int(year))

    if nace_code is not None and "nace_code" in ef.columns:
        mask &= ef["nace_code"].astype(str).eq(str(nace_code))

    if factor_scope is not None and "factor_scope" in ef.columns:
        mask &= ef["factor_scope"].astype(str).eq(str(factor_scope))

    matched = ef.loc[mask]

    if len(matched) > 0:
        return float(matched["emission_factor"].iloc[0])

    return fallback


def get_grid_factor(country_code, year):
    return get_factor(
        country_code=country_code,
        year=year,
        nace_code="GRID_ELECTRICITY",
        factor_scope="scope2",
        fallback=0.25
    )


def get_fuel_factor(country_code, year, fuel_code):
    return get_factor(
        country_code=country_code,
        year=year,
        nace_code=fuel_code,
        factor_scope="scope1",
        fallback=0.20
    )


# =========================================================
# 1) OPERATIONAL EMISSIONS BY ENTITY/YEAR
# =========================================================
utility = utility_bills.copy()
utility["billing_period_start"] = pd.to_datetime(utility["billing_period_start"])
utility["year"] = utility["billing_period_start"].dt.year

# Keep only useful years
utility = utility[utility["year"].isin(years)].copy()

# Scope 2 electricity
electricity = utility[utility["meter_type"].eq("electricity")].copy()

electricity["grid_tco2e_per_mwh"] = electricity.apply(
    lambda r: get_grid_factor(r["country_code"], r["year"]),
    axis=1
)

electricity["scope2_tco2e"] = (
    electricity["quantity"] / 1000
) * electricity["grid_tco2e_per_mwh"]

# Scope 1 natural gas
gas = utility[utility["meter_type"].eq("natural_gas")].copy()
gas["fuel_tco2e_per_mwh"] = gas.apply(
    lambda r: get_fuel_factor(r["country_code"], r["year"], "FUEL_NATGAS"),
    axis=1
)

gas["scope1_tco2e"] = (
    gas["quantity"] / 1000
) * gas["fuel_tco2e_per_mwh"]

# Scope 1 diesel
diesel = utility[utility["meter_type"].eq("diesel_fleet")].copy()
diesel["fuel_tco2e_per_mwh"] = diesel.apply(
    lambda r: get_fuel_factor(r["country_code"], r["year"], "FUEL_DIESEL"),
    axis=1
)

# litres → MWh approximation: 10 kWh/litre
diesel["scope1_tco2e"] = (
    diesel["quantity"] * 10 / 1000
) * diesel["fuel_tco2e_per_mwh"]

scope1_by_entity_year = (
    pd.concat([
        gas[["entity_id", "year", "scope1_tco2e"]],
        diesel[["entity_id", "year", "scope1_tco2e"]]
    ], ignore_index=True)
    .groupby(["entity_id", "year"])["scope1_tco2e"]
    .sum()
)

scope2_by_entity_year = (
    electricity
    .groupby(["entity_id", "year"])["scope2_tco2e"]
    .sum()
)

energy_by_entity_year = (
    utility[utility["meter_type"].isin(["electricity", "natural_gas"])]
    .groupby(["entity_id", "year"])["quantity"]
    .sum()
)

energy_cost_by_entity_year = (
    utility
    .groupby(["entity_id", "year"])["cost_eur"]
    .sum()
)

# =========================================================
# 2) FINANCED EMISSIONS BY ENTITY
# =========================================================
loan = loan_book.copy()

# Merge counterparty data
cp_cols = [
    "counterparty_id",
    "segment",
    "listed_flag",
    "book_equity_eur",
    "total_debt_eur",
    "evic_eur",
    "total_assets_eur",
    "annual_revenue_eur",
    "borrower_scope1_tco2e",
    "borrower_scope2_tco2e",
    "borrower_scope3_tco2e",
    "national_scope1_tco2e",
    "national_scope2_tco2e",
    "national_scope3_tco2e",
    "ppp_adjusted_gdp_eur",
    "pcaf_quality_score",
    "data_source_type",
    "transition_risk_score",
    "sbti_target_flag"
]

cp_cols = [c for c in cp_cols if c in counterparty_master.columns]

loan_cp = loan.merge(
    counterparty_master[cp_cols],
    on="counterparty_id",
    how="left"
)

# Add collateral-financed emissions for mortgage/commercial RE
if len(collateral_register) > 0 and "building_emissions_tco2e" in collateral_register.columns:
    collateral = collateral_register.copy()

    collateral["building_attribution_factor"] = (
        collateral["allocated_outstanding_balance_eur"] /
        collateral["collateral_value_at_origination_eur"].replace(0, np.nan)
    ).clip(lower=0, upper=1)

    collateral["financed_building_emissions_tco2e"] = (
        collateral["building_attribution_factor"] *
        collateral["building_emissions_tco2e"]
    )

    building_financed_by_facility = (
        collateral
        .groupby("facility_id")["financed_building_emissions_tco2e"]
        .sum()
        .reset_index()
    )

    loan_cp = loan_cp.merge(
        building_financed_by_facility,
        on="facility_id",
        how="left"
    )

else:
    loan_cp["financed_building_emissions_tco2e"] = 0.0

loan_cp["financed_building_emissions_tco2e"] = (
    loan_cp["financed_building_emissions_tco2e"].fillna(0)
)

# Borrower/company emissions
for col in [
    "borrower_scope1_tco2e",
    "borrower_scope2_tco2e",
    "borrower_scope3_tco2e",
    "national_scope1_tco2e",
    "national_scope2_tco2e",
    "national_scope3_tco2e"
]:
    if col not in loan_cp.columns:
        loan_cp[col] = 0.0

loan_cp["borrower_scope12_tco2e"] = (
    loan_cp["borrower_scope1_tco2e"].fillna(0) +
    loan_cp["borrower_scope2_tco2e"].fillna(0)
)

loan_cp["national_emissions_tco2e"] = (
    loan_cp["national_scope1_tco2e"].fillna(0) +
    loan_cp["national_scope2_tco2e"].fillna(0) +
    loan_cp["national_scope3_tco2e"].fillna(0)
)

# Denominator helpers
if "evic_eur" not in loan_cp.columns:
    loan_cp["evic_eur"] = np.nan

if "book_equity_eur" not in loan_cp.columns:
    loan_cp["book_equity_eur"] = np.nan

if "total_debt_eur" not in loan_cp.columns:
    loan_cp["total_debt_eur"] = np.nan

loan_cp["equity_plus_debt_eur"] = (
    loan_cp["book_equity_eur"].fillna(0) +
    loan_cp["total_debt_eur"].fillna(0)
)

loan_cp["company_denominator_eur"] = loan_cp["evic_eur"].fillna(
    loan_cp["equity_plus_debt_eur"]
)

# Default financed emissions = 0
loan_cp["financed_emissions_tco2e"] = 0.0

# Business loans
mask_business = loan_cp["pcaf_asset_class"].eq("business_loan")
loan_cp.loc[mask_business, "financed_emissions_tco2e"] = (
    loan_cp.loc[mask_business, "outstanding_balance_eur"] /
    loan_cp.loc[mask_business, "company_denominator_eur"].replace(0, np.nan)
).clip(0, 1).fillna(0) * loan_cp.loc[mask_business, "borrower_scope12_tco2e"]

# Mortgage + commercial real estate
mask_real_estate = loan_cp["pcaf_asset_class"].isin(["mortgage", "commercial_re"])
loan_cp.loc[mask_real_estate, "financed_emissions_tco2e"] = (
    loan_cp.loc[mask_real_estate, "financed_building_emissions_tco2e"]
)

# Motor vehicle
if {
    "vehicle_value_at_origination_eur",
    "vehicle_annual_emissions_tco2e"
}.issubset(loan_cp.columns):

    mask_vehicle = loan_cp["pcaf_asset_class"].eq("motor_vehicle")

    loan_cp.loc[mask_vehicle, "financed_emissions_tco2e"] = (
        loan_cp.loc[mask_vehicle, "outstanding_balance_eur"] /
        loan_cp.loc[mask_vehicle, "vehicle_value_at_origination_eur"].replace(0, np.nan)
    ).clip(0, 1).fillna(0) * loan_cp.loc[mask_vehicle, "vehicle_annual_emissions_tco2e"]

# Sovereign bond
if {
    "ppp_adjusted_gdp_eur",
    "national_emissions_tco2e"
}.issubset(loan_cp.columns):

    mask_sovereign = loan_cp["pcaf_asset_class"].eq("sovereign_bond")

    loan_cp.loc[mask_sovereign, "financed_emissions_tco2e"] = (
        loan_cp.loc[mask_sovereign, "outstanding_balance_eur"] /
        loan_cp.loc[mask_sovereign, "ppp_adjusted_gdp_eur"].replace(0, np.nan)
    ).clip(0, 1).fillna(0) * loan_cp.loc[mask_sovereign, "national_emissions_tco2e"]

# Project finance
if {
    "total_project_cost_eur",
    "project_annual_emissions_tco2e",
    "has_control"
}.issubset(loan_cp.columns):

    mask_project = loan_cp["pcaf_asset_class"].eq("project_finance")

    project_attr = (
        loan_cp.loc[mask_project, "outstanding_balance_eur"] /
        loan_cp.loc[mask_project, "total_project_cost_eur"].replace(0, np.nan)
    ).clip(0, 1).fillna(0)

    project_attr = np.where(
        loan_cp.loc[mask_project, "has_control"].astype(bool),
        1.0,
        project_attr
    )

    loan_cp.loc[mask_project, "financed_emissions_tco2e"] = (
        project_attr *
        loan_cp.loc[mask_project, "project_annual_emissions_tco2e"].fillna(0)
    )

# Entity-level 2024 portfolio KPIs
financed_2024_by_entity = (
    loan_cp
    .groupby("entity_id")["financed_emissions_tco2e"]
    .sum()
)

portfolio_2024_by_entity = (
    loan_cp
    .groupby("entity_id")["outstanding_balance_eur"]
    .sum()
)

high_emission_nace = [
    "B05.10", "B06.10", "C23.51", "C24.10",
    "D35.11", "H51.10", "H49.41", "C20.16"
]

loan_cp["high_emission_sector_flag"] = (
    loan_cp["nace_code"].astype(str).isin(high_emission_nace)
)

high_emission_exposure_2024_by_entity = (
    loan_cp.loc[loan_cp["high_emission_sector_flag"]]
    .groupby("entity_id")["outstanding_balance_eur"]
    .sum()
)

high_emission_exposure_pct_2024_by_entity = (
    high_emission_exposure_2024_by_entity /
    portfolio_2024_by_entity *
    100
).fillna(0)

def weighted_average(group, value_col, weight_col):
    valid = group[value_col].notna() & group[weight_col].notna()
    if valid.sum() == 0:
        return np.nan
    return np.average(group.loc[valid, value_col], weights=group.loc[valid, weight_col])

avg_pcaf_quality_2024_by_entity = (
    loan_cp
    .groupby("entity_id")
    .apply(lambda g: weighted_average(g, "pcaf_quality_score", "outstanding_balance_eur"))
)

esg_data_coverage_pct_2024_by_entity = (
    loan_cp
    .groupby("entity_id")["data_source_type"]
    .apply(lambda s: s.notna().mean() * 100)
)

sbti_exposure_pct_2024_by_entity = (
    loan_cp.loc[loan_cp["sbti_target_flag"].astype(str).str.lower().eq("true")]
    .groupby("entity_id")["outstanding_balance_eur"]
    .sum()
    .div(portfolio_2024_by_entity)
    .mul(100)
    .fillna(0)
)

transition_high_risk_exposure_pct_2024_by_entity = (
    loan_cp.loc[loan_cp["transition_risk_score"] >= 7]
    .groupby("entity_id")["outstanding_balance_eur"]
    .sum()
    .div(portfolio_2024_by_entity)
    .mul(100)
    .fillna(0)
)

# =========================================================
# BACKCAST HELPERS
# =========================================================
def backcast_to_2024(value_2024, annual_change, noise=0.02):
    vals = {}
    for y in years:
        years_back = 2024 - y
        vals[y] = value_2024 * ((1 + annual_change) ** years_back) * rng.uniform(1 - noise, 1 + noise)
    vals[2024] = value_2024
    return pd.Series(vals)


def smooth_series(baseline, target, noise=0.03):
    vals = {}
    for y in years:
        progress = (y - 2019) / (2030 - 2019)
        expected = baseline + (target - baseline) * progress
        vals[y] = expected * rng.uniform(1 - noise, 1 + noise)
    return pd.Series(vals)


# =========================================================
# KPI CATALOGUE
# =========================================================
kpi_catalogue = [
    {
        "kpi_code": "ENV-001",
        "kpi_name": "Scope 1 emissions",
        "category": "Climate",
        "unit": "tCO2e",
        "source_logic": "Computed from utility_bills natural_gas and diesel_fleet using emission_factors",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_reduction_pct": 50
    },
    {
        "kpi_code": "ENV-002",
        "kpi_name": "Scope 2 location-based emissions",
        "category": "Climate",
        "unit": "tCO2e",
        "source_logic": "Computed from utility_bills electricity using country grid factors",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_reduction_pct": 50
    },
    {
        "kpi_code": "ENV-003",
        "kpi_name": "Total operational Scope 1 and 2 emissions",
        "category": "Climate",
        "unit": "tCO2e",
        "source_logic": "Derived as Scope 1 + Scope 2",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_reduction_pct": 50
    },
    {
        "kpi_code": "ENV-004",
        "kpi_name": "Energy consumption",
        "category": "Climate",
        "unit": "kWh",
        "source_logic": "Computed from utility_bills electricity and natural_gas quantities",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_reduction_pct": 20
    },
    {
        "kpi_code": "ENV-005",
        "kpi_name": "Energy cost",
        "category": "Climate",
        "unit": "EUR",
        "source_logic": "Computed from utility_bills cost_eur",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_reduction_pct": 10
    },
    {
        "kpi_code": "FIN-001",
        "kpi_name": "Financed emissions Scope 1 and 2",
        "category": "Financed emissions",
        "unit": "tCO2e",
        "source_logic": "Computed from loan_book, counterparty_master, collateral_register and PCAF attribution logic",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_reduction_pct": 45
    },
    {
        "kpi_code": "FIN-002",
        "kpi_name": "Outstanding loan exposure",
        "category": "Portfolio",
        "unit": "EUR",
        "source_logic": "Computed from loan_book outstanding_balance_eur",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_reduction_pct": 0
    },
    {
        "kpi_code": "FIN-003",
        "kpi_name": "High-emission sector exposure",
        "category": "Portfolio",
        "unit": "%",
        "source_logic": "Computed from loan_book exposure where NACE is high-emission sector",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_reduction_pct": 30
    },
    {
        "kpi_code": "FIN-004",
        "kpi_name": "Average PCAF data quality score",
        "category": "Data quality",
        "unit": "score",
        "source_logic": "Exposure-weighted average from counterparty_master pcaf_quality_score",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_value": 2.5
    },
    {
        "kpi_code": "FIN-005",
        "kpi_name": "Counterparty ESG data coverage",
        "category": "Data quality",
        "unit": "%",
        "source_logic": "Share of loan counterparties with emissions data source populated",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_value": 95
    },
    {
        "kpi_code": "FIN-006",
        "kpi_name": "SBTi-aligned exposure",
        "category": "Climate targets",
        "unit": "%",
        "source_logic": "Exposure share to counterparties with sbti_target_flag",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_value": 35
    },
    {
        "kpi_code": "FIN-007",
        "kpi_name": "High transition risk exposure",
        "category": "Climate risk",
        "unit": "%",
        "source_logic": "Exposure share where transition_risk_score >= 7",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_reduction_pct": 35
    },
    {
        "kpi_code": "SOC-001",
        "kpi_name": "Gender pay gap",
        "category": "Social",
        "unit": "%",
        "source_logic": "Synthetic supporting social KPI, later IFRS S1 scope",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_value": 5.0
    },
    {
        "kpi_code": "SOC-002",
        "kpi_name": "ESG training completion",
        "category": "Social",
        "unit": "%",
        "source_logic": "Synthetic supporting workforce KPI for sustainability risk capability",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_value": 95
    },
    {
        "kpi_code": "GOV-001",
        "kpi_name": "Board meetings with ESG agenda",
        "category": "Governance",
        "unit": "%",
        "source_logic": "Synthetic governance KPI linked to board_minutes",
        "baseline_year": 2019,
        "target_year": 2030,
        "target_value": 100
    },
]

# =========================================================
# BUILD KPI TRACKER WITH ENTITY_ID
# =========================================================
rows = []

for _, entity in entities.iterrows():
    entity_id = entity["entity_id"]

    scope1_series = scope1_by_entity_year.reindex(
        pd.MultiIndex.from_product([[entity_id], years])
    ).fillna(0)
    scope1_series.index = years

    scope2_series = scope2_by_entity_year.reindex(
        pd.MultiIndex.from_product([[entity_id], years])
    ).fillna(0)
    scope2_series.index = years

    energy_series = energy_by_entity_year.reindex(
        pd.MultiIndex.from_product([[entity_id], years])
    ).fillna(0)
    energy_series.index = years

    cost_series = energy_cost_by_entity_year.reindex(
        pd.MultiIndex.from_product([[entity_id], years])
    ).fillna(0)
    cost_series.index = years

    financed_2024 = financed_2024_by_entity.get(entity_id, 0)
    portfolio_2024 = portfolio_2024_by_entity.get(entity_id, 0)
    high_emission_pct_2024 = high_emission_exposure_pct_2024_by_entity.get(entity_id, 0)
    avg_pcaf_quality_2024 = avg_pcaf_quality_2024_by_entity.get(entity_id, 4)
    esg_coverage_2024 = esg_data_coverage_pct_2024_by_entity.get(entity_id, 0)
    sbti_pct_2024 = sbti_exposure_pct_2024_by_entity.get(entity_id, 0)
    transition_high_risk_2024 = transition_high_risk_exposure_pct_2024_by_entity.get(entity_id, 0)

    actual_series = {
        "ENV-001": scope1_series,
        "ENV-002": scope2_series,
        "ENV-003": scope1_series + scope2_series,
        "ENV-004": energy_series,
        "ENV-005": cost_series,
        "FIN-001": backcast_to_2024(financed_2024, annual_change=0.035, noise=0.015),
        "FIN-002": backcast_to_2024(portfolio_2024, annual_change=-0.02, noise=0.01),
        "FIN-003": backcast_to_2024(high_emission_pct_2024, annual_change=0.02, noise=0.015),
        "FIN-004": pd.Series({
            y: max(1, min(5, avg_pcaf_quality_2024 + (2024 - y) * 0.12 + rng.normal(0, 0.03)))
            for y in years
        }),
        "FIN-005": pd.Series({
            y: max(0, min(100, esg_coverage_2024 - (2024 - y) * 5 + rng.normal(0, 1.0)))
            for y in years
        }),
        "FIN-006": pd.Series({
            y: max(0, min(100, sbti_pct_2024 - (2024 - y) * 2.5 + rng.normal(0, 0.8)))
            for y in years
        }),
        "FIN-007": pd.Series({
            y: max(0, min(100, transition_high_risk_2024 + (2024 - y) * 1.2 + rng.normal(0, 0.4)))
            for y in years
        }),
        "SOC-001": smooth_series(18.2, 5.0, 0.04),
        "SOC-002": smooth_series(38.0, 95.0, 0.03),
        "GOV-001": smooth_series(35.0, 100.0, 0.03),
    }

    for kpi in kpi_catalogue:
        code = kpi["kpi_code"]
        s = actual_series[code].reindex(years)

        baseline_value = float(s.loc[kpi["baseline_year"]])

        if "target_value" in kpi:
            target_value = float(kpi["target_value"])
        else:
            if kpi["target_reduction_pct"] == 0:
                target_value = baseline_value
            else:
                target_value = baseline_value * (1 - kpi["target_reduction_pct"] / 100)

        for year in years:
            actual_value = float(s.loc[year])

            if baseline_value == target_value:
                progress_to_target_pct = None
                on_track_flag = None
            else:
                if target_value < baseline_value:
                    progress_to_target_pct = (
                        (baseline_value - actual_value) /
                        (baseline_value - target_value)
                    ) * 100
                else:
                    progress_to_target_pct = (
                        (actual_value - baseline_value) /
                        (target_value - baseline_value)
                    ) * 100

                elapsed = year - kpi["baseline_year"]
                horizon = kpi["target_year"] - kpi["baseline_year"]
                expected_progress = (elapsed / horizon) * 100 * 0.90
                on_track_flag = bool(progress_to_target_pct >= expected_progress)

            rows.append({
                "kpi_record_id": f"KPI-{entity_id}-{code}-{year}",
                "entity_id": entity_id,
                "kpi_code": code,
                "kpi_name": kpi["kpi_name"],
                "category": kpi["category"],
                "reporting_year": year,
                "unit": kpi["unit"],
                "baseline_year": kpi["baseline_year"],
                "baseline_value": round(baseline_value, 4),
                "actual_value": round(actual_value, 4),
                "target_year": kpi["target_year"],
                "target_value": round(target_value, 4),
                "target_reduction_pct": kpi.get("target_reduction_pct", None),
                "progress_to_target_pct": (
                    None
                    if progress_to_target_pct is None
                    else round(float(np.clip(progress_to_target_pct, -100, 200)), 2)
                ),
                "on_track_flag": on_track_flag,
                "source_logic": kpi["source_logic"],
                "data_lineage": (
                    "derived_from_core_tables"
                    if code.startswith(("ENV", "FIN"))
                    else "synthetic_supporting_kpi"
                ),
                "created_from": "synthetic_esg_kpi_tracker_generation_entity_level_v2"
            })

esg_kpi_tracker = pd.DataFrame(rows)

# =========================================================
# VALIDATION
# =========================================================
validation = {
    "rows": len(esg_kpi_tracker),
    "unique_kpi_record_id": int(esg_kpi_tracker["kpi_record_id"].is_unique),
    "entities_covered": esg_kpi_tracker["entity_id"].nunique(),
    "years_covered": sorted(esg_kpi_tracker["reporting_year"].unique().tolist()),
    "kpis_covered": esg_kpi_tracker["kpi_code"].nunique(),
    "missing_entity_id": int(esg_kpi_tracker["entity_id"].isna().sum()),
    "missing_actual_value": int(esg_kpi_tracker["actual_value"].isna().sum()),
    "duplicate_entity_kpi_year": int(
        esg_kpi_tracker.duplicated(
            subset=["entity_id", "kpi_code", "reporting_year"]
        ).sum()
    ),
    "progress_outside_-100_200": int(
        (
            esg_kpi_tracker["progress_to_target_pct"].dropna().lt(-100) |
            esg_kpi_tracker["progress_to_target_pct"].dropna().gt(200)
        ).sum()
    ),
}

out_path = DATA_DIR / "esg_kpi_tracker_raw.csv"
esg_kpi_tracker.to_csv(out_path, index=False)

print(f"Generated: {out_path}")
for k, v in validation.items():
    print(f"{k}: {v}")

esg_kpi_tracker.head(20)

Generated: Data\esg_kpi_tracker_raw.csv
rows: 900
unique_kpi_record_id: 1
entities_covered: 10
years_covered: [2019, 2020, 2021, 2022, 2023, 2024]
kpis_covered: 15
missing_entity_id: 0
missing_actual_value: 0
duplicate_entity_kpi_year: 0
progress_outside_-100_200: 0

,kpi_record_id,entity_id,kpi_code,kpi_name,category,reporting_year,unit,baseline_year,baseline_value,actual_value,target_year,target_value,target_reduction_pct,progress_to_target_pct,on_track_flag,source_logic,data_lineage,created_from
0,KPI-ENT-GROUP-001-ENV-001-2019,ENT-GROUP-001,ENV-001,Scope 1 emissions,Climate,2019,tCO2e,2019,6.264203e+02,6.264203e+02,2030,3.132101e+02,50.0,0.00,True,Computed from utility_bills natural_gas and di...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
1,KPI-ENT-GROUP-001-ENV-001-2020,ENT-GROUP-001,ENV-001,Scope 1 emissions,Climate,2020,tCO2e,2019,6.264203e+02,6.772515e+02,2030,3.132101e+02,50.0,-16.23,False,Computed from utility_bills natural_gas and di...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
2,KPI-ENT-GROUP-001-ENV-001-2021,ENT-GROUP-001,ENV-001,Scope 1 emissions,Climate,2021,tCO2e,2019,6.264203e+02,6.481542e+02,2030,3.132101e+02,50.0,-6.94,False,Computed from utility_bills natural_gas and di...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
3,KPI-ENT-GROUP-001-ENV-001-2022,ENT-GROUP-001,ENV-001,Scope 1 emissions,Climate,2022,tCO2e,2019,6.264203e+02,6.796186e+02,2030,3.132101e+02,50.0,-16.98,False,Computed from utility_bills natural_gas and di...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
4,KPI-ENT-GROUP-001-ENV-001-2023,ENT-GROUP-001,ENV-001,Scope 1 emissions,Climate,2023,tCO2e,2019,6.264203e+02,6.698341e+02,2030,3.132101e+02,50.0,-13.86,False,Computed from utility_bills natural_gas and di...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
5,KPI-ENT-GROUP-001-ENV-001-2024,ENT-GROUP-001,ENV-001,Scope 1 emissions,Climate,2024,tCO2e,2019,6.264203e+02,6.294259e+02,2030,3.132101e+02,50.0,-0.96,False,Computed from utility_bills natural_gas and di...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
6,KPI-ENT-GROUP-001-ENV-002-2019,ENT-GROUP-001,ENV-002,Scope 2 location-based emissions,Climate,2019,tCO2e,2019,7.742821e+02,7.742821e+02,2030,3.871410e+02,50.0,0.00,True,Computed from utility_bills electricity using ...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
7,KPI-ENT-GROUP-001-ENV-002-2020,ENT-GROUP-001,ENV-002,Scope 2 location-based emissions,Climate,2020,tCO2e,2019,7.742821e+02,7.681292e+02,2030,3.871410e+02,50.0,1.59,False,Computed from utility_bills electricity using ...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
8,KPI-ENT-GROUP-001-ENV-002-2021,ENT-GROUP-001,ENV-002,Scope 2 location-based emissions,Climate,2021,tCO2e,2019,7.742821e+02,7.183855e+02,2030,3.871410e+02,50.0,14.44,False,Computed from utility_bills electricity using ...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
9,KPI-ENT-GROUP-001-ENV-002-2022,ENT-GROUP-001,ENV-002,Scope 2 location-based emissions,Climate,2022,tCO2e,2019,7.742821e+02,6.952847e+02,2030,3.871410e+02,50.0,20.41,False,Computed from utility_bills electricity using ...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
10,KPI-ENT-GROUP-001-ENV-002-2023,ENT-GROUP-001,ENV-002,Scope 2 location-based emissions,Climate,2023,tCO2e,2019,7.742821e+02,6.486027e+02,2030,3.871410e+02,50.0,32.46,False,Computed from utility_bills electricity using ...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
11,KPI-ENT-GROUP-001-ENV-002-2024,ENT-GROUP-001,ENV-002,Scope 2 location-based emissions,Climate,2024,tCO2e,2019,7.742821e+02,6.395635e+02,2030,3.871410e+02,50.0,34.80,False,Computed from utility_bills electricity using ...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
12,KPI-ENT-GROUP-001-ENV-003-2019,ENT-GROUP-001,ENV-003,Total operational Scope 1 and 2 emissions,Climate,2019,tCO2e,2019,1.400702e+03,1.400702e+03,2030,7.003512e+02,50.0,0.00,True,Derived as Scope 1 + Scope 2,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
13,KPI-ENT-GROUP-001-ENV-003-2020,ENT-GROUP-001,ENV-003,Total operational Scope 1 and 2 emissions,Climate,2020,tCO2e,2019,1.400702e+03,1.445381e+03,2030,7.003512e+02,50.0,-6.38,False,Derived as Scope 1 + Scope 2,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
14,KPI-ENT-GROUP-001-ENV-003-2021,ENT-GROUP-001,ENV-003,Total operational Scope 1 and 2 emissions,Climate,2021,tCO2e,2019,1.400702e+03,1.366540e+03,2030,7.003512e+02,50.0,4.88,False,Derived as Scope 1 + Scope 2,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
15,KPI-ENT-GROUP-001-ENV-003-2022,ENT-GROUP-001,ENV-003,Total operational Scope 1 and 2 emissions,Climate,2022,tCO2e,2019,1.400702e+03,1.374903e+03,2030,7.003512e+02,50.0,3.68,False,Derived as Scope 1 + Scope 2,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
16,KPI-ENT-GROUP-001-ENV-003-2023,ENT-GROUP-001,ENV-003,Total operational Scope 1 and 2 emissions,Climate,2023,tCO2e,2019,1.400702e+03,1.318437e+03,2030,7.003512e+02,50.0,11.75,False,Derived as Scope 1 + Scope 2,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
17,KPI-ENT-GROUP-001-ENV-003-2024,ENT-GROUP-001,ENV-003,Total operational Scope 1 and 2 emissions,Climate,2024,tCO2e,2019,1.400702e+03,1.268989e+03,2030,7.003512e+02,50.0,18.81,False,Derived as Scope 1 + Scope 2,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
18,KPI-ENT-GROUP-001-ENV-004-2019,ENT-GROUP-001,ENV-004,Energy consumption,Climate,2019,kWh,2019,1.383143e+07,1.383143e+07,2030,1.106514e+07,20.0,0.00,True,Computed from utility_bills electricity and na...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...
19,KPI-ENT-GROUP-001-ENV-004-2020,ENT-GROUP-001,ENV-004,Energy consumption,Climate,2020,kWh,2019,1.383143e+07,1.441866e+07,2030,1.106514e+07,20.0,-21.23,False,Computed from utility_bills electricity and na...,derived_from_core_tables,synthetic_esg_kpi_tracker_generation_entity_le...

HR System : HR data for the executive team

In [10]:
import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# CONFIG
# =========================================================
rng = np.random.default_rng(42)

DATA_DIR = Path("Data")
OUTPUT_PATH = DATA_DIR / "hr_system_raw.csv"

years = list(range(2019, 2025))

# =========================================================
# LOAD DEPENDENCIES
# =========================================================
entity_master = pd.read_csv(DATA_DIR / "entity_master_raw.csv")
esg_kpi_tracker = pd.read_csv(DATA_DIR / "esg_kpi_tracker_raw.csv")

# Clean column names
for df in [entity_master, esg_kpi_tracker]:
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

# Normalize boolean
entity_master["in_scope_esg_flag"] = (
    entity_master["in_scope_esg_flag"]
    .astype(str)
    .str.lower()
    .isin(["true", "1", "yes"])
)

# =========================================================
# FILTER IN-SCOPE ENTITIES
# =========================================================
entities = (
    entity_master.loc[
        entity_master["in_scope_esg_flag"].eq(True),
        ["entity_id", "legal_name", "country_code"]
    ]
    .dropna(subset=["entity_id", "country_code"])
    .drop_duplicates()
    .reset_index(drop=True)
)

if entities.empty:
    raise ValueError("No in-scope ESG entities found in entity_master_raw.csv")

# =========================================================
# KPI CATALOGUE
# =========================================================
kpi_catalogue = (
    esg_kpi_tracker[["kpi_code", "kpi_name", "category"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

eligible_kpis = (
    kpi_catalogue[
        kpi_catalogue["category"].isin([
            "Climate",
            "Financed emissions",
            "Climate risk",
            "Climate targets",
            "Governance",
            "Data quality",
            "Portfolio",
        ])
    ]
    .reset_index(drop=True)
)

if eligible_kpis.empty:
    raise ValueError("No eligible ESG KPIs found in esg_kpi_tracker_raw.csv")

# =========================================================
# ROLE CONFIGURATION
# =========================================================
role_cfg = {
    "CEO": {
        "base_esg": 20,
        "esg_std": 3,
        "train_lambda": 12,
        "fixed_pay_mu": np.log(650_000),
        "variable_pay_mu": np.log(220_000),
        "pay_sigma": 0.25,
        "kpi_count": 4,
    },
    "CFO": {
        "base_esg": 15,
        "esg_std": 3,
        "train_lambda": 10,
        "fixed_pay_mu": np.log(480_000),
        "variable_pay_mu": np.log(150_000),
        "pay_sigma": 0.25,
        "kpi_count": 3,
    },
    "CRO": {
        "base_esg": 25,
        "esg_std": 4,
        "train_lambda": 14,
        "fixed_pay_mu": np.log(430_000),
        "variable_pay_mu": np.log(135_000),
        "pay_sigma": 0.25,
        "kpi_count": 4,
    },
    "CSO": {
        "base_esg": 50,
        "esg_std": 8,
        "train_lambda": 40,
        "fixed_pay_mu": np.log(360_000),
        "variable_pay_mu": np.log(110_000),
        "pay_sigma": 0.25,
        "kpi_count": 5,
    },
    "BOARD_MEMBER": {
        "base_esg": 6,
        "esg_std": 2,
        "train_lambda": 8,
        "fixed_pay_mu": np.log(95_000),
        "variable_pay_mu": np.log(25_000),
        "pay_sigma": 0.20,
        "kpi_count": 2,
    },
}

first_names = [
    "Alex", "Morgan", "Jordan", "Taylor", "Sam", "Riley",
    "Nora", "Maya", "Sofia", "Adam", "Lea", "Victor",
    "Emma", "Karim", "Lina", "David"
]

last_names = [
    "Martin", "Schmidt", "Dubois", "Rossi", "Jansen",
    "Smith", "Garcia", "Moreau", "Weber", "Brown",
    "Lefevre", "Muller", "Costa", "Haddad", "Bianchi"
]

# =========================================================
# CREATE PEOPLE MASTER
# =========================================================
people = []
person_counter = 1

for _, entity in entities.iterrows():
    fixed_roles = ["CEO", "CFO", "CRO"]

    if rng.random() < 0.80:
        fixed_roles.append("CSO")

    board_count = int(rng.integers(3, 6))
    roles = fixed_roles + ["BOARD_MEMBER"] * board_count

    for role_instance, role in enumerate(roles, start=1):
        gender = rng.choice(
            ["female", "male"],
            p=[0.42, 0.58]
        )

        people.append({
            "person_id": f"EXEC-{person_counter:05d}",
            "entity_id": entity["entity_id"],
            "entity_legal_name": entity["legal_name"],
            "country_code": entity["country_code"],
            "full_name": f"{rng.choice(first_names)} {rng.choice(last_names)}",
            "gender": gender,
            "role": role,
            "role_instance": role_instance,
        })

        person_counter += 1

people_df = pd.DataFrame(people)

# =========================================================
# GENERATE HR RECORDS
# =========================================================
rows = []

for _, person in people_df.iterrows():
    cfg = role_cfg[person["role"]]

    selected_kpis = eligible_kpis.sample(
        n=min(cfg["kpi_count"], len(eligible_kpis)),
        replace=False,
        random_state=int(rng.integers(1, 1_000_000))
    )

    kpi_names = selected_kpis["kpi_name"].tolist()
    kpi_codes = selected_kpis["kpi_code"].tolist()

    base_fixed_pay = rng.lognormal(
        mean=cfg["fixed_pay_mu"],
        sigma=cfg["pay_sigma"]
    )

    base_variable_pay = rng.lognormal(
        mean=cfg["variable_pay_mu"],
        sigma=cfg["pay_sigma"]
    )

    # Small synthetic gender pay gap effect for raw data realism
    # This allows SOC-001 to be calculated later.
    gender_pay_adjustment = 0.94 if person["gender"] == "female" else 1.00

    for year in years:
        yrs_since_base = year - 2019

        esg_weight = (
            cfg["base_esg"]
            + (yrs_since_base * rng.uniform(1.8, 3.0))
            + rng.normal(0, cfg["esg_std"])
        )

        esg_weight = float(np.clip(esg_weight, 0, 100))

        train_lambda = (
            cfg["train_lambda"]
            + yrs_since_base * (
                1.5 if person["role"] in ["CSO", "CRO"] else 0.8
            )
        )

        climate_training_hours = int(
            rng.poisson(max(train_lambda, 0.1))
        )

        esg_training_required_flag = True

        # Training completion improves over time
        completion_probability = np.clip(
            0.45 + yrs_since_base * 0.07,
            0.40,
            0.95
        )

        if person["role"] in ["CSO", "CRO"]:
            completion_probability = min(
                completion_probability + 0.12,
                0.98
            )

        esg_training_completed_flag = (
            rng.random() < completion_probability
        )

        if esg_training_completed_flag:
            esg_training_completion_date = pd.Timestamp(
                year=year,
                month=int(rng.integers(1, 13)),
                day=int(rng.integers(1, 28))
            ).date()
        else:
            esg_training_completion_date = pd.NaT

        fixed_pay = (
            base_fixed_pay
            * (1 + 0.025 * yrs_since_base)
            * rng.lognormal(mean=0, sigma=0.06)
            * gender_pay_adjustment
        )

        variable_pay = (
            base_variable_pay
            * (1 + 0.030 * yrs_since_base)
            * rng.lognormal(mean=0, sigma=0.12)
            * gender_pay_adjustment
        )

        total_compensation = fixed_pay + variable_pay

        rows.append({
            "hr_record_id": f"HR-{person['person_id']}-{year}",
            "person_id": person["person_id"],
            "entity_id": person["entity_id"],
            "entity_legal_name": person["entity_legal_name"],
            "country_code": person["country_code"],
            "full_name": person["full_name"],
            "gender": person["gender"],
            "role": person["role"],
            "role_instance": person["role_instance"],
            "reporting_year": year,

            "fixed_pay_eur": round(fixed_pay, 2),
            "total_variable_pay_eur": round(variable_pay, 2),
            "total_compensation_eur": round(total_compensation, 2),

            "esg_bonus_weight_pct": round(esg_weight, 1),
            "esg_bonus_kpi_codes": "; ".join(kpi_codes),
            "esg_bonus_kpis": "; ".join(kpi_names),

            "esg_training_required_flag": esg_training_required_flag,
            "esg_training_completed_flag": esg_training_completed_flag,
            "esg_training_completion_date": esg_training_completion_date,
            "climate_training_hours_yr": climate_training_hours,

            "data_source": "synthetic_hr_remuneration_and_training_snapshot",
            "created_from": "synthetic_hr_system_generation_v2_core_tables_aligned",
        })

hr_system = pd.DataFrame(rows)

# =========================================================
# VALIDATION
# =========================================================
valid_entity_ids = set(entity_master["entity_id"].astype(str))
valid_kpi_codes = set(esg_kpi_tracker["kpi_code"].astype(str).unique())
valid_kpi_names = set(esg_kpi_tracker["kpi_name"].astype(str).unique())

referenced_codes = set()
for val in hr_system["esg_bonus_kpi_codes"]:
    referenced_codes.update([
        x.strip()
        for x in str(val).split(";")
        if x.strip()
    ])

referenced_names = set()
for val in hr_system["esg_bonus_kpis"]:
    referenced_names.update([
        x.strip()
        for x in str(val).split(";")
        if x.strip()
    ])

role_counts = (
    hr_system[
        hr_system["role"].isin(["CEO", "CFO", "CRO"])
    ]
    .groupby(["entity_id", "reporting_year", "role"])
    .size()
    .reset_index(name="count")
)

training_completion_rate = (
    hr_system["esg_training_completed_flag"].mean() * 100
)

gender_pay_gap_2024 = np.nan

pay_2024 = hr_system[
    hr_system["reporting_year"].eq(2024)
].copy()

male_avg_pay = pay_2024.loc[
    pay_2024["gender"].eq("male"),
    "total_compensation_eur"
].mean()

female_avg_pay = pay_2024.loc[
    pay_2024["gender"].eq("female"),
    "total_compensation_eur"
].mean()

if pd.notna(male_avg_pay) and male_avg_pay > 0:
    gender_pay_gap_2024 = (
        (male_avg_pay - female_avg_pay)
        / male_avg_pay
        * 100
    )

validation = {
    "rows": len(hr_system),
    "persons": hr_system["person_id"].nunique(),
    "entities_covered": hr_system["entity_id"].nunique(),
    "years_covered": sorted(hr_system["reporting_year"].unique().tolist()),
    "unique_hr_record_id": int(hr_system["hr_record_id"].is_unique),

    "entity_id_missing_from_entity_master": int(
        (~hr_system["entity_id"].astype(str).isin(valid_entity_ids)).sum()
    ),

    "esg_bonus_weight_outside_0_100": int(
        (
            (hr_system["esg_bonus_weight_pct"] < 0)
            | (hr_system["esg_bonus_weight_pct"] > 100)
        ).sum()
    ),

    "negative_training_hours": int(
        (hr_system["climate_training_hours_yr"] < 0).sum()
    ),

    "non_positive_fixed_pay": int(
        (hr_system["fixed_pay_eur"] <= 0).sum()
    ),

    "non_positive_variable_pay": int(
        (hr_system["total_variable_pay_eur"] <= 0).sum()
    ),

    "non_positive_total_compensation": int(
        (hr_system["total_compensation_eur"] <= 0).sum()
    ),

    "invalid_referenced_kpi_codes": len(
        referenced_codes - valid_kpi_codes
    ),

    "invalid_referenced_kpi_names": len(
        referenced_names - valid_kpi_names
    ),

    "mandatory_role_count_violations": int(
        (role_counts["count"] != 1).sum()
    ),

    "training_completion_rate_pct": round(training_completion_rate, 2),
    "gender_pay_gap_2024_pct": (
        None
        if pd.isna(gender_pay_gap_2024)
        else round(gender_pay_gap_2024, 2)
    ),
}

# =========================================================
# SAVE
# =========================================================
hr_system.to_csv(OUTPUT_PATH, index=False)

print(f"Generated: {OUTPUT_PATH}")

print("\nValidation:")
for key, value in validation.items():
    print(f"{key}: {value}")

print("\nPreview:")
print(hr_system.head(12))

Generated: Data\hr_system_raw.csv

Validation:
rows: 438
persons: 73
entities_covered: 10
years_covered: [2019, 2020, 2021, 2022, 2023, 2024]
unique_hr_record_id: 1
entity_id_missing_from_entity_master: 0
esg_bonus_weight_outside_0_100: 0
negative_training_hours: 0
non_positive_fixed_pay: 0
non_positive_variable_pay: 0
non_positive_total_compensation: 0
invalid_referenced_kpi_codes: 0
invalid_referenced_kpi_names: 0
mandatory_role_count_violations: 0
training_completion_rate_pct: 69.63
gender_pay_gap_2024_pct: -5.21

Preview:
          hr_record_id   person_id      entity_id       entity_legal_name  \
0   HR-EXEC-00001-2019  EXEC-00001  ENT-GROUP-001  Atlas Banking Group SA
1   HR-EXEC-00001-2020  EXEC-00001  ENT-GROUP-001  Atlas Banking Group SA
2   HR-EXEC-00001-2021  EXEC-00001  ENT-GROUP-001  Atlas Banking Group SA
3   HR-EXEC-00001-2022  EXEC-00001  ENT-GROUP-001  Atlas Banking Group SA
4   HR-EXEC-00001-2023  EXEC-00001  ENT-GROUP-001  Atlas Banking Group SA
5   HR-EXEC-00001-2024  EXEC-00001  ENT-GROUP-001  Atlas Banking Group SA
6   HR-EXEC-00002-2019  EXEC-00002  ENT-GROUP-001  Atlas Banking Group SA
7   HR-EXEC-00002-2020  EXEC-00002  ENT-GROUP-001  Atlas Banking Group SA
8   HR-EXEC-00002-2021  EXEC-00002  ENT-GROUP-001  Atlas Banking Group SA
9   HR-EXEC-00002-2022  EXEC-00002  ENT-GROUP-001  Atlas Banking Group SA
10  HR-EXEC-00002-2023  EXEC-00002  ENT-GROUP-001  Atlas Banking Group SA
11  HR-EXEC-00002-2024  EXEC-00002  ENT-GROUP-001  Atlas Banking Group SA

   country_code      full_name  gender role  role_instance  reporting_year  \
0            FR   Maya Schmidt    male  CEO              1            2019
1            FR   Maya Schmidt    male  CEO              1            2020
2            FR   Maya Schmidt    male  CEO              1            2021
3            FR   Maya Schmidt    male  CEO              1            2022
4            FR   Maya Schmidt    male  CEO              1            2023
5            FR   Maya Schmidt    male  CEO              1            2024
6            FR  Victor Moreau  female  CFO              2            2019
7            FR  Victor Moreau  female  CFO              2            2020
8            FR  Victor Moreau  female  CFO              2            2021
9            FR  Victor Moreau  female  CFO              2            2022
10           FR  Victor Moreau  female  CFO              2            2023
11           FR  Victor Moreau  female  CFO              2            2024

    ...  total_compensation_eur  esg_bonus_weight_pct  \
0   ...               660112.25                  26.4
1   ...               686661.39                  18.5
2   ...               677051.52                  28.4
3   ...               704172.45                  24.2
4   ...               672690.11                  31.5
5   ...               747483.72                  29.2
6   ...               579206.08                  19.0
7   ...               580386.09                  17.7
8   ...               589558.29                  18.7
9   ...               703564.16                  28.4
10  ...               663326.23                  26.1
11  ...               689388.81                  20.8

                   esg_bonus_kpi_codes  \
0   FIN-008; FIN-009; ENV-004; FIN-004
1   FIN-008; FIN-009; ENV-004; FIN-004
2   FIN-008; FIN-009; ENV-004; FIN-004
3   FIN-008; FIN-009; ENV-004; FIN-004
4   FIN-008; FIN-009; ENV-004; FIN-004
5   FIN-008; FIN-009; ENV-004; FIN-004
6            FIN-007; FIN-005; ENV-004
7            FIN-007; FIN-005; ENV-004
8            FIN-007; FIN-005; ENV-004
9            FIN-007; FIN-005; ENV-004
10           FIN-007; FIN-005; ENV-004
11           FIN-007; FIN-005; ENV-004

                                       esg_bonus_kpis  \
0   Sovereign bond exposure; Project finance expos...
1   Sovereign bond exposure; Project finance expos...
2   Sovereign bond exposure; Project finance expos...
3   Sovereign bond exposure; Project finance expos...
4   Sovereign bond exposure; Project finance expos...
5   Sovereign bond exposure; Project finance expos...
6   High transition risk exposure; Financed emissi...
7   High transition risk exposure; Financed emissi...
8   High transition risk exposure; Financed emissi...
9   High transition risk exposure; Financed emissi...
10  High transition risk exposure; Financed emissi...
11  High transition risk exposure; Financed emissi...

   esg_training_required_flag esg_training_completed_flag  \
0                        True                        True
1                        True                       False
2                        True                       False
3                        True                       False
4                        True                        True
5                        True                        True
6                        True                        True
7                        True                        True
8                        True                        True
9                        True                       False
10                       True                        True
11                       True                        True

    esg_training_completion_date  climate_training_hours_yr  \
0                     2019-11-27                         10
1                            NaT                         13
2                            NaT                         10
3                            NaT                         12
4                     2023-12-09                         10
5                     2024-07-12                         19
6                     2019-08-15                          8
7                     2020-08-03                         10
8                     2021-12-12                         13
9                            NaT                          9
10                    2023-11-25                         17
11                    2024-07-19                         10

                                        data_source  \
0   synthetic_hr_remuneration_and_training_snapshot
1   synthetic_hr_remuneration_and_training_snapshot
2   synthetic_hr_remuneration_and_training_snapshot
3   synthetic_hr_remuneration_and_training_snapshot
4   synthetic_hr_remuneration_and_training_snapshot
5   synthetic_hr_remuneration_and_training_snapshot
6   synthetic_hr_remuneration_and_training_snapshot
7   synthetic_hr_remuneration_and_training_snapshot
8   synthetic_hr_remuneration_and_training_snapshot
9   synthetic_hr_remuneration_and_training_snapshot
10  synthetic_hr_remuneration_and_training_snapshot
11  synthetic_hr_remuneration_and_training_snapshot

                                         created_from
0   synthetic_hr_system_generation_v2_core_tables_...
1   synthetic_hr_system_generation_v2_core_tables_...
2   synthetic_hr_system_generation_v2_core_tables_...
3   synthetic_hr_system_generation_v2_core_tables_...
4   synthetic_hr_system_generation_v2_core_tables_...
5   synthetic_hr_system_generation_v2_core_tables_...
6   synthetic_hr_system_generation_v2_core_tables_...
7   synthetic_hr_system_generation_v2_core_tables_...
8   synthetic_hr_system_generation_v2_core_tables_...
9   synthetic_hr_system_generation_v2_core_tables_...
10  synthetic_hr_system_generation_v2_core_tables_...
11  synthetic_hr_system_generation_v2_core_tables_...

[12 rows x 22 columns]

ERM System : The enterprise risk register

In [12]:
import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# CONFIG
# =========================================================
rng = np.random.default_rng(42)

DATA_DIR = Path("Data")
OUTPUT_PATH = DATA_DIR / "erm_system_raw.csv"

years = list(range(2019, 2025))

# =========================================================
# LOAD DEPENDENCIES
# =========================================================
entity_master = pd.read_csv(DATA_DIR / "entity_master_raw.csv")
geo_risk_db = pd.read_csv(DATA_DIR / "geo_risk_db_raw.csv")
loan_book = pd.read_csv(DATA_DIR / "loan_book_raw.csv")
counterparty_master = pd.read_csv(DATA_DIR / "counterparty_master_raw.csv")
collateral_register = pd.read_csv(DATA_DIR / "collateral_register_raw.csv")

# Clean columns
for df in [entity_master, geo_risk_db, loan_book, counterparty_master, collateral_register]:
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

# Normalize booleans
if "in_scope_esg_flag" in entity_master.columns:
    entity_master["in_scope_esg_flag"] = (
        entity_master["in_scope_esg_flag"]
        .astype(str)
        .str.lower()
        .isin(["true", "1", "yes"])
    )

for col in ["listed_flag", "sbti_target_flag", "verification_flag"]:
    if col in counterparty_master.columns:
        counterparty_master[col] = (
            counterparty_master[col]
            .astype(str)
            .str.lower()
            .isin(["true", "1", "yes"])
        )

for col in ["listed_flag", "green_label_flag", "has_control"]:
    if col in loan_book.columns:
        loan_book[col] = (
            loan_book[col]
            .astype(str)
            .str.lower()
            .isin(["true", "1", "yes"])
        )

# =========================================================
# REQUIRED COLUMN CHECKS
# =========================================================
required_entity_cols = [
    "entity_id",
    "legal_name",
    "country_code",
    "in_scope_esg_flag",
]

required_geo_cols = [
    "geo_id",
    "country_code",
]

required_loan_cols = [
    "facility_id",
    "entity_id",
    "counterparty_id",
    "pcaf_asset_class",
    "outstanding_balance_eur",
    "nace_code",
]

required_cp_cols = [
    "counterparty_id",
    "segment",
    "country_code",
    "transition_risk_score",
    "sbti_target_flag",
    "pcaf_quality_score",
    "data_source_type",
]

required_collateral_cols = [
    "collateral_id",
    "facility_id",
    "collateral_type",
    "allocated_outstanding_balance_eur",
]

missing_entity_cols = [c for c in required_entity_cols if c not in entity_master.columns]
missing_geo_cols = [c for c in required_geo_cols if c not in geo_risk_db.columns]
missing_loan_cols = [c for c in required_loan_cols if c not in loan_book.columns]
missing_cp_cols = [c for c in required_cp_cols if c not in counterparty_master.columns]
missing_collateral_cols = [c for c in required_collateral_cols if c not in collateral_register.columns]

if missing_entity_cols:
    raise ValueError(f"entity_master is missing columns: {missing_entity_cols}")

if missing_geo_cols:
    raise ValueError(f"geo_risk_db is missing columns: {missing_geo_cols}")

if missing_loan_cols:
    raise ValueError(f"loan_book is missing columns: {missing_loan_cols}")

if missing_cp_cols:
    raise ValueError(f"counterparty_master is missing columns: {missing_cp_cols}")

if missing_collateral_cols:
    raise ValueError(f"collateral_register is missing columns: {missing_collateral_cols}")

# =========================================================
# FILTER ENTITIES
# =========================================================
entities = (
    entity_master.loc[
        entity_master["in_scope_esg_flag"].eq(True),
        ["entity_id", "legal_name", "country_code"]
    ]
    .dropna(subset=["entity_id", "country_code"])
    .drop_duplicates()
    .reset_index(drop=True)
)

if entities.empty:
    raise ValueError("No in-scope ESG entities found in entity_master_raw.csv")

entities["country_code"] = entities["country_code"].astype(str).str.upper()
geo_risk_db["country_code"] = geo_risk_db["country_code"].astype(str).str.upper()

# =========================================================
# PREPARE LOAN + COUNTERPARTY EXPOSURE BASE
# =========================================================
loan_cp = loan_book.merge(
    counterparty_master[
        [
            "counterparty_id",
            "segment",
            "country_code",
            "transition_risk_score",
            "sbti_target_flag",
            "pcaf_quality_score",
            "data_source_type",
        ]
    ],
    on="counterparty_id",
    how="left",
    suffixes=("_loan", "_cp")
)

# Normalize country columns
if "borrower_country_code" in loan_cp.columns:
    loan_cp["risk_country_code"] = loan_cp["borrower_country_code"].astype(str).str.upper()
elif "country_code_cp" in loan_cp.columns:
    loan_cp["risk_country_code"] = loan_cp["country_code_cp"].astype(str).str.upper()
else:
    loan_cp["risk_country_code"] = loan_cp["country_code"].astype(str).str.upper()

loan_cp["nace_code"] = loan_cp["nace_code"].astype(str)

# =========================================================
# PREPARE COLLATERAL + LOAN EXPOSURE BASE
# =========================================================
collateral_exposure = collateral_register.merge(
    loan_book[
        [
            "facility_id",
            "entity_id",
            "counterparty_id",
            "pcaf_asset_class",
            "outstanding_balance_eur",
            "nace_code",
        ]
    ],
    on="facility_id",
    how="left"
)

# If collateral table has country_code, use it. Otherwise use loan/counterparty country later.
if "country_code" in collateral_exposure.columns:
    collateral_exposure["risk_country_code"] = (
        collateral_exposure["country_code"]
        .astype(str)
        .str.upper()
    )
else:
    collateral_exposure = collateral_exposure.merge(
        counterparty_master[["counterparty_id", "country_code"]],
        on="counterparty_id",
        how="left"
    )

    collateral_exposure["risk_country_code"] = (
        collateral_exposure["country_code"]
        .astype(str)
        .str.upper()
    )

# Keep only real estate collateral for physical risk
real_estate_collateral = collateral_exposure[
    collateral_exposure["collateral_type"].isin(
        ["residential_property", "commercial_property"]
    )
].copy()

# =========================================================
# HELPER FUNCTIONS
# =========================================================
def rating_from_score(score):
    if score <= 6:
        return "low"
    if score <= 12:
        return "medium"
    if score <= 19:
        return "high"
    return "critical"


def clip_score(x):
    return int(np.clip(round(x), 1, 5))


def get_geo_score(row, risk_category):
    """
    Pulls a physical hazard score from geo_risk_db when possible.
    Falls back to neutral score if the column does not exist.
    """
    if risk_category == "physical_acute":
        for col in ["acute_risk_composite", "flood_risk_score", "storm_risk_score"]:
            if col in row.index and pd.notna(row[col]):
                return float(row[col])

    if risk_category == "physical_chronic":
        for col in ["chronic_risk_composite", "heat_stress_score", "water_stress_score"]:
            if col in row.index and pd.notna(row[col]):
                return float(row[col])

    return 5.0


def get_geo_reference(country_code, risk_category):
    """
    Selects a relevant geo risk row for a country.
    If the country has no geo row, falls back to a global high-risk row.
    """
    country_geo = geo_risk_db[
        geo_risk_db["country_code"].astype(str).str.upper().eq(str(country_code).upper())
    ].copy()

    if country_geo.empty:
        country_geo = geo_risk_db.copy()

    if risk_category == "physical_acute":
        sort_cols = [
            col for col in ["acute_risk_composite", "flood_risk_score", "storm_risk_score"]
            if col in country_geo.columns
        ]
    else:
        sort_cols = [
            col for col in ["chronic_risk_composite", "heat_stress_score", "water_stress_score"]
            if col in country_geo.columns
        ]

    if sort_cols:
        country_geo = country_geo.sort_values(sort_cols, ascending=False)

    return country_geo.iloc[0]


def safe_sample(df, n=1):
    if df.empty:
        return None
    return df.sample(n=n, random_state=int(rng.integers(1, 1_000_000))).iloc[0]


def choose_transition_exposure(risk_name):
    """
    Selects loan/counterparty exposures depending on the transition risk type.
    """
    high_emission_nace = [
        "B05.10",
        "B06.10",
        "C23.51",
        "C24.10",
        "D35.11",
        "H51.10",
        "H49.41",
        "C20.16",
    ]

    if "carbon pricing" in risk_name.lower():
        pool = loan_cp[
            loan_cp["nace_code"].isin(high_emission_nace)
            | loan_cp["transition_risk_score"].ge(7)
        ]

    elif "stranded assets" in risk_name.lower():
        pool = loan_cp[
            loan_cp["nace_code"].isin(["B05.10", "B06.10", "D35.11"])
            | loan_cp["pcaf_asset_class"].isin(["business_loan", "project_finance"])
        ]

    elif "market repricing" in risk_name.lower():
        pool = loan_cp[
            loan_cp["pcaf_asset_class"].isin(["commercial_re", "mortgage"])
        ]

    elif "transition plan" in risk_name.lower():
        pool = loan_cp[
            loan_cp["sbti_target_flag"].eq(False)
            & loan_cp["pcaf_asset_class"].isin(["business_loan", "project_finance"])
        ]

    elif "scope 3" in risk_name.lower() or "data quality" in risk_name.lower():
        pool = loan_cp[
            loan_cp["pcaf_quality_score"].ge(4)
            | loan_cp["data_source_type"].isin(["proxy_model", "estimated_sector_avg"])
        ]

    else:
        pool = loan_cp

    if pool.empty:
        pool = loan_cp

    return safe_sample(pool)


def choose_physical_exposure(risk_category, risk_name):
    """
    Selects collateral exposures for physical acute/chronic risks.
    """
    pool = real_estate_collateral.copy()

    if "mortgage" in risk_name.lower():
        pool = pool[pool["pcaf_asset_class"].eq("mortgage")]

    elif "commercial" in risk_name.lower():
        pool = pool[pool["pcaf_asset_class"].eq("commercial_re")]

    if pool.empty:
        pool = real_estate_collateral

    return safe_sample(pool)


# =========================================================
# RISK CATALOGUE
# =========================================================
risk_catalogue = [
    {
        "risk_id": "RISK-001",
        "risk_name": "Flood risk - mortgage book",
        "risk_category": "physical_acute",
        "risk_owner_function": "Credit Risk",
        "base_likelihood": 3,
        "base_severity": 4,
        "climate_risk_driver": "flood",
        "time_horizon": "short_term",
    },
    {
        "risk_id": "RISK-002",
        "risk_name": "Storm surge - coastal collateral",
        "risk_category": "physical_acute",
        "risk_owner_function": "Credit Risk",
        "base_likelihood": 3,
        "base_severity": 4,
        "climate_risk_driver": "storm_surge",
        "time_horizon": "short_term",
    },
    {
        "risk_id": "RISK-003",
        "risk_name": "Chronic heat - commercial real estate",
        "risk_category": "physical_chronic",
        "risk_owner_function": "Portfolio Risk",
        "base_likelihood": 3,
        "base_severity": 3,
        "climate_risk_driver": "heat_stress",
        "time_horizon": "medium_term",
    },
    {
        "risk_id": "RISK-004",
        "risk_name": "Water stress - agribusiness borrowers",
        "risk_category": "physical_chronic",
        "risk_owner_function": "Sector Risk",
        "base_likelihood": 2,
        "base_severity": 3,
        "climate_risk_driver": "water_stress",
        "time_horizon": "medium_term",
    },
    {
        "risk_id": "RISK-005",
        "risk_name": "Carbon pricing - industrial loans",
        "risk_category": "transition_policy",
        "risk_owner_function": "Credit Risk",
        "base_likelihood": 4,
        "base_severity": 4,
        "climate_risk_driver": "carbon_pricing",
        "time_horizon": "medium_term",
    },
    {
        "risk_id": "RISK-006",
        "risk_name": "Mandatory climate disclosure non-compliance",
        "risk_category": "transition_policy",
        "risk_owner_function": "Compliance",
        "base_likelihood": 3,
        "base_severity": 4,
        "climate_risk_driver": "climate_disclosure_regulation",
        "time_horizon": "short_term",
    },
    {
        "risk_id": "RISK-007",
        "risk_name": "Greenwashing litigation and conduct risk",
        "risk_category": "transition_policy",
        "risk_owner_function": "Legal",
        "base_likelihood": 3,
        "base_severity": 4,
        "climate_risk_driver": "greenwashing_litigation",
        "time_horizon": "short_term",
    },
    {
        "risk_id": "RISK-008",
        "risk_name": "Stranded assets - fossil fuel sector",
        "risk_category": "transition_market",
        "risk_owner_function": "Sector Risk",
        "base_likelihood": 4,
        "base_severity": 5,
        "climate_risk_driver": "stranded_assets",
        "time_horizon": "long_term",
    },
    {
        "risk_id": "RISK-009",
        "risk_name": "Market repricing of high-emission collateral",
        "risk_category": "transition_market",
        "risk_owner_function": "Market Risk",
        "base_likelihood": 3,
        "base_severity": 4,
        "climate_risk_driver": "collateral_repricing",
        "time_horizon": "medium_term",
    },
    {
        "risk_id": "RISK-010",
        "risk_name": "Client transition plan credibility risk",
        "risk_category": "transition_market",
        "risk_owner_function": "Relationship Banking",
        "base_likelihood": 4,
        "base_severity": 3,
        "climate_risk_driver": "transition_plan_credibility",
        "time_horizon": "medium_term",
    },
    {
        "risk_id": "RISK-011",
        "risk_name": "Supply chain - Scope 3 data gaps",
        "risk_category": "governance",
        "risk_owner_function": "Sustainability Office",
        "base_likelihood": 4,
        "base_severity": 3,
        "climate_risk_driver": "scope3_data_gap",
        "time_horizon": "medium_term",
    },
    {
        "risk_id": "RISK-012",
        "risk_name": "ESG data quality and lineage weakness",
        "risk_category": "governance",
        "risk_owner_function": "Data Governance",
        "base_likelihood": 4,
        "base_severity": 4,
        "climate_risk_driver": "data_quality_lineage",
        "time_horizon": "short_term",
    },
    {
        "risk_id": "RISK-013",
        "risk_name": "Board climate competence gap",
        "risk_category": "governance",
        "risk_owner_function": "Board Secretariat",
        "base_likelihood": 3,
        "base_severity": 3,
        "climate_risk_driver": "board_competence",
        "time_horizon": "short_term",
    },
    {
        "risk_id": "RISK-014",
        "risk_name": "Customer vulnerability and financial inclusion risk",
        "risk_category": "social",
        "risk_owner_function": "Retail Banking",
        "base_likelihood": 3,
        "base_severity": 3,
        "climate_risk_driver": "customer_vulnerability",
        "time_horizon": "medium_term",
    },
    {
        "risk_id": "RISK-015",
        "risk_name": "Workforce sustainability skills shortage",
        "risk_category": "social",
        "risk_owner_function": "Human Resources",
        "base_likelihood": 3,
        "base_severity": 3,
        "climate_risk_driver": "workforce_skills",
        "time_horizon": "short_term",
    },
]

impact_mu_by_severity = {
    1: np.log(1_000_000),
    2: np.log(5_000_000),
    3: np.log(20_000_000),
    4: np.log(80_000_000),
    5: np.log(300_000_000),
}

# =========================================================
# GENERATE ERM RECORDS
# =========================================================
rows = []

for risk in risk_catalogue:
    previous_likelihood = risk["base_likelihood"]
    previous_severity = risk["base_severity"]

    for year in years:
        yrs_since_base = year - 2019

        # -----------------------------
        # Pick linked exposure
        # -----------------------------
        linked_facility_id = None
        linked_counterparty_id = None
        linked_collateral_id = None
        linked_pcaf_asset_class = None
        linked_nace_code = None
        exposure_at_risk_eur = None
        geo_id = None
        country_code = None
        postcode = None
        geography_reference = None
        linkage_source = None

        if risk["risk_category"].startswith("physical"):
            exposure = choose_physical_exposure(
                risk["risk_category"],
                risk["risk_name"]
            )

            if exposure is not None:
                linked_facility_id = exposure.get("facility_id")
                linked_counterparty_id = exposure.get("counterparty_id")
                linked_collateral_id = exposure.get("collateral_id")
                linked_pcaf_asset_class = exposure.get("pcaf_asset_class")
                linked_nace_code = exposure.get("nace_code")
                country_code = exposure.get("risk_country_code")

                allocated_balance = float(
                    exposure.get("allocated_outstanding_balance_eur", 0)
                )

                geo_ref = get_geo_reference(country_code, risk["risk_category"])
                geo_id = geo_ref.get("geo_id")
                postcode = geo_ref.get("postcode") if "postcode" in geo_ref.index else None

                city = geo_ref.get("city") if "city" in geo_ref.index else None
                geo_country = geo_ref.get("country_code")

                if city is not None and postcode is not None:
                    geography_reference = f"{city}, {geo_country} ({postcode})"
                else:
                    geography_reference = str(geo_country)

                hazard_score = get_geo_score(geo_ref, risk["risk_category"])

                exposure_at_risk_eur = allocated_balance * np.clip(
                    hazard_score / 10,
                    0.10,
                    1.00
                )

                linkage_source = "collateral_register + geo_risk_db"

            else:
                owner_entity = entities.iloc[int(rng.integers(0, len(entities)))]
                country_code = owner_entity["country_code"]
                exposure_at_risk_eur = rng.lognormal(np.log(10_000_000), 0.6)
                linkage_source = "entity_level_fallback"

        elif risk["risk_category"] in ["transition_policy", "transition_market", "governance"]:
            exposure = choose_transition_exposure(risk["risk_name"])

            if exposure is not None:
                linked_facility_id = exposure.get("facility_id")
                linked_counterparty_id = exposure.get("counterparty_id")
                linked_pcaf_asset_class = exposure.get("pcaf_asset_class")
                linked_nace_code = exposure.get("nace_code")
                country_code = exposure.get("risk_country_code")
                exposure_at_risk_eur = float(exposure.get("outstanding_balance_eur", 0))
                linkage_source = "loan_book + counterparty_master"

            else:
                owner_entity = entities.iloc[int(rng.integers(0, len(entities)))]
                country_code = owner_entity["country_code"]
                exposure_at_risk_eur = rng.lognormal(np.log(20_000_000), 0.7)
                linkage_source = "entity_level_fallback"

        else:
            owner_entity = entities.iloc[int(rng.integers(0, len(entities)))]
            country_code = owner_entity["country_code"]

            entity_loans = loan_book[
                loan_book["entity_id"].eq(owner_entity["entity_id"])
            ]

            if entity_loans.empty:
                exposure_at_risk_eur = rng.lognormal(np.log(5_000_000), 0.5)
            else:
                exposure_at_risk_eur = (
                    entity_loans["outstanding_balance_eur"].sum()
                    * rng.uniform(0.01, 0.05)
                )

            linkage_source = "entity_master + portfolio_exposure"

        # -----------------------------
        # Assign owner entity
        # -----------------------------
        if linked_facility_id is not None:
            matched_loan = loan_book[
                loan_book["facility_id"].eq(linked_facility_id)
            ]

            if not matched_loan.empty:
                owner_entity_id = matched_loan["entity_id"].iloc[0]
                owner_entity = entities[
                    entities["entity_id"].eq(owner_entity_id)
                ]

                if owner_entity.empty:
                    owner_entity = entities.iloc[[int(rng.integers(0, len(entities)))]]
            else:
                owner_entity = entities.iloc[[int(rng.integers(0, len(entities)))]]
        else:
            owner_entity = entities.iloc[[int(rng.integers(0, len(entities)))]]

        owner_entity = owner_entity.iloc[0]

        # -----------------------------
        # Risk scoring
        # -----------------------------
        if risk["risk_category"] in ["transition_policy", "transition_market"]:
            likelihood_drift = 0.10 * yrs_since_base
        elif risk["risk_category"].startswith("physical"):
            likelihood_drift = 0.07 * yrs_since_base
        else:
            likelihood_drift = 0.03 * yrs_since_base

        likelihood_score = clip_score(
            previous_likelihood
            + likelihood_drift
            + rng.normal(0, 0.35)
        )

        severity_score = clip_score(
            previous_severity
            + rng.normal(0, 0.25)
        )

        likelihood_score = max(likelihood_score, 2)
        severity_score = max(severity_score, 2)

        risk_rating_score = likelihood_score * severity_score
        risk_rating = rating_from_score(risk_rating_score)

        base_financial_impact = rng.lognormal(
            mean=impact_mu_by_severity[severity_score],
            sigma=0.50
        )

        # Tie financial impact to exposure at risk
        financial_impact_eur = min(
            base_financial_impact,
            float(exposure_at_risk_eur) * rng.uniform(0.05, 0.45)
        )

        # ERM integration probability depends on rating
        if risk_rating in ["critical", "high"]:
            erm_integrated_flag = rng.random() < 0.95
        elif risk_rating == "medium":
            erm_integrated_flag = rng.random() < 0.60
        else:
            erm_integrated_flag = rng.random() < 0.15

        mitigation_status = rng.choice(
            ["not_started", "in_progress", "implemented", "monitored"],
            p=[0.10, 0.45, 0.30, 0.15]
        )

        control_effectiveness = rng.choice(
            ["weak", "moderate", "strong"],
            p=[0.18, 0.55, 0.27]
        )

        residual_score_adjustment = {
            "weak": 0,
            "moderate": -2,
            "strong": -4,
        }[control_effectiveness]

        residual_risk_score = int(
            np.clip(
                risk_rating_score + residual_score_adjustment,
                1,
                25
            )
        )

        residual_risk_rating = rating_from_score(residual_risk_score)

        rows.append({
            "erm_record_id": f"ERM-{risk['risk_id']}-{year}",
            "risk_id": risk["risk_id"],
            "risk_name": risk["risk_name"],
            "risk_category": risk["risk_category"],
            "climate_risk_driver": risk["climate_risk_driver"],
            "time_horizon": risk["time_horizon"],

            "reporting_year": year,
            "entity_id": owner_entity["entity_id"],
            "risk_owner_function": risk["risk_owner_function"],

            "facility_id": linked_facility_id,
            "counterparty_id": linked_counterparty_id,
            "collateral_id": linked_collateral_id,
            "pcaf_asset_class": linked_pcaf_asset_class,
            "nace_code": linked_nace_code,

            "exposure_at_risk_eur": round(float(exposure_at_risk_eur), 2),

            "likelihood_score": likelihood_score,
            "severity_score": severity_score,
            "risk_rating_score": risk_rating_score,
            "risk_rating": risk_rating,

            "financial_impact_eur": round(float(financial_impact_eur), 2),

            "erm_integrated_flag": bool(erm_integrated_flag),
            "mitigation_status": mitigation_status,
            "control_effectiveness": control_effectiveness,
            "residual_risk_score": residual_risk_score,
            "residual_risk_rating": residual_risk_rating,

            "geo_id": geo_id,
            "country_code": country_code,
            "postcode": postcode,
            "geography_reference": geography_reference,

            "linkage_source": linkage_source,
            "data_source": "synthetic_erm_risk_register",
            "created_from": "synthetic_erm_system_generation_v2_core_tables_aligned",
        })

erm_system = pd.DataFrame(rows)

# =========================================================
# VALIDATION
# =========================================================
expected_rating = erm_system["risk_rating_score"].apply(rating_from_score)
physical_rows = erm_system["risk_category"].str.startswith("physical")

valid_entity_ids = set(entity_master["entity_id"].astype(str))
valid_facility_ids = set(loan_book["facility_id"].astype(str))
valid_counterparty_ids = set(counterparty_master["counterparty_id"].astype(str))
valid_collateral_ids = set(collateral_register["collateral_id"].astype(str))
valid_geo_ids = set(geo_risk_db["geo_id"].astype(str))

validation = {
    "rows": len(erm_system),
    "risks_covered": erm_system["risk_id"].nunique(),
    "years_covered": sorted(erm_system["reporting_year"].unique().tolist()),
    "unique_erm_record_id": int(erm_system["erm_record_id"].is_unique),

    "entity_id_missing_from_entity_master": int(
        (~erm_system["entity_id"].astype(str).isin(valid_entity_ids)).sum()
    ),

    "facility_id_missing_from_loan_book": int(
        (
            erm_system["facility_id"].notna()
            & ~erm_system["facility_id"].astype(str).isin(valid_facility_ids)
        ).sum()
    ),

    "counterparty_id_missing_from_counterparty_master": int(
        (
            erm_system["counterparty_id"].notna()
            & ~erm_system["counterparty_id"].astype(str).isin(valid_counterparty_ids)
        ).sum()
    ),

    "collateral_id_missing_from_collateral_register": int(
        (
            erm_system["collateral_id"].notna()
            & ~erm_system["collateral_id"].astype(str).isin(valid_collateral_ids)
        ).sum()
    ),

    "score_outside_1_5": int(
        (
            (erm_system["likelihood_score"] < 1)
            | (erm_system["likelihood_score"] > 5)
            | (erm_system["severity_score"] < 1)
            | (erm_system["severity_score"] > 5)
        ).sum()
    ),

    "risk_rating_not_likelihood_x_severity": int(
        (
            erm_system["risk_rating_score"]
            != erm_system["likelihood_score"] * erm_system["severity_score"]
        ).sum()
    ),

    "wrong_risk_rating_label": int(
        (erm_system["risk_rating"] != expected_rating).sum()
    ),

    "non_positive_financial_impact": int(
        (erm_system["financial_impact_eur"] <= 0).sum()
    ),

    "non_positive_exposure_at_risk": int(
        (erm_system["exposure_at_risk_eur"] <= 0).sum()
    ),

    "physical_without_collateral_reference": int(
        (
            physical_rows
            & erm_system["collateral_id"].isna()
        ).sum()
    ),

    "physical_without_geo_reference": int(
        (
            physical_rows
            & erm_system["geo_id"].isna()
        ).sum()
    ),

    "geo_id_missing_from_geo_risk_db": int(
        (
            erm_system["geo_id"].notna()
            & ~erm_system["geo_id"].astype(str).isin(valid_geo_ids)
        ).sum()
    ),

    "transition_without_facility_reference": int(
        (
            erm_system["risk_category"].isin(["transition_policy", "transition_market"])
            & erm_system["facility_id"].isna()
        ).sum()
    ),

    "duplicate_risk_per_year": int(
        erm_system.duplicated(["risk_id", "reporting_year"]).sum()
    ),
}

# =========================================================
# SAVE
# =========================================================
erm_system.to_csv(OUTPUT_PATH, index=False)

print(f"Generated: {OUTPUT_PATH}")

print("\nValidation:")
for key, value in validation.items():
    print(f"{key}: {value}")

print("\nPreview:")
print(erm_system.head(12))

Generated: Data\erm_system_raw.csv

Validation:
rows: 90
risks_covered: 15
years_covered: [2019, 2020, 2021, 2022, 2023, 2024]
unique_erm_record_id: 1
entity_id_missing_from_entity_master: 0
facility_id_missing_from_loan_book: 0
counterparty_id_missing_from_counterparty_master: 0
collateral_id_missing_from_collateral_register: 0
score_outside_1_5: 0
risk_rating_not_likelihood_x_severity: 0
wrong_risk_rating_label: 0
non_positive_financial_impact: 0
non_positive_exposure_at_risk: 0
physical_without_collateral_reference: 0
physical_without_geo_reference: 0
geo_id_missing_from_geo_risk_db: 0
transition_without_facility_reference: 0
duplicate_risk_per_year: 0

Preview:
        erm_record_id   risk_id                         risk_name  \
0   ERM-RISK-001-2019  RISK-001        Flood risk - mortgage book
1   ERM-RISK-001-2020  RISK-001        Flood risk - mortgage book
2   ERM-RISK-001-2021  RISK-001        Flood risk - mortgage book
3   ERM-RISK-001-2022  RISK-001        Flood risk - mortgage book
4   ERM-RISK-001-2023  RISK-001        Flood risk - mortgage book
5   ERM-RISK-001-2024  RISK-001        Flood risk - mortgage book
6   ERM-RISK-002-2019  RISK-002  Storm surge - coastal collateral
7   ERM-RISK-002-2020  RISK-002  Storm surge - coastal collateral
8   ERM-RISK-002-2021  RISK-002  Storm surge - coastal collateral
9   ERM-RISK-002-2022  RISK-002  Storm surge - coastal collateral
10  ERM-RISK-002-2023  RISK-002  Storm surge - coastal collateral
11  ERM-RISK-002-2024  RISK-002  Storm surge - coastal collateral

     risk_category climate_risk_driver time_horizon  reporting_year  \
0   physical_acute               flood   short_term            2019
1   physical_acute               flood   short_term            2020
2   physical_acute               flood   short_term            2021
3   physical_acute               flood   short_term            2022
4   physical_acute               flood   short_term            2023
5   physical_acute               flood   short_term            2024
6   physical_acute         storm_surge   short_term            2019
7   physical_acute         storm_surge   short_term            2020
8   physical_acute         storm_surge   short_term            2021
9   physical_acute         storm_surge   short_term            2022
10  physical_acute         storm_surge   short_term            2023
11  physical_acute         storm_surge   short_term            2024

        entity_id risk_owner_function  facility_id  ... control_effectiveness  \
0      ENT-DE-003         Credit Risk  FAC-0047197  ...                strong
1      ENT-DE-003         Credit Risk  FAC-0025288  ...              moderate
2      ENT-DE-003         Credit Risk  FAC-0008406  ...                strong
3      ENT-IT-007         Credit Risk  FAC-0040986  ...              moderate
4   ENT-GROUP-001         Credit Risk  FAC-0043611  ...              moderate
5      ENT-LU-009         Credit Risk  FAC-0002644  ...                strong
6      ENT-NL-004         Credit Risk  FAC-0039006  ...                strong
7      ENT-IT-007         Credit Risk  FAC-0042781  ...                  weak
8      ENT-ES-006         Credit Risk  FAC-0037104  ...              moderate
9      ENT-UK-005         Credit Risk  FAC-0042688  ...                  weak
10     ENT-FR-002         Credit Risk  FAC-0042705  ...                strong
11     ENT-US-010         Credit Risk  FAC-0009584  ...              moderate

   residual_risk_score residual_risk_rating        geo_id  country_code  \
0                    8               medium  GEO-DE-00066            DE
1                   10               medium  GEO-NL-00466            NL
2                    8               medium  GEO-ES-00161            ES
3                   10               medium  GEO-ES-00161            ES
4                   10               medium  GEO-LU-00425            LU
5                    8               medium  GEO-GB-00327            GB
6                    8               medium  GEO-DE-00066            DE
7                   12               medium  GEO-ES-00161            ES
8                   10               medium  GEO-NL-00466            NL
9                   12               medium  GEO-NL-00466            NL
10                   8               medium  GEO-ES-00161            ES
11                  10               medium  GEO-LU-00425            LU

    postcode  geography_reference                     linkage_source  \
0   20095-06                   DE  collateral_register + geo_risk_db
1    2511-01                   NL  collateral_register + geo_risk_db
2   08001-11                   ES  collateral_register + geo_risk_db
3   08001-11                   ES  collateral_register + geo_risk_db
4     L-4004                   LU  collateral_register + geo_risk_db
5    L1 12AA                   GB  collateral_register + geo_risk_db
6   20095-06                   DE  collateral_register + geo_risk_db
7   08001-11                   ES  collateral_register + geo_risk_db
8    2511-01                   NL  collateral_register + geo_risk_db
9    2511-01                   NL  collateral_register + geo_risk_db
10  08001-11                   ES  collateral_register + geo_risk_db
11    L-4004                   LU  collateral_register + geo_risk_db

                    data_source  \
0   synthetic_erm_risk_register
1   synthetic_erm_risk_register
2   synthetic_erm_risk_register
3   synthetic_erm_risk_register
4   synthetic_erm_risk_register
5   synthetic_erm_risk_register
6   synthetic_erm_risk_register
7   synthetic_erm_risk_register
8   synthetic_erm_risk_register
9   synthetic_erm_risk_register
10  synthetic_erm_risk_register
11  synthetic_erm_risk_register

                                         created_from
0   synthetic_erm_system_generation_v2_core_tables...
1   synthetic_erm_system_generation_v2_core_tables...
2   synthetic_erm_system_generation_v2_core_tables...
3   synthetic_erm_system_generation_v2_core_tables...
4   synthetic_erm_system_generation_v2_core_tables...
5   synthetic_erm_system_generation_v2_core_tables...
6   synthetic_erm_system_generation_v2_core_tables...
7   synthetic_erm_system_generation_v2_core_tables...
8   synthetic_erm_system_generation_v2_core_tables...
9   synthetic_erm_system_generation_v2_core_tables...
10  synthetic_erm_system_generation_v2_core_tables...
11  synthetic_erm_system_generation_v2_core_tables...

[12 rows x 32 columns]

Board minutes : This feeds the IFRS S1 governance pillar requirement to describe how frequently the board discusses sustainability and what decisions it makes

In [13]:
import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# CONFIG
# =========================================================
rng = np.random.default_rng(42)

DATA_DIR = Path("Data")
OUTPUT_PATH = DATA_DIR / "board_minutes_raw.csv"

years = list(range(2019, 2025))

# =========================================================
# LOAD DEPENDENCIES
# =========================================================
entity_master = pd.read_csv(DATA_DIR / "entity_master_raw.csv")
esg_kpi_tracker = pd.read_csv(DATA_DIR / "esg_kpi_tracker_raw.csv")
erm_system = pd.read_csv(DATA_DIR / "erm_system_raw.csv")

# Optional dependency
hr_path = DATA_DIR / "hr_system_raw.csv"
hr_system = pd.read_csv(hr_path) if hr_path.exists() else None

# Clean columns
for df in [entity_master, esg_kpi_tracker, erm_system]:
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

if hr_system is not None:
    hr_system.columns = (
        hr_system.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

# =========================================================
# REQUIRED COLUMN CHECKS
# =========================================================
required_entity_cols = [
    "entity_id",
    "legal_name",
    "country_code",
    "in_scope_esg_flag",
]

required_kpi_cols = [
    "kpi_code",
    "kpi_name",
    "category",
    "reporting_year",
]

required_erm_cols = [
    "risk_id",
    "risk_name",
    "risk_category",
    "risk_owner_function",
    "reporting_year",
]

missing_entity_cols = [c for c in required_entity_cols if c not in entity_master.columns]
missing_kpi_cols = [c for c in required_kpi_cols if c not in esg_kpi_tracker.columns]
missing_erm_cols = [c for c in required_erm_cols if c not in erm_system.columns]

if missing_entity_cols:
    raise ValueError(f"entity_master is missing columns: {missing_entity_cols}")

if missing_kpi_cols:
    raise ValueError(f"esg_kpi_tracker is missing columns: {missing_kpi_cols}")

if missing_erm_cols:
    raise ValueError(f"erm_system is missing columns: {missing_erm_cols}")

# =========================================================
# FILTER IN-SCOPE ENTITIES
# =========================================================
entity_master["in_scope_esg_flag"] = (
    entity_master["in_scope_esg_flag"]
    .astype(str)
    .str.lower()
    .isin(["true", "1", "yes"])
)

entities = (
    entity_master.loc[
        entity_master["in_scope_esg_flag"].eq(True),
        ["entity_id", "legal_name", "country_code"]
    ]
    .dropna(subset=["entity_id", "country_code"])
    .drop_duplicates()
    .reset_index(drop=True)
)

if entities.empty:
    raise ValueError("No in-scope ESG entities found in entity_master_raw.csv")

# =========================================================
# PREPARE KPI AND ERM REFERENCES
# =========================================================
kpi_ref = (
    esg_kpi_tracker[
        ["kpi_code", "kpi_name", "category", "reporting_year"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

erm_ref = (
    erm_system[
        [
            "risk_id",
            "risk_name",
            "risk_category",
            "risk_owner_function",
            "reporting_year",
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

# Useful KPI groups
climate_kpis = kpi_ref[
    kpi_ref["category"].isin([
        "Climate",
        "Financed emissions",
        "Climate risk",
        "Climate targets",
        "Portfolio",
        "Data quality",
    ])
].copy()

governance_kpis = kpi_ref[
    kpi_ref["category"].isin(["Governance", "Data quality"])
].copy()

social_kpis = kpi_ref[
    kpi_ref["category"].isin(["Social"])
].copy()

if climate_kpis.empty:
    climate_kpis = kpi_ref.copy()

# =========================================================
# TOPIC CONFIGURATION
# =========================================================
topics = [
    "Net-zero target progress review",
    "IFRS S2 climate disclosure approval",
    "Green bond framework update",
    "Climate scenario analysis review",
    "ESG remuneration KPI setting",
    "Supplier ESG policy update",
    "Financed emissions methodology review",
    "Physical risk exposure review",
    "Transition risk appetite approval",
    "Annual sustainability report sign-off",
    "PCAF data quality remediation",
    "Climate risk model validation",
    "Sovereign bond financed emissions review",
    "Project finance emissions methodology review",
    "Real estate collateral emissions review",
    "Motor vehicle portfolio emissions review",
]

topic_to_kpi_category = {
    "Net-zero target progress review": ["Climate", "Climate targets"],
    "IFRS S2 climate disclosure approval": ["Climate", "Financed emissions", "Climate risk"],
    "Green bond framework update": ["Portfolio", "Climate"],
    "Climate scenario analysis review": ["Climate risk"],
    "ESG remuneration KPI setting": ["Governance", "Climate targets"],
    "Supplier ESG policy update": ["Social", "Governance"],
    "Financed emissions methodology review": ["Financed emissions", "Data quality"],
    "Physical risk exposure review": ["Climate risk", "Portfolio"],
    "Transition risk appetite approval": ["Climate risk", "Portfolio"],
    "Annual sustainability report sign-off": ["Climate", "Financed emissions", "Governance"],
    "PCAF data quality remediation": ["Data quality", "Financed emissions"],
    "Climate risk model validation": ["Climate risk", "Data quality"],
    "Sovereign bond financed emissions review": ["Portfolio", "Financed emissions"],
    "Project finance emissions methodology review": ["Portfolio", "Financed emissions"],
    "Real estate collateral emissions review": ["Portfolio", "Financed emissions"],
    "Motor vehicle portfolio emissions review": ["Portfolio", "Financed emissions"],
}

topic_to_risk_category = {
    "Physical risk exposure review": ["physical_acute", "physical_chronic"],
    "Transition risk appetite approval": ["transition_policy", "transition_market"],
    "Climate scenario analysis review": ["physical_acute", "physical_chronic", "transition_policy", "transition_market"],
    "Climate risk model validation": ["governance", "transition_policy", "transition_market"],
    "IFRS S2 climate disclosure approval": ["governance", "transition_policy"],
    "PCAF data quality remediation": ["governance"],
    "Financed emissions methodology review": ["governance", "transition_policy"],
    "Real estate collateral emissions review": ["physical_acute", "physical_chronic", "transition_market"],
    "Sovereign bond financed emissions review": ["transition_policy", "governance"],
    "Project finance emissions methodology review": ["transition_policy", "transition_market"],
    "Motor vehicle portfolio emissions review": ["transition_policy"],
}

owner_functions = [
    "Sustainability Office",
    "Risk Management",
    "Credit Risk",
    "Finance",
    "Compliance",
    "Internal Audit",
    "Board Secretariat",
    "Data Governance",
    "Human Resources",
]

action_statuses = [
    "not_started",
    "in_progress",
    "completed",
    "deferred",
    "monitored",
]

# =========================================================
# HELPER FUNCTIONS
# =========================================================
def adjust_to_weekday(date):
    while date.weekday() > 4:
        date = date - pd.Timedelta(days=1)
    return date


def pick_kpi_for_topic(topic, year):
    categories = topic_to_kpi_category.get(topic, [])

    pool = kpi_ref[
        kpi_ref["reporting_year"].eq(year)
        & kpi_ref["category"].isin(categories)
    ].copy()

    if pool.empty:
        pool = kpi_ref[kpi_ref["reporting_year"].eq(year)].copy()

    if pool.empty:
        pool = kpi_ref.copy()

    selected = pool.sample(
        n=1,
        random_state=int(rng.integers(1, 1_000_000))
    ).iloc[0]

    return selected["kpi_code"], selected["kpi_name"]


def pick_risk_for_topic(topic, year):
    risk_categories = topic_to_risk_category.get(topic, [])

    if not risk_categories:
        return None, None, None

    pool = erm_ref[
        erm_ref["reporting_year"].eq(year)
        & erm_ref["risk_category"].isin(risk_categories)
    ].copy()

    if pool.empty:
        pool = erm_ref[
            erm_ref["reporting_year"].eq(year)
        ].copy()

    if pool.empty:
        pool = erm_ref.copy()

    selected = pool.sample(
        n=1,
        random_state=int(rng.integers(1, 1_000_000))
    ).iloc[0]

    return (
        selected["risk_id"],
        selected["risk_name"],
        selected["risk_owner_function"],
    )


def make_action_due_date(meeting_date):
    return (
        pd.Timestamp(meeting_date)
        + pd.Timedelta(days=int(rng.integers(30, 181)))
    ).date()


def make_decision_summary(topic, decision_made_flag, linked_kpi_code, linked_risk_id):
    if not topic:
        return None

    if decision_made_flag:
        details = [f"Decision recorded: {topic}"]

        if linked_kpi_code:
            details.append(f"linked KPI {linked_kpi_code}")

        if linked_risk_id:
            details.append(f"linked risk {linked_risk_id}")

        return " | ".join(details)

    return f"Discussion only; no formal decision recorded for {topic}"


# =========================================================
# GENERATE BOARD MINUTES
# =========================================================
rows = []
meeting_counter = 1

for _, entity in entities.iterrows():
    for year in years:

        # -------------------------------------------------
        # Quarterly full board meetings
        # -------------------------------------------------
        for month in [1, 4, 7, 10]:
            offset = int(rng.integers(-10, 11))
            meeting_date = adjust_to_weekday(
                pd.Timestamp(year, month, 15) + pd.Timedelta(days=offset)
            )

            esg_agenda_flag = bool(rng.random() < 0.78)
            decision_made_flag = bool(esg_agenda_flag and (rng.random() < 0.52))

            if month == 1:
                # Make sure annual sign-off exists for every entity and every year
                esg_agenda_flag = True
                decision_made_flag = True
                topic = "Annual sustainability report sign-off"
            else:
                topic = rng.choice(topics) if esg_agenda_flag else None

            linked_kpi_code = None
            linked_kpi_name = None
            linked_erm_risk_id = None
            linked_erm_risk_name = None
            action_owner_function = None

            if topic:
                linked_kpi_code, linked_kpi_name = pick_kpi_for_topic(topic, year)
                (
                    linked_erm_risk_id,
                    linked_erm_risk_name,
                    risk_owner_function,
                ) = pick_risk_for_topic(topic, year)

                action_owner_function = (
                    risk_owner_function
                    if risk_owner_function is not None
                    else rng.choice(owner_functions)
                )

            action_due_date = (
                make_action_due_date(meeting_date)
                if esg_agenda_flag and decision_made_flag
                else pd.NaT
            )

            action_status = (
                rng.choice(action_statuses, p=[0.08, 0.38, 0.34, 0.08, 0.12])
                if esg_agenda_flag and decision_made_flag
                else None
            )

            board_size = int(rng.integers(9, 13))
            members_present = max(1, min(board_size, int(rng.binomial(board_size, 0.88))))
            attendance_rate = round(members_present / board_size * 100, 1)

            rows.append({
                "meeting_id": f"MTG-{meeting_counter:06d}",
                "entity_id": entity["entity_id"],
                "entity_legal_name": entity["legal_name"],
                "country_code": entity["country_code"],

                "committee_name": "Board of Directors",
                "meeting_type": "full_board",
                "meeting_date": meeting_date.strftime("%Y-%m-%d"),
                "reporting_year": year,

                "board_size": board_size,
                "members_present": members_present,
                "attendance_rate_pct": attendance_rate,

                "esg_agenda_flag": esg_agenda_flag,
                "decision_made_flag": decision_made_flag,
                "esg_topics_discussed": topic,

                "linked_kpi_code": linked_kpi_code,
                "linked_kpi_name": linked_kpi_name,
                "linked_erm_risk_id": linked_erm_risk_id,
                "linked_erm_risk_name": linked_erm_risk_name,

                "decision_summary": make_decision_summary(
                    topic,
                    decision_made_flag,
                    linked_kpi_code,
                    linked_erm_risk_id,
                ),

                "action_owner_function": action_owner_function,
                "action_due_date": action_due_date,
                "action_status": action_status,

                "minutes_status": rng.choice(
                    ["approved", "draft", "pending_review"],
                    p=[0.82, 0.10, 0.08]
                ),

                "data_source": "synthetic_board_minutes_schedule",
                "created_from": "synthetic_board_minutes_generation_v2_core_tables_aligned",
            })

            meeting_counter += 1

        # -------------------------------------------------
        # ESG committee meetings
        # -------------------------------------------------
        for month in [3, 6, 9, 12]:
            offset = int(rng.integers(-7, 8))
            meeting_date = adjust_to_weekday(
                pd.Timestamp(year, month, 15) + pd.Timedelta(days=offset)
            )

            topic_count = int(rng.integers(1, 4))
            selected_topics = rng.choice(
                topics,
                size=topic_count,
                replace=False
            ).tolist()

            decision_made_flag = bool(rng.random() < 0.65)

            primary_topic = selected_topics[0]

            linked_kpi_code, linked_kpi_name = pick_kpi_for_topic(primary_topic, year)

            (
                linked_erm_risk_id,
                linked_erm_risk_name,
                risk_owner_function,
            ) = pick_risk_for_topic(primary_topic, year)

            action_owner_function = (
                risk_owner_function
                if risk_owner_function is not None
                else rng.choice(owner_functions)
            )

            action_due_date = (
                make_action_due_date(meeting_date)
                if decision_made_flag
                else pd.NaT
            )

            action_status = (
                rng.choice(action_statuses, p=[0.06, 0.42, 0.32, 0.06, 0.14])
                if decision_made_flag
                else "monitored"
            )

            board_size = int(rng.integers(7, 10))
            members_present = max(1, min(board_size, int(rng.binomial(board_size, 0.90))))
            attendance_rate = round(members_present / board_size * 100, 1)

            rows.append({
                "meeting_id": f"MTG-{meeting_counter:06d}",
                "entity_id": entity["entity_id"],
                "entity_legal_name": entity["legal_name"],
                "country_code": entity["country_code"],

                "committee_name": "Board ESG & Sustainability Committee",
                "meeting_type": "esg_committee",
                "meeting_date": meeting_date.strftime("%Y-%m-%d"),
                "reporting_year": year,

                "board_size": board_size,
                "members_present": members_present,
                "attendance_rate_pct": attendance_rate,

                "esg_agenda_flag": True,
                "decision_made_flag": decision_made_flag,
                "esg_topics_discussed": "; ".join(selected_topics),

                "linked_kpi_code": linked_kpi_code,
                "linked_kpi_name": linked_kpi_name,
                "linked_erm_risk_id": linked_erm_risk_id,
                "linked_erm_risk_name": linked_erm_risk_name,

                "decision_summary": make_decision_summary(
                    primary_topic,
                    decision_made_flag,
                    linked_kpi_code,
                    linked_erm_risk_id,
                ) if decision_made_flag else "Committee review completed; action items assigned",

                "action_owner_function": action_owner_function,
                "action_due_date": action_due_date,
                "action_status": action_status,

                "minutes_status": rng.choice(
                    ["approved", "draft", "pending_review"],
                    p=[0.86, 0.08, 0.06]
                ),

                "data_source": "synthetic_board_minutes_schedule",
                "created_from": "synthetic_board_minutes_generation_v2_core_tables_aligned",
            })

            meeting_counter += 1

board_minutes = pd.DataFrame(rows)

# =========================================================
# VALIDATION
# =========================================================
meeting_dates = pd.to_datetime(board_minutes["meeting_date"])

valid_entity_ids = set(entity_master["entity_id"].astype(str))
valid_kpi_codes = set(esg_kpi_tracker["kpi_code"].astype(str).unique())
valid_erm_risk_ids = set(erm_system["risk_id"].astype(str).unique())

annual_signoff = board_minutes[
    board_minutes["esg_topics_discussed"]
    .fillna("")
    .str.contains("Annual sustainability report sign-off", regex=False)
]

validation = {
    "rows": len(board_minutes),
    "entities_covered": board_minutes["entity_id"].nunique(),
    "years_covered": sorted(board_minutes["reporting_year"].unique().tolist()),
    "unique_meeting_id": int(board_minutes["meeting_id"].is_unique),

    "entity_id_missing_from_entity_master": int(
        (~board_minutes["entity_id"].astype(str).isin(valid_entity_ids)).sum()
    ),

    "weekend_meetings": int(
        (meeting_dates.dt.weekday > 4).sum()
    ),

    "decision_without_esg_agenda": int(
        (
            board_minutes["decision_made_flag"].eq(True)
            & board_minutes["esg_agenda_flag"].eq(False)
        ).sum()
    ),

    "esg_committee_without_esg_agenda": int(
        (
            board_minutes["meeting_type"].eq("esg_committee")
            & board_minutes["esg_agenda_flag"].eq(False)
        ).sum()
    ),

    "attendance_over_100": int(
        (board_minutes["attendance_rate_pct"] > 100).sum()
    ),

    "members_present_greater_than_board_size": int(
        (board_minutes["members_present"] > board_minutes["board_size"]).sum()
    ),

    "missing_annual_signoff_year_entity": int(
        len(entities) * len(years)
        - annual_signoff.groupby(["entity_id", "reporting_year"]).size().count()
    ),

    "invalid_linked_kpi_code": int(
        (
            board_minutes["linked_kpi_code"].notna()
            & ~board_minutes["linked_kpi_code"].astype(str).isin(valid_kpi_codes)
        ).sum()
    ),

    "invalid_linked_erm_risk_id": int(
        (
            board_minutes["linked_erm_risk_id"].notna()
            & ~board_minutes["linked_erm_risk_id"].astype(str).isin(valid_erm_risk_ids)
        ).sum()
    ),

    "esg_agenda_without_topic": int(
        (
            board_minutes["esg_agenda_flag"].eq(True)
            & board_minutes["esg_topics_discussed"].isna()
        ).sum()
    ),

    "decision_without_action_owner": int(
        (
            board_minutes["decision_made_flag"].eq(True)
            & board_minutes["action_owner_function"].isna()
        ).sum()
    ),

    "decision_without_action_due_date": int(
        (
            board_minutes["decision_made_flag"].eq(True)
            & board_minutes["action_due_date"].isna()
        ).sum()
    ),
}

# =========================================================
# SAVE
# =========================================================
board_minutes.to_csv(OUTPUT_PATH, index=False)

print(f"Generated: {OUTPUT_PATH}")

print("\nValidation:")
for key, value in validation.items():
    print(f"{key}: {value}")

print("\nPreview:")
print(board_minutes.head(12))

Generated: Data\board_minutes_raw.csv

Validation:
rows: 480
entities_covered: 10
years_covered: [2019, 2020, 2021, 2022, 2023, 2024]
unique_meeting_id: 1
entity_id_missing_from_entity_master: 0
weekend_meetings: 0
decision_without_esg_agenda: 0
esg_committee_without_esg_agenda: 0
attendance_over_100: 0
members_present_greater_than_board_size: 0
missing_annual_signoff_year_entity: 0
invalid_linked_kpi_code: 0
invalid_linked_erm_risk_id: 0
esg_agenda_without_topic: 0
decision_without_action_owner: 0
decision_without_action_due_date: 0

Preview:
    meeting_id      entity_id       entity_legal_name country_code  \
0   MTG-000001  ENT-GROUP-001  Atlas Banking Group SA           FR
1   MTG-000002  ENT-GROUP-001  Atlas Banking Group SA           FR
2   MTG-000003  ENT-GROUP-001  Atlas Banking Group SA           FR
3   MTG-000004  ENT-GROUP-001  Atlas Banking Group SA           FR
4   MTG-000005  ENT-GROUP-001  Atlas Banking Group SA           FR
5   MTG-000006  ENT-GROUP-001  Atlas Banking Group SA           FR
6   MTG-000007  ENT-GROUP-001  Atlas Banking Group SA           FR
7   MTG-000008  ENT-GROUP-001  Atlas Banking Group SA           FR
8   MTG-000009  ENT-GROUP-001  Atlas Banking Group SA           FR
9   MTG-000010  ENT-GROUP-001  Atlas Banking Group SA           FR
10  MTG-000011  ENT-GROUP-001  Atlas Banking Group SA           FR
11  MTG-000012  ENT-GROUP-001  Atlas Banking Group SA           FR

                          committee_name   meeting_type meeting_date  \
0                     Board of Directors     full_board   2019-01-04
1                     Board of Directors     full_board   2019-04-25
2                     Board of Directors     full_board   2019-07-22
3                     Board of Directors     full_board   2019-10-11
4   Board ESG & Sustainability Committee  esg_committee   2019-03-18
5   Board ESG & Sustainability Committee  esg_committee   2019-06-21
6   Board ESG & Sustainability Committee  esg_committee   2019-09-13
7   Board ESG & Sustainability Committee  esg_committee   2019-12-13
8                     Board of Directors     full_board   2020-01-17
9                     Board of Directors     full_board   2020-04-14
10                    Board of Directors     full_board   2020-07-09
11                    Board of Directors     full_board   2020-10-13

    reporting_year  board_size  members_present  ...  \
0             2019          11                9  ...
1             2019          10                9  ...
2             2019          11                7  ...
3             2019          11                9  ...
4             2019           7                7  ...
5             2019           9                9  ...
6             2019           8                7  ...
7             2019           8                7  ...
8             2020          10               10  ...
9             2020           9                9  ...
10            2020          12               10  ...
11            2020          11               11  ...

                        linked_kpi_name  linked_erm_risk_id  \
0   Financed emissions Scope 1, 2 and 3                 NaN
1               Sovereign bond exposure            RISK-010
2         High-emission sector exposure            RISK-006
3        Board meetings with ESG agenda                 NaN
4               Sovereign bond exposure            RISK-002
5                     Scope 1 emissions                 NaN
6      Financed emissions Scope 1 and 2            RISK-008
7                Motor vehicle exposure                 NaN
8                    Energy consumption                 NaN
9                                   NaN                 NaN
10                 Real estate exposure                 NaN
11             Project finance exposure            RISK-009

                            linked_erm_risk_name  \
0                                            NaN
1        Client transition plan credibility risk
2    Mandatory climate disclosure non-compliance
3                                            NaN
4               Storm surge - coastal collateral
5                                            NaN
6           Stranded assets - fossil fuel sector
7                                            NaN
8                                            NaN
9                                            NaN
10                                           NaN
11  Market repricing of high-emission collateral

                                     decision_summary  action_owner_function  \
0   Decision recorded: Annual sustainability repor...  Sustainability Office
1   Decision recorded: Transition risk appetite ap...   Relationship Banking
2   Decision recorded: Project finance emissions m...             Compliance
3   Decision recorded: Supplier ESG policy update ...             Compliance
4   Decision recorded: Real estate collateral emis...            Credit Risk
5   Decision recorded: Green bond framework update...      Board Secretariat
6   Decision recorded: Project finance emissions m...            Sector Risk
7   Committee review completed; action items assigned         Internal Audit
8   Decision recorded: Annual sustainability repor...        Data Governance
9                                                 NaN                    NaN
10  Discussion only; no formal decision recorded f...             Compliance
11  Decision recorded: Project finance emissions m...            Market Risk

   action_due_date action_status  minutes_status  \
0       2019-05-19   in_progress        approved
1       2019-10-11     completed        approved
2       2019-11-24     completed           draft
3       2019-11-16   in_progress  pending_review
4       2019-06-25   in_progress        approved
5       2019-11-23      deferred        approved
6       2020-02-07     completed        approved
7              NaT     monitored        approved
8       2020-04-01   not_started        approved
9              NaT           NaN        approved
10             NaT           NaN        approved
11      2021-03-08     completed        approved

                         data_source  \
0   synthetic_board_minutes_schedule
1   synthetic_board_minutes_schedule
2   synthetic_board_minutes_schedule
3   synthetic_board_minutes_schedule
4   synthetic_board_minutes_schedule
5   synthetic_board_minutes_schedule
6   synthetic_board_minutes_schedule
7   synthetic_board_minutes_schedule
8   synthetic_board_minutes_schedule
9   synthetic_board_minutes_schedule
10  synthetic_board_minutes_schedule
11  synthetic_board_minutes_schedule

                                         created_from
0   synthetic_board_minutes_generation_v2_core_tab...
1   synthetic_board_minutes_generation_v2_core_tab...
2   synthetic_board_minutes_generation_v2_core_tab...
3   synthetic_board_minutes_generation_v2_core_tab...
4   synthetic_board_minutes_generation_v2_core_tab...
5   synthetic_board_minutes_generation_v2_core_tab...
6   synthetic_board_minutes_generation_v2_core_tab...
7   synthetic_board_minutes_generation_v2_core_tab...
8   synthetic_board_minutes_generation_v2_core_tab...
9   synthetic_board_minutes_generation_v2_core_tab...
10  synthetic_board_minutes_generation_v2_core_tab...
11  synthetic_board_minutes_generation_v2_core_tab...

[12 rows x 25 columns]

In [5]:
import pandas as pd
from pathlib import Path

board_minutes = pd.read_csv(r"Data\board_minutes_raw.csv")

# Enforce the hard constraint: every entity/year has an annual sustainability report sign-off meeting in Q1.
mask = (board_minutes["meeting_type"] == "full_board") & (
    pd.to_datetime(board_minutes["meeting_date"]).dt.month.isin([1, 2, 3])
)

# The generated schedule has one Jan full-board meeting per entity/year, so use that as the sign-off meeting.
jan_board = board_minutes[mask].groupby(["entity_id", "reporting_year"]).head(1).index

board_minutes.loc[jan_board, "esg_agenda_flag"] = True
board_minutes.loc[jan_board, "decision_made_flag"] = True
board_minutes.loc[jan_board, "esg_topics_discussed"] = "Annual sustainability report sign-off"
board_minutes.loc[jan_board, "decision_summary"] = "Decision recorded: Annual sustainability report sign-off"
board_minutes.loc[jan_board, "minutes_status"] = "approved"

# Recalculate validation
meeting_dates = pd.to_datetime(board_minutes["meeting_date"])

signoff_pairs = (
    board_minutes[
        board_minutes["esg_topics_discussed"].fillna("").str.contains("Annual sustainability report sign-off")
    ]
    .groupby(["entity_id", "reporting_year"])
    .size()
)

validation = {
    "rows": len(board_minutes),
    "entities_covered": board_minutes["entity_id"].nunique(),
    "years_covered": sorted(board_minutes["reporting_year"].unique().tolist()),
    "unique_meeting_id": int(board_minutes["meeting_id"].is_unique),
    "weekend_meetings": int((meeting_dates.dt.weekday > 4).sum()),
    "decision_without_esg_agenda": int(((board_minutes["decision_made_flag"] == True) & (board_minutes["esg_agenda_flag"] == False)).sum()),
    "esg_committee_without_esg_agenda": int(((board_minutes["meeting_type"] == "esg_committee") & (board_minutes["esg_agenda_flag"] == False)).sum()),
    "attendance_over_100": int((board_minutes["attendance_rate_pct"] > 100).sum()),
    "missing_annual_signoff_year_entity": int(board_minutes["entity_id"].nunique() * board_minutes["reporting_year"].nunique() - signoff_pairs.count())
}

out_path = Path(r"Data\board_minutes_raw.csv")
board_minutes.to_csv(out_path, index=False)

print(f"Corrected and saved: {out_path}")
for k, v in validation.items():
    print(f"{k}: {v}")

board_minutes.head(12)

Corrected and saved: Data\board_minutes_raw.csv
rows: 480
entities_covered: 10
years_covered: [2019, 2020, 2021, 2022, 2023, 2024]
unique_meeting_id: 1
weekend_meetings: 0
decision_without_esg_agenda: 0
esg_committee_without_esg_agenda: 0
attendance_over_100: 0
missing_annual_signoff_year_entity: 0

,meeting_id,entity_id,entity_legal_name,country_code,committee_name,meeting_type,meeting_date,reporting_year,board_size,members_present,attendance_rate_pct,esg_agenda_flag,decision_made_flag,esg_topics_discussed,decision_summary,minutes_status,data_source,created_from
0,MTG-000001,ENT-GROUP-001,Atlas Banking Group SA,FR,Board of Directors,full_board,2019-01-04,2019,9,8,88.9,True,True,Annual sustainability report sign-off,Decision recorded: Annual sustainability repor...,approved,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1
1,MTG-000002,ENT-GROUP-001,Atlas Banking Group SA,FR,Board of Directors,full_board,2019-04-19,2019,11,10,90.9,False,False,NaN,NaN,approved,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1
2,MTG-000003,ENT-GROUP-001,Atlas Banking Group SA,FR,Board of Directors,full_board,2019-07-19,2019,10,10,100.0,True,True,Financed emissions methodology review,Decision recorded: Financed emissions methodol...,pending_review,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1
3,MTG-000004,ENT-GROUP-001,Atlas Banking Group SA,FR,Board of Directors,full_board,2019-10-21,2019,11,10,90.9,False,False,NaN,NaN,approved,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1
4,MTG-000005,ENT-GROUP-001,Atlas Banking Group SA,FR,Board ESG & Sustainability Committee,esg_committee,2019-03-14,2019,8,8,100.0,True,True,IFRS S2 climate disclosure approval,Decision recorded on: IFRS S2 climate disclosu...,approved,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1
5,MTG-000006,ENT-GROUP-001,Atlas Banking Group SA,FR,Board ESG & Sustainability Committee,esg_committee,2019-06-12,2019,8,8,100.0,True,False,IFRS S2 climate disclosure approval; Annual su...,Committee review completed; action items assigned,draft,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1
6,MTG-000007,ENT-GROUP-001,Atlas Banking Group SA,FR,Board ESG & Sustainability Committee,esg_committee,2019-09-18,2019,7,6,85.7,True,True,ESG remuneration KPI setting; Physical risk ex...,Decision recorded on: ESG remuneration KPI set...,approved,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1
7,MTG-000008,ENT-GROUP-001,Atlas Banking Group SA,FR,Board ESG & Sustainability Committee,esg_committee,2019-12-20,2019,8,7,87.5,True,True,ESG remuneration KPI setting; PCAF data qualit...,Decision recorded on: ESG remuneration KPI set...,approved,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1
8,MTG-000009,ENT-GROUP-001,Atlas Banking Group SA,FR,Board of Directors,full_board,2020-01-14,2020,11,9,81.8,True,True,Annual sustainability report sign-off,Decision recorded: Annual sustainability repor...,approved,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1
9,MTG-000010,ENT-GROUP-001,Atlas Banking Group SA,FR,Board of Directors,full_board,2020-04-17,2020,11,10,90.9,False,False,NaN,NaN,approved,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1
10,MTG-000011,ENT-GROUP-001,Atlas Banking Group SA,FR,Board of Directors,full_board,2020-07-17,2020,10,7,70.0,False,False,NaN,NaN,approved,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1
11,MTG-000012,ENT-GROUP-001,Atlas Banking Group SA,FR,Board of Directors,full_board,2020-10-21,2020,9,7,77.8,True,False,Physical risk exposure review,Discussion only; no formal decision recorded,approved,synthetic_board_minutes_schedule,synthetic_board_minutes_generation_v1

Scenario models outputs : Output rows from the bank's climate scenario models

In [14]:
import pandas as pd
import numpy as np
from pathlib import Path

rng = np.random.default_rng(42)

# Load available dependencies
entity_master = pd.read_csv(r"Data\entity_master_raw.csv")
counterparty_master = pd.read_csv(r"Data\counterparty_master_raw.csv")

entities = entity_master.loc[
    entity_master["in_scope_esg_flag"] == True,
    ["entity_id", "country_code"]
].reset_index(drop=True)

# -------------------------------------------------------------------
# 1) Recreate loan_book dependency if missing.
# -------------------------------------------------------------------
loan_path = Path(r"Data\loan_book_raw.csv")

if loan_path.exists():
    loan_book = pd.read_csv(loan_path)
else:
    n_loans = 35_000

    cp_idx = rng.integers(0, len(counterparty_master), size=n_loans)
    ent_idx = rng.integers(0, len(entities), size=n_loans)

    cp = counterparty_master.iloc[cp_idx].reset_index(drop=True)
    ent = entities.iloc[ent_idx].reset_index(drop=True)

    pcaf_asset_class = rng.choice(
        ["business_loan", "commercial_re", "mortgage", "project_finance", "motor_vehicle_loan", "sovereign_bond"],
        p=[0.47, 0.18, 0.20, 0.06, 0.06, 0.03],
        size=n_loans
    )

    origination_pool = pd.date_range("2017-01-01", "2024-12-31", freq="D")
    origination_dates = pd.to_datetime(rng.choice(origination_pool, size=n_loans))

    maturity_years = np.where(
        pcaf_asset_class == "mortgage",
        rng.integers(10, 31, size=n_loans),
        np.where(
            pcaf_asset_class == "commercial_re",
            rng.integers(5, 21, size=n_loans),
            rng.integers(1, 11, size=n_loans)
        )
    )
    maturity_dates = origination_dates + pd.to_timedelta(maturity_years * 365, unit="D")

    segment_multiplier = cp["segment"].map({
        "retail_microbusiness": 0.25,
        "sme": 1.0,
        "large_corporate": 8.0
    }).to_numpy()

    base_balance = np.where(
        pcaf_asset_class == "mortgage",
        rng.lognormal(np.log(250_000), 0.55, size=n_loans),
        np.where(
            pcaf_asset_class == "commercial_re",
            rng.lognormal(np.log(2_500_000), 0.85, size=n_loans),
            rng.lognormal(np.log(750_000), 1.05, size=n_loans)
        )
    )

    outstanding_balance = np.clip(base_balance * segment_multiplier, 10_000, 250_000_000)
    committed_amount = outstanding_balance * rng.uniform(1.02, 1.45, size=n_loans)

    loan_book = pd.DataFrame({
        "facility_id": [f"FAC-{i:08d}" for i in range(1, n_loans + 1)],
        "loan_id": [f"LN-{i:08d}" for i in range(1, n_loans + 1)],
        "entity_id": ent["entity_id"].to_numpy(),
        "booking_country_code": ent["country_code"].to_numpy(),
        "counterparty_id": cp["counterparty_id"].to_numpy(),
        "nace_code": cp["nace_code"].to_numpy(),
        "pcaf_asset_class": pcaf_asset_class,
        "origination_date": origination_dates.strftime("%Y-%m-%d"),
        "maturity_date": maturity_dates.strftime("%Y-%m-%d"),
        "committed_amount_eur": np.round(committed_amount, 2),
        "outstanding_balance_eur": np.round(outstanding_balance, 2),
        "currency": "EUR",
        "credit_rating": rng.choice(
            ["AAA", "AA", "A", "BBB", "BB", "B", "CCC"],
            p=[0.01, 0.04, 0.18, 0.36, 0.25, 0.13, 0.03],
            size=n_loans
        ),
        "reporting_date": "2024-12-31",
        "created_from": "synthetic_loan_book_generation_v1"
    })

    loan_book.to_csv(loan_path, index=False)

# -------------------------------------------------------------------
# 2) Generate scenario_model_out from loan_book sector composition.
# -------------------------------------------------------------------
sector_exposure = (
    loan_book.groupby("nace_code")["outstanding_balance_eur"]
    .sum()
    .reset_index()
    .rename(columns={"outstanding_balance_eur": "sector_exposure_eur"})
)

sector_names = (
    counterparty_master[["nace_code", "nace_description"]]
    .drop_duplicates("nace_code")
)
sector_exposure = sector_exposure.merge(sector_names, on="nace_code", how="left")
sector_exposure = sector_exposure[sector_exposure["sector_exposure_eur"] > 0].reset_index(drop=True)

total_book_exposure_eur = sector_exposure["sector_exposure_eur"].sum()
bank_revenue_eur = total_book_exposure_eur * 0.035  # synthetic finance denominator

scenarios = {
    "NGFS_NET_ZERO_2050": {
        "scenario_family": "orderly_transition",
        "temperature_pathway_c": 1.5,
        "physical_mult": 0.45,
        "transition_mult": 1.85,
        "description": "Orderly transition with early policy action; lower physical risk and higher near-term transition cost."
    },
    "NGFS_DISORDERLY": {
        "scenario_family": "disorderly_transition",
        "temperature_pathway_c": 2.0,
        "physical_mult": 0.95,
        "transition_mult": 1.35,
        "description": "Delayed and uneven transition; medium physical risk and elevated transition shocks."
    },
    "NGFS_HOT_HOUSE_WORLD": {
        "scenario_family": "hot_house_world",
        "temperature_pathway_c": 3.5,
        "physical_mult": 2.30,
        "transition_mult": 0.45,
        "description": "Limited climate policy response; high physical risk and lower transition cost."
    }
}

time_horizons = [2025, 2030, 2040, 2050]
metric_definitions = [
    ("credit_loss_transition", "transition", "Expected credit loss impact driven by transition policy/market shocks"),
    ("credit_loss_physical", "physical", "Expected credit loss impact driven by physical climate hazards"),
    ("rwa_increase_transition", "transition", "Risk-weighted asset increase from transition risk deterioration"),
    ("collateral_value_loss_physical", "physical", "Collateral valuation loss driven by physical risk exposure"),
]

transition_base_by_nace = {
    "B05.10": 0.18, "B06.10": 0.16, "C23.51": 0.15, "C24.10": 0.12,
    "D35.11": 0.11, "H51.10": 0.10, "H49.41": 0.09, "C20.16": 0.08,
    "C10.11": 0.055, "A01.11": 0.050, "F41.20": 0.045, "L68.20": 0.040,
    "G46.90": 0.030, "J62.01": 0.015, "K64.19": 0.012, "K64.30": 0.010
}

physical_base_by_nace = {
    "L68.20": 0.085, "A01.11": 0.080, "F41.20": 0.060, "C23.51": 0.050,
    "D35.11": 0.050, "H49.41": 0.045, "C10.11": 0.040, "B06.10": 0.040,
    "B05.10": 0.035, "C24.10": 0.030, "C20.16": 0.030, "H51.10": 0.025,
    "G46.90": 0.020, "J62.01": 0.012, "K64.19": 0.010, "K64.30": 0.010
}

rows = []
record_counter = 1

for _, sector in sector_exposure.iterrows():
    nace = sector["nace_code"]
    exposure = float(sector["sector_exposure_eur"])
    exposure_share_pct = exposure / total_book_exposure_eur * 100

    base_transition_risk = transition_base_by_nace.get(nace, 0.035)
    base_physical_risk = physical_base_by_nace.get(nace, 0.030)

    for scenario_id, scn in scenarios.items():
        previous_transition = 0.0
        previous_physical = 0.0

        for year in time_horizons:
            t_factor = (year - 2024) / (2050 - 2024)

            transition_impact = exposure * base_transition_risk * scn["transition_mult"] * t_factor
            physical_impact = exposure * base_physical_risk * scn["physical_mult"] * t_factor

            transition_impact *= rng.uniform(0.96, 1.04)
            physical_impact *= rng.uniform(0.96, 1.04)

            transition_impact = max(transition_impact, previous_transition)
            physical_impact = max(physical_impact, previous_physical)

            previous_transition = transition_impact
            previous_physical = physical_impact

            for metric_name, metric_category, metric_description in metric_definitions:
                if metric_name == "credit_loss_transition":
                    impact_eur = transition_impact
                    metric_multiplier = 1.00
                elif metric_name == "rwa_increase_transition":
                    impact_eur = transition_impact * 0.65
                    metric_multiplier = 0.65
                elif metric_name == "credit_loss_physical":
                    impact_eur = physical_impact
                    metric_multiplier = 1.00
                else:
                    impact_eur = physical_impact * 0.75
                    metric_multiplier = 0.75

                rows.append({
                    "scenario_record_id": f"SCN-{record_counter:07d}",
                    "scenario_id": scenario_id,
                    "scenario_family": scn["scenario_family"],
                    "scenario_description": scn["description"],
                    "temperature_pathway_c": scn["temperature_pathway_c"],
                    "time_horizon_year": year,
                    "metric_name": metric_name,
                    "metric_category": metric_category,
                    "metric_description": metric_description,
                    "nace_code": nace,
                    "nace_description": sector["nace_description"],
                    "sector_exposure_eur": round(exposure, 2),
                    "sector_exposure_share_pct": round(exposure_share_pct, 4),
                    "base_transition_risk_factor": base_transition_risk,
                    "base_physical_risk_factor": base_physical_risk,
                    "scenario_transition_multiplier": scn["transition_mult"],
                    "scenario_physical_multiplier": scn["physical_mult"],
                    "metric_multiplier": metric_multiplier,
                    "impact_eur": round(impact_eur, 2),
                    "impact_eur_m": round(impact_eur / 1_000_000, 4),
                    "impact_pct_of_bank_revenue": round(impact_eur / bank_revenue_eur * 100, 4),
                    "reporting_year": 2024,
                    "data_source": "synthetic_ngfs_scenario_model_output",
                    "created_from": "synthetic_scenario_model_out_generation_v1"
                })
                record_counter += 1

scenario_model_out = pd.DataFrame(rows)

# -------------------------------------------------------------------
# 3) Validation checks.
# -------------------------------------------------------------------
validation = {
    "loan_book_rows_used": len(loan_book),
    "scenario_rows": len(scenario_model_out),
    "unique_scenario_record_id": int(scenario_model_out["scenario_record_id"].is_unique),
    "scenarios_covered": sorted(scenario_model_out["scenario_id"].unique().tolist()),
    "time_horizons_covered": sorted(scenario_model_out["time_horizon_year"].unique().tolist()),
    "nace_sectors_covered": scenario_model_out["nace_code"].nunique(),
    "negative_impact_records": int((scenario_model_out["impact_eur"] < 0).sum()),
    "impact_pct_not_derived": int((
        abs(
            scenario_model_out["impact_pct_of_bank_revenue"]
            - (scenario_model_out["impact_eur"] / bank_revenue_eur * 100).round(4)
        ) > 0.0001
    ).sum())
}

phys = scenario_model_out[scenario_model_out["metric_category"] == "physical"]
phys_pivot = phys.pivot_table(
    index=["nace_code", "time_horizon_year", "metric_name"],
    columns="scenario_id",
    values="impact_eur",
    aggfunc="first"
).reset_index()
validation["hot_house_physical_not_gt_orderly"] = int(
    (phys_pivot["NGFS_HOT_HOUSE_WORLD"] <= phys_pivot["NGFS_NET_ZERO_2050"]).sum()
)

trans = scenario_model_out[scenario_model_out["metric_category"] == "transition"]
trans_pivot = trans.pivot_table(
    index=["nace_code", "time_horizon_year", "metric_name"],
    columns="scenario_id",
    values="impact_eur",
    aggfunc="first"
).reset_index()

high_transition_sectors = ["B05.10", "B06.10", "C23.51", "C24.10", "D35.11", "H51.10", "H49.41", "C20.16"]
high_trans_pivot = trans_pivot[trans_pivot["nace_code"].isin(high_transition_sectors)]
validation["orderly_transition_not_gt_hot_house_for_high_carbon"] = int(
    (high_trans_pivot["NGFS_NET_ZERO_2050"] <= high_trans_pivot["NGFS_HOT_HOUSE_WORLD"]).sum()
)

monotonic_violations = 0
for _, group in scenario_model_out.sort_values("time_horizon_year").groupby(["scenario_id", "nace_code", "metric_name"]):
    values = group["impact_eur"].to_numpy()
    if np.any(np.diff(values) < -0.01):
        monotonic_violations += 1
validation["non_monotonic_impact_series"] = monotonic_violations

expected_scenarios = {"NGFS_NET_ZERO_2050", "NGFS_DISORDERLY", "NGFS_HOT_HOUSE_WORLD"}
validation["unexpected_scenario_names"] = len(set(scenario_model_out["scenario_id"].unique()) - expected_scenarios)

out_path = Path(r"Data\scenario_model_out_raw.csv")
scenario_model_out.to_csv(out_path, index=False)

print(f"Generated loan dependency: {loan_path}")
print(f"Generated scenario table: {out_path}")
for k, v in validation.items():
    print(f"{k}: {v}")

scenario_model_out.head(12)

Generated loan dependency: Data\loan_book_raw.csv
Generated scenario table: Data\scenario_model_out_raw.csv
loan_book_rows_used: 50000
scenario_rows: 336
unique_scenario_record_id: 1
scenarios_covered: ['NGFS_DISORDERLY', 'NGFS_HOT_HOUSE_WORLD', 'NGFS_NET_ZERO_2050']
time_horizons_covered: [2025, 2030, 2040, 2050]
nace_sectors_covered: 7
negative_impact_records: 0
impact_pct_not_derived: 0
hot_house_physical_not_gt_orderly: 0
orderly_transition_not_gt_hot_house_for_high_carbon: 0
non_monotonic_impact_series: 0
unexpected_scenario_names: 0

,scenario_record_id,scenario_id,scenario_family,scenario_description,temperature_pathway_c,time_horizon_year,metric_name,metric_category,metric_description,nace_code,...,base_physical_risk_factor,scenario_transition_multiplier,scenario_physical_multiplier,metric_multiplier,impact_eur,impact_eur_m,impact_pct_of_bank_revenue,reporting_year,data_source,created_from
0,SCN-0000001,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2025,credit_loss_transition,transition,Expected credit loss impact driven by transiti...,C24.10,...,0.03,1.85,0.45,1.00,2.510627e+09,2510.6270,10.8423,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1
1,SCN-0000002,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2025,credit_loss_physical,physical,Expected credit loss impact driven by physical...,C24.10,...,0.03,1.85,0.45,1.00,1.486684e+08,148.6684,0.6420,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1
2,SCN-0000003,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2025,rwa_increase_transition,transition,Risk-weighted asset increase from transition r...,C24.10,...,0.03,1.85,0.45,0.65,1.631908e+09,1631.9075,7.0475,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1
3,SCN-0000004,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2025,collateral_value_loss_physical,physical,Collateral valuation loss driven by physical r...,C24.10,...,0.03,1.85,0.45,0.75,1.115013e+08,111.5013,0.4815,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1
4,SCN-0000005,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2030,credit_loss_transition,transition,Expected credit loss impact driven by transiti...,C24.10,...,0.03,1.85,0.45,1.00,1.516358e+10,15163.5761,65.4846,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1
5,SCN-0000006,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2030,credit_loss_physical,physical,Expected credit loss impact driven by physical...,C24.10,...,0.03,1.85,0.45,1.00,9.105473e+08,910.5473,3.9322,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1
6,SCN-0000007,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2030,rwa_increase_transition,transition,Risk-weighted asset increase from transition r...,C24.10,...,0.03,1.85,0.45,0.65,9.856324e+09,9856.3245,42.5650,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1
7,SCN-0000008,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2030,collateral_value_loss_physical,physical,Collateral valuation loss driven by physical r...,C24.10,...,0.03,1.85,0.45,0.75,6.829105e+08,682.9105,2.9492,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1
8,SCN-0000009,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2040,credit_loss_transition,transition,Expected credit loss impact driven by transiti...,C24.10,...,0.03,1.85,0.45,1.00,3.803234e+10,38032.3433,164.2445,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1
9,SCN-0000010,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2040,credit_loss_physical,physical,Expected credit loss impact driven by physical...,C24.10,...,0.03,1.85,0.45,1.00,2.481337e+09,2481.3370,10.7158,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1
10,SCN-0000011,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2040,rwa_increase_transition,transition,Risk-weighted asset increase from transition r...,C24.10,...,0.03,1.85,0.45,0.65,2.472102e+10,24721.0231,106.7589,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1
11,SCN-0000012,NGFS_NET_ZERO_2050,orderly_transition,Orderly transition with early policy action; l...,1.5,2040,collateral_value_loss_physical,physical,Collateral valuation loss driven by physical r...,C24.10,...,0.03,1.85,0.45,0.75,1.861003e+09,1861.0027,8.0368,2024,synthetic_ngfs_scenario_model_output,synthetic_scenario_model_out_generation_v1

Audit log : Tracks the assurance process

In [15]:
import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# CONFIG
# =========================================================
rng = np.random.default_rng(42)

DATA_DIR = Path("Data")
OUTPUT_PATH = DATA_DIR / "audit_log_raw.csv"

years = list(range(2019, 2025))

# =========================================================
# LOAD DEPENDENCIES
# =========================================================
entity_master = pd.read_csv(DATA_DIR / "entity_master_raw.csv")
esg_kpi_tracker = pd.read_csv(DATA_DIR / "esg_kpi_tracker_raw.csv")
board_minutes = pd.read_csv(DATA_DIR / "board_minutes_raw.csv")
erm_system = pd.read_csv(DATA_DIR / "erm_system_raw.csv")

# Clean column names
for df in [entity_master, esg_kpi_tracker, board_minutes, erm_system]:
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

# =========================================================
# REQUIRED COLUMN CHECKS
# =========================================================
required_entity_cols = [
    "entity_id",
    "legal_name",
    "country_code",
    "regulatory_regime",
    "in_scope_esg_flag",
]

required_kpi_cols = [
    "kpi_code",
    "kpi_name",
    "category",
    "reporting_year",
]

required_board_cols = [
    "meeting_id",
    "entity_id",
    "reporting_year",
    "esg_agenda_flag",
    "decision_made_flag",
    "esg_topics_discussed",
]

required_erm_cols = [
    "risk_id",
    "risk_name",
    "risk_category",
    "reporting_year",
]

missing_entity_cols = [c for c in required_entity_cols if c not in entity_master.columns]
missing_kpi_cols = [c for c in required_kpi_cols if c not in esg_kpi_tracker.columns]
missing_board_cols = [c for c in required_board_cols if c not in board_minutes.columns]
missing_erm_cols = [c for c in required_erm_cols if c not in erm_system.columns]

if missing_entity_cols:
    raise ValueError(f"entity_master is missing columns: {missing_entity_cols}")

if missing_kpi_cols:
    raise ValueError(f"esg_kpi_tracker is missing columns: {missing_kpi_cols}")

if missing_board_cols:
    raise ValueError(f"board_minutes is missing columns: {missing_board_cols}")

if missing_erm_cols:
    raise ValueError(f"erm_system is missing columns: {missing_erm_cols}")

# =========================================================
# FILTER IN-SCOPE ENTITIES
# =========================================================
entity_master["in_scope_esg_flag"] = (
    entity_master["in_scope_esg_flag"]
    .astype(str)
    .str.lower()
    .isin(["true", "1", "yes"])
)

entities = (
    entity_master.loc[
        entity_master["in_scope_esg_flag"].eq(True),
        ["entity_id", "legal_name", "country_code", "regulatory_regime"]
    ]
    .dropna(subset=["entity_id", "country_code"])
    .drop_duplicates()
    .reset_index(drop=True)
)

if entities.empty:
    raise ValueError("No in-scope ESG entities found in entity_master_raw.csv")

# =========================================================
# KPI GROUPS
# =========================================================
kpis = (
    esg_kpi_tracker[
        ["kpi_code", "kpi_name", "category", "reporting_year"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

scope12_kpis = kpis[
    kpis["kpi_code"].isin(["ENV-001", "ENV-002", "ENV-003"])
].copy()

financed_kpis = kpis[
    kpis["kpi_code"].isin([
        "FIN-001",
        "FIN-003",
        "FIN-004",
        "FIN-005",
        "FIN-008",
        "FIN-009",
        "FIN-010",
        "FIN-011",
        "FIN-012",
    ])
].copy()

governance_kpis = kpis[
    kpis["kpi_code"].isin(["GOV-001"])
].copy()

social_kpis = kpis[
    kpis["kpi_code"].isin(["SOC-001", "SOC-002"])
].copy()

# =========================================================
# BOARD / ERM REFERENCES
# =========================================================
board_minutes["esg_agenda_flag"] = (
    board_minutes["esg_agenda_flag"]
    .astype(str)
    .str.lower()
    .isin(["true", "1", "yes"])
)

board_minutes["decision_made_flag"] = (
    board_minutes["decision_made_flag"]
    .astype(str)
    .str.lower()
    .isin(["true", "1", "yes"])
)

board_evidence = board_minutes[
    board_minutes["esg_agenda_flag"].eq(True)
].copy()

erm_ref = (
    erm_system[
        ["risk_id", "risk_name", "risk_category", "reporting_year"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

# =========================================================
# AUDITOR CONFIG
# =========================================================
auditor_pool_by_country = {
    "DE": ["PwC Germany", "KPMG Germany", "EY Germany", "Deloitte Germany"],
    "NL": ["Deloitte Netherlands", "KPMG Netherlands", "PwC Netherlands", "EY Netherlands"],
    "FR": ["EY France", "KPMG France", "Deloitte France", "PwC France"],
    "GB": ["PwC UK", "KPMG UK", "EY UK", "Deloitte UK"],
    "IT": ["Deloitte Italy", "KPMG Italy", "PwC Italy", "EY Italy"],
    "ES": ["EY Spain", "KPMG Spain", "Deloitte Spain", "PwC Spain"],
    "TN": ["EY Tunisia", "PwC Tunisia", "KPMG Tunisia", "Deloitte Tunisia"],
}

assurance_standards = {
    "big4": ["ISAE3000", "ISAE3410"],
    "specialist_verifier": ["AA1000AS", "ISO14064-3"],
}

finding_templates = {
    "unmodified": [
        "No material misstatements identified; minor process observations communicated to management.",
        "Assurance procedures completed with clean conclusion across selected ESG metrics.",
        "Evidence obtained was sufficient and appropriate for the stated assurance scope.",
    ],
    "modified": [
        "Modified conclusion due to limited evidence over selected Scope 3 estimation assumptions.",
        "One data lineage weakness identified; management remediation plan agreed.",
        "Boundary restatement required for one subsidiary; comparative figures corrected.",
    ],
    "adverse": [
        "Adverse conclusion issued because reported figures were not supported by reliable evidence.",
        "Material inconsistency identified between disclosed financed emissions and source portfolio data.",
    ],
    "disclaimer": [
        "Disclaimer issued because supporting evidence was insufficient for key reported metrics.",
        "Scope limitation prevented completion of procedures over selected ESG indicators.",
    ],
}

# =========================================================
# HELPERS
# =========================================================
def pick_kpi_scope(year):
    """
    Assurance scope expands over time.
    """
    if year <= 2021:
        selected = scope12_kpis[
            scope12_kpis["reporting_year"].eq(year)
        ].copy()

        assurance_scope_type = "operational_emissions"

    elif year in [2022, 2023]:
        selected = pd.concat([
            scope12_kpis[scope12_kpis["reporting_year"].eq(year)],
            governance_kpis[governance_kpis["reporting_year"].eq(year)],
        ])

        assurance_scope_type = "operational_emissions_and_governance"

    else:
        selected = pd.concat([
            scope12_kpis[scope12_kpis["reporting_year"].eq(year)],
            financed_kpis[financed_kpis["reporting_year"].eq(year)],
            governance_kpis[governance_kpis["reporting_year"].eq(year)],
            social_kpis[social_kpis["reporting_year"].eq(year)],
        ])

        assurance_scope_type = "full_esg_and_financed_emissions"

    if selected.empty:
        selected = kpis[kpis["reporting_year"].eq(year)].copy()

    if selected.empty:
        selected = kpis.copy()

    return selected.drop_duplicates(), assurance_scope_type


def pick_board_meeting(entity_id, year):
    pool = board_evidence[
        board_evidence["entity_id"].eq(entity_id)
        & board_evidence["reporting_year"].eq(year)
    ].copy()

    if pool.empty:
        pool = board_evidence[
            board_evidence["entity_id"].eq(entity_id)
        ].copy()

    if pool.empty:
        return None

    # Prefer decisions, not only discussions
    decision_pool = pool[pool["decision_made_flag"].eq(True)]

    if not decision_pool.empty:
        pool = decision_pool

    selected = pool.sample(
        n=1,
        random_state=int(rng.integers(1, 1_000_000))
    ).iloc[0]

    return selected["meeting_id"]


def pick_erm_risks(year, n=2):
    pool = erm_ref[
        erm_ref["reporting_year"].eq(year)
    ].copy()

    if pool.empty:
        pool = erm_ref.copy()

    if pool.empty:
        return []

    n = min(n, len(pool))

    selected = pool.sample(
        n=n,
        replace=False,
        random_state=int(rng.integers(1, 1_000_000))
    )

    return selected["risk_id"].tolist()


# =========================================================
# ASSIGN STABLE AUDITOR PER ENTITY
# =========================================================
entity_auditors = {}

for _, entity in entities.iterrows():
    country = str(entity["country_code"]).upper()
    pool = auditor_pool_by_country.get(
        country,
        ["EY Germany", "PwC Germany", "KPMG Germany", "Deloitte Germany"]
    )

    entity_auditors[entity["entity_id"]] = rng.choice(pool)

# =========================================================
# GENERATE AUDIT LOG
# =========================================================
rows = []

for _, entity in entities.iterrows():
    previous_level_rank = 1
    auditor_name = entity_auditors[entity["entity_id"]]

    for year in years:
        # -------------------------------------------------
        # Assurance level improves over time
        # -------------------------------------------------
        if year <= 2021:
            assurance_level = "limited"
        elif year in [2022, 2023]:
            assurance_level = "reasonable" if rng.random() < 0.35 else "limited"
        else:
            assurance_level = "reasonable"

        level_rank = 2 if assurance_level == "reasonable" else 1

        # Avoid downgrade
        if level_rank < previous_level_rank:
            assurance_level = "reasonable"
            level_rank = 2

        previous_level_rank = level_rank

        # -------------------------------------------------
        # Covered KPIs
        # -------------------------------------------------
        covered_kpis, assurance_scope_type = pick_kpi_scope(year)

        covered_kpi_codes = covered_kpis["kpi_code"].tolist()
        covered_kpi_names = covered_kpis["kpi_name"].tolist()

        if year <= 2021:
            scope_description = (
                "Limited assurance over operational Scope 1 and Scope 2 emissions: "
                + "; ".join(covered_kpi_names)
            )

        elif year in [2022, 2023]:
            scope_description = (
                "Assurance over operational emissions and governance oversight metrics: "
                + "; ".join(covered_kpi_names)
            )

        else:
            scope_description = (
                "Reasonable assurance over operational emissions, financed emissions, "
                "portfolio climate KPIs, governance and selected social metrics: "
                + "; ".join(covered_kpi_names)
            )

        # -------------------------------------------------
        # Auditor type and standard
        # -------------------------------------------------
        auditor_type = (
            "big4"
            if any(x in auditor_name for x in ["PwC", "KPMG", "EY", "Deloitte"])
            else "specialist_verifier"
        )

        assurance_standard = rng.choice(
            assurance_standards[auditor_type]
        )

        # -------------------------------------------------
        # Opinion distribution
        # -------------------------------------------------
        if year <= 2021:
            opinion = rng.choice(
                ["unmodified", "modified", "adverse", "disclaimer"],
                p=[0.80, 0.16, 0.02, 0.02],
            )

        elif year in [2022, 2023]:
            opinion = rng.choice(
                ["unmodified", "modified", "adverse", "disclaimer"],
                p=[0.86, 0.12, 0.01, 0.01],
            )

        else:
            opinion = rng.choice(
                ["unmodified", "modified", "adverse", "disclaimer"],
                p=[0.90, 0.09, 0.005, 0.005],
            )

        findings_summary = rng.choice(finding_templates[opinion])

        material_weakness_flag = opinion in ["modified", "adverse", "disclaimer"]

        # -------------------------------------------------
        # Evidence links
        # -------------------------------------------------
        linked_board_meeting_id = pick_board_meeting(
            entity["entity_id"],
            year
        )

        linked_erm_risk_ids = pick_erm_risks(
            year,
            n=3 if year >= 2024 else 2
        )

        evidence_basis_parts = [
            "esg_kpi_tracker",
            "entity_master",
        ]

        if linked_board_meeting_id is not None:
            evidence_basis_parts.append("board_minutes")

        if linked_erm_risk_ids:
            evidence_basis_parts.append("erm_system")

        if year >= 2024:
            evidence_basis_parts.extend([
                "loan_book",
                "counterparty_master",
                "collateral_register",
                "utility_bills",
                "emission_factors",
            ])

        evidence_basis = "; ".join(sorted(set(evidence_basis_parts)))

        # -------------------------------------------------
        # Dates
        # Sign-off after year-end
        # -------------------------------------------------
        signoff_day = int(rng.integers(20, 29))
        sign_off_date = pd.Timestamp(year + 1, 3, signoff_day)

        if material_weakness_flag:
            remediation_due_date = (
                sign_off_date + pd.Timedelta(days=int(rng.integers(60, 181)))
            ).date()
        else:
            remediation_due_date = pd.NaT

        rows.append({
            "audit_id": f"AUD-{entity['entity_id']}-{year}",
            "entity_id": entity["entity_id"],
            "entity_legal_name": entity["legal_name"],
            "country_code": entity["country_code"],
            "regulatory_regime": entity["regulatory_regime"],
            "reporting_year": year,

            "auditor_name": auditor_name,
            "auditor_type": auditor_type,
            "assurance_standard": assurance_standard,
            "assurance_level": assurance_level,

            "assurance_scope_type": assurance_scope_type,
            "scope_description": scope_description,

            "covered_kpi_codes": "; ".join(covered_kpi_codes),
            "covered_kpi_names": "; ".join(covered_kpi_names),

            "linked_board_meeting_id": linked_board_meeting_id,
            "linked_erm_risk_ids": "; ".join(linked_erm_risk_ids),

            "opinion": opinion,
            "findings_summary": findings_summary,
            "material_weakness_flag": bool(material_weakness_flag),
            "remediation_due_date": remediation_due_date,

            "sign_off_date": sign_off_date.strftime("%Y-%m-%d"),
            "assurance_engagement_status": "signed_off",

            "evidence_basis": evidence_basis,

            "data_source": "synthetic_assurance_engagement_register",
            "created_from": "synthetic_audit_log_generation_v2_core_tables_aligned",
        })

audit_log = pd.DataFrame(rows)

# =========================================================
# VALIDATION
# =========================================================
valid_entity_ids = set(entity_master["entity_id"].astype(str))
valid_kpi_codes = set(esg_kpi_tracker["kpi_code"].astype(str))
valid_kpi_names = set(esg_kpi_tracker["kpi_name"].astype(str))
valid_board_ids = set(board_minutes["meeting_id"].astype(str))
valid_erm_ids = set(erm_system["risk_id"].astype(str))

referenced_codes = set()
for val in audit_log["covered_kpi_codes"]:
    referenced_codes.update([
        x.strip()
        for x in str(val).split(";")
        if x.strip()
    ])

referenced_names = set()
for val in audit_log["covered_kpi_names"]:
    referenced_names.update([
        x.strip()
        for x in str(val).split(";")
        if x.strip()
    ])

referenced_erm_ids = set()
for val in audit_log["linked_erm_risk_ids"]:
    referenced_erm_ids.update([
        x.strip()
        for x in str(val).split(";")
        if x.strip()
    ])

level_rank_map = {
    "limited": 1,
    "reasonable": 2,
}

downgrade_violations = 0

for _, group in audit_log.sort_values("reporting_year").groupby("entity_id"):
    ranks = group["assurance_level"].map(level_rank_map).to_numpy()

    if np.any(np.diff(ranks) < 0):
        downgrade_violations += 1

signoff_dates = pd.to_datetime(audit_log["sign_off_date"])
year_end_dates = pd.to_datetime(
    audit_log["reporting_year"].astype(str) + "-12-31"
)

bad_opinion_without_explanation = audit_log[
    audit_log["opinion"].isin(["adverse", "disclaimer", "modified"])
    & audit_log["findings_summary"].isna()
]

validation = {
    "rows": len(audit_log),
    "entities_covered": audit_log["entity_id"].nunique(),
    "years_covered": sorted(audit_log["reporting_year"].unique().tolist()),
    "unique_audit_id": int(audit_log["audit_id"].is_unique),

    "entity_id_missing_from_entity_master": int(
        (~audit_log["entity_id"].astype(str).isin(valid_entity_ids)).sum()
    ),

    "invalid_referenced_kpi_codes": len(
        referenced_codes - valid_kpi_codes
    ),

    "invalid_referenced_kpi_names": len(
        referenced_names - valid_kpi_names
    ),

    "invalid_linked_board_meeting_id": int(
        (
            audit_log["linked_board_meeting_id"].notna()
            & ~audit_log["linked_board_meeting_id"].astype(str).isin(valid_board_ids)
        ).sum()
    ),

    "invalid_linked_erm_risk_ids": len(
        referenced_erm_ids - valid_erm_ids
    ),

    "assurance_downgrade_violations": int(
        downgrade_violations
    ),

    "sign_off_not_after_year_end": int(
        (signoff_dates <= year_end_dates).sum()
    ),

    "adverse_modified_or_disclaimer_without_findings": int(
        len(bad_opinion_without_explanation)
    ),

    "material_weakness_without_remediation_due_date": int(
        (
            audit_log["material_weakness_flag"].eq(True)
            & audit_log["remediation_due_date"].isna()
        ).sum()
    ),

    "missing_scope_description": int(
        audit_log["scope_description"].isna().sum()
    ),

    "missing_evidence_basis": int(
        audit_log["evidence_basis"].isna().sum()
    ),
}

# =========================================================
# SAVE
# =========================================================
audit_log.to_csv(OUTPUT_PATH, index=False)

print(f"Generated: {OUTPUT_PATH}")

print("\nValidation:")
for key, value in validation.items():
    print(f"{key}: {value}")

print("\nPreview:")
print(audit_log.head(12))

Generated: Data\audit_log_raw.csv

Validation:
rows: 60
entities_covered: 10
years_covered: [2019, 2020, 2021, 2022, 2023, 2024]
unique_audit_id: 1
entity_id_missing_from_entity_master: 0
invalid_referenced_kpi_codes: 0
invalid_referenced_kpi_names: 0
invalid_linked_board_meeting_id: 0
invalid_linked_erm_risk_ids: 0
assurance_downgrade_violations: 0
sign_off_not_after_year_end: 0
adverse_modified_or_disclaimer_without_findings: 0
material_weakness_without_remediation_due_date: 0
missing_scope_description: 0
missing_evidence_basis: 0

Preview:
                  audit_id      entity_id            entity_legal_name  \
0   AUD-ENT-GROUP-001-2019  ENT-GROUP-001       Atlas Banking Group SA
1   AUD-ENT-GROUP-001-2020  ENT-GROUP-001       Atlas Banking Group SA
2   AUD-ENT-GROUP-001-2021  ENT-GROUP-001       Atlas Banking Group SA
3   AUD-ENT-GROUP-001-2022  ENT-GROUP-001       Atlas Banking Group SA
4   AUD-ENT-GROUP-001-2023  ENT-GROUP-001       Atlas Banking Group SA
5   AUD-ENT-GROUP-001-2024  ENT-GROUP-001       Atlas Banking Group SA
6      AUD-ENT-FR-002-2019     ENT-FR-002  Atlas Retail Bank France SA
7      AUD-ENT-FR-002-2020     ENT-FR-002  Atlas Retail Bank France SA
8      AUD-ENT-FR-002-2021     ENT-FR-002  Atlas Retail Bank France SA
9      AUD-ENT-FR-002-2022     ENT-FR-002  Atlas Retail Bank France SA
10     AUD-ENT-FR-002-2023     ENT-FR-002  Atlas Retail Bank France SA
11     AUD-ENT-FR-002-2024     ENT-FR-002  Atlas Retail Bank France SA

   country_code regulatory_regime  reporting_year auditor_name auditor_type  \
0            FR              CSRD            2019    EY France         big4
1            FR              CSRD            2020    EY France         big4
2            FR              CSRD            2021    EY France         big4
3            FR              CSRD            2022    EY France         big4
4            FR              CSRD            2023    EY France         big4
5            FR              CSRD            2024    EY France         big4
6            FR              CSRD            2019   PwC France         big4
7            FR              CSRD            2020   PwC France         big4
8            FR              CSRD            2021   PwC France         big4
9            FR              CSRD            2022   PwC France         big4
10           FR              CSRD            2023   PwC France         big4
11           FR              CSRD            2024   PwC France         big4

   assurance_standard assurance_level  ...           linked_erm_risk_ids  \
0            ISAE3410         limited  ...            RISK-011; RISK-012
1            ISAE3000         limited  ...            RISK-011; RISK-003
2            ISAE3410         limited  ...            RISK-008; RISK-011
3            ISAE3410         limited  ...            RISK-009; RISK-008
4            ISAE3410         limited  ...            RISK-005; RISK-004
5            ISAE3000      reasonable  ...  RISK-006; RISK-015; RISK-011
6            ISAE3410         limited  ...            RISK-002; RISK-014
7            ISAE3000         limited  ...            RISK-004; RISK-003
8            ISAE3000         limited  ...            RISK-004; RISK-008
9            ISAE3410         limited  ...            RISK-008; RISK-011
10           ISAE3000         limited  ...            RISK-014; RISK-007
11           ISAE3410      reasonable  ...  RISK-013; RISK-006; RISK-011

       opinion                                   findings_summary  \
0   unmodified  Evidence obtained was sufficient and appropria...
1   unmodified  Assurance procedures completed with clean conc...
2     modified  One data lineage weakness identified; manageme...
3   unmodified  No material misstatements identified; minor pr...
4     modified  One data lineage weakness identified; manageme...
5   unmodified  Assurance procedures completed with clean conc...
6   unmodified  Evidence obtained was sufficient and appropria...
7   unmodified  No material misstatements identified; minor pr...
8   unmodified  No material misstatements identified; minor pr...
9   unmodified  Assurance procedures completed with clean conc...
10  unmodified  Evidence obtained was sufficient and appropria...
11  unmodified  Evidence obtained was sufficient and appropria...

   material_weakness_flag remediation_due_date sign_off_date  \
0                   False                  NaT    2020-03-24
1                   False                  NaT    2021-03-28
2                    True           2022-06-19    2022-03-24
3                   False                  NaT    2023-03-21
4                    True           2024-08-25    2024-03-27
5                   False                  NaT    2025-03-21
6                   False                  NaT    2020-03-23
7                   False                  NaT    2021-03-21
8                   False                  NaT    2022-03-25
9                   False                  NaT    2023-03-22
10                  False                  NaT    2024-03-22
11                  False                  NaT    2025-03-20

   assurance_engagement_status  \
0                   signed_off
1                   signed_off
2                   signed_off
3                   signed_off
4                   signed_off
5                   signed_off
6                   signed_off
7                   signed_off
8                   signed_off
9                   signed_off
10                  signed_off
11                  signed_off

                                       evidence_basis  \
0   board_minutes; entity_master; erm_system; esg_...
1   board_minutes; entity_master; erm_system; esg_...
2   board_minutes; entity_master; erm_system; esg_...
3   board_minutes; entity_master; erm_system; esg_...
4   board_minutes; entity_master; erm_system; esg_...
5   board_minutes; collateral_register; counterpar...
6   board_minutes; entity_master; erm_system; esg_...
7   board_minutes; entity_master; erm_system; esg_...
8   board_minutes; entity_master; erm_system; esg_...
9   board_minutes; entity_master; erm_system; esg_...
10  board_minutes; entity_master; erm_system; esg_...
11  board_minutes; collateral_register; counterpar...

                                data_source  \
0   synthetic_assurance_engagement_register
1   synthetic_assurance_engagement_register
2   synthetic_assurance_engagement_register
3   synthetic_assurance_engagement_register
4   synthetic_assurance_engagement_register
5   synthetic_assurance_engagement_register
6   synthetic_assurance_engagement_register
7   synthetic_assurance_engagement_register
8   synthetic_assurance_engagement_register
9   synthetic_assurance_engagement_register
10  synthetic_assurance_engagement_register
11  synthetic_assurance_engagement_register

                                         created_from
0   synthetic_audit_log_generation_v2_core_tables_...
1   synthetic_audit_log_generation_v2_core_tables_...
2   synthetic_audit_log_generation_v2_core_tables_...
3   synthetic_audit_log_generation_v2_core_tables_...
4   synthetic_audit_log_generation_v2_core_tables_...
5   synthetic_audit_log_generation_v2_core_tables_...
6   synthetic_audit_log_generation_v2_core_tables_...
7   synthetic_audit_log_generation_v2_core_tables_...
8   synthetic_audit_log_generation_v2_core_tables_...
9   synthetic_audit_log_generation_v2_core_tables_...
10  synthetic_audit_log_generation_v2_core_tables_...
11  synthetic_audit_log_generation_v2_core_tables_...

[12 rows x 25 columns]

Internal Carbon Price

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# CONFIG
# =========================================================
rng = np.random.default_rng(42)

DATA_DIR = Path("Data")
OUTPUT_PATH = DATA_DIR / "internal_carbon_price_raw.csv"

reporting_years = list(range(2019, 2025))

# =========================================================
# LOAD DEPENDENCIES
# =========================================================
entity_master = pd.read_csv(DATA_DIR / "entity_master_raw.csv")

# Optional dependency: used only for baseline-year validation
esg_kpi_path = DATA_DIR / "esg_kpi_tracker_raw.csv"
esg_kpi_tracker = pd.read_csv(esg_kpi_path) if esg_kpi_path.exists() else None

# Clean column names
entity_master.columns = (
    entity_master.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

if esg_kpi_tracker is not None:
    esg_kpi_tracker.columns = (
        esg_kpi_tracker.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

# =========================================================
# REQUIRED COLUMN CHECKS
# =========================================================
required_entity_cols = [
    "entity_id",
    "legal_name",
    "country_code",
    "in_scope_esg_flag",
]

missing_entity_cols = [
    col for col in required_entity_cols
    if col not in entity_master.columns
]

if missing_entity_cols:
    raise ValueError(f"entity_master is missing columns: {missing_entity_cols}")

# =========================================================
# FILTER IN-SCOPE ENTITIES
# =========================================================
entity_master["in_scope_esg_flag"] = (
    entity_master["in_scope_esg_flag"]
    .astype(str)
    .str.lower()
    .isin(["true", "1", "yes"])
)

entities = (
    entity_master.loc[
        entity_master["in_scope_esg_flag"].eq(True),
        ["entity_id", "legal_name", "country_code"]
    ]
    .dropna(subset=["entity_id", "country_code"])
    .drop_duplicates()
    .reset_index(drop=True)
)

if entities.empty:
    raise ValueError("No in-scope ESG entities found in entity_master_raw.csv")

# Optional baseline check against ESG KPI tracker
if esg_kpi_tracker is not None and "reporting_year" in esg_kpi_tracker.columns:
    if 2019 not in esg_kpi_tracker["reporting_year"].unique():
        raise ValueError("esg_kpi_tracker_raw.csv does not contain baseline year 2019")

# =========================================================
# GENERATE INTERNAL CARBON PRICE TABLE
# =========================================================
rows = []

for _, entity in entities.iterrows():
    entity_id = entity["entity_id"]

    # Baseline price in 2019:
    # normal(30, 8), clipped to [15, 55]
    base_price = float(
        np.clip(
            rng.normal(30, 8),
            15,
            55
        )
    )

    # Annual growth varies by entity ambition
    annual_growth = float(
        rng.uniform(5, 9)
    )

    price_type = rng.choice(
        ["shadow_price", "internal_charge"],
        p=[0.75, 0.25]
    )

    # If internal charge, avoid investment_decisions only
    if price_type == "internal_charge":
        application_scope = rng.choice(
            ["capex_appraisal", "product_pricing", "all"],
            p=[0.35, 0.20, 0.45]
        )
    else:
        application_scope = rng.choice(
            [
                "investment_decisions",
                "capex_appraisal",
                "product_pricing",
                "all",
            ],
            p=[0.40, 0.30, 0.10, 0.20]
        )

    review_frequency = rng.choice(
        ["annual", "biennial"],
        p=[0.70, 0.30]
    )

    benchmark_reference = rng.choice(
        [
            "EU_ETS_spot",
            "NGFS_transition_scenario",
            "IEA_NZE_pathway",
            "internal_model",
        ],
        p=[0.35, 0.25, 0.20, 0.20]
    )

    applies_to_financed_emissions = bool(
        rng.choice(
            [True, False],
            p=[0.45, 0.55]
        )
    )

    prev_price = None

    for year in reporting_years:
        years_elapsed = year - 2019

        expected_price = base_price + years_elapsed * annual_growth

        noise_factor = rng.uniform(0.92, 1.08)

        price = float(
            np.clip(
                expected_price * noise_factor,
                15,
                150
            )
        )

        # Enforce minimum +1% year-on-year increase
        if prev_price is not None:
            price = max(price, prev_price * 1.01)

        # Keep final price inside cap
        price = min(price, 150)

        prev_price = price

        rows.append({
            "price_id": f"ICP-{entity_id}-{year}",
            "entity_id": entity_id,
            "entity_legal_name": entity["legal_name"],
            "country_code": entity["country_code"],
            "reporting_year": year,

            "carbon_price_eur_per_tco2e": round(price, 2),
            "price_type": price_type,
            "application_scope": application_scope,
            "review_frequency": review_frequency,
            "currency": "EUR",
            "benchmark_reference": benchmark_reference,
            "applies_to_financed_emissions": applies_to_financed_emissions,

            "baseline_year": 2019,
            "price_setting_method": "synthetic_shadow_price_policy",
            "data_source": "synthetic_internal_carbon_pricing_policy",
            "created_from": "synthetic_internal_carbon_price_generation_v1",
        })

internal_carbon_price = pd.DataFrame(rows)

# =========================================================
# VALIDATION
# =========================================================
valid_entity_ids = set(entity_master["entity_id"].astype(str))

duplicates = internal_carbon_price.duplicated(
    ["entity_id", "reporting_year"]
).sum()

price_outside_range = (
    (internal_carbon_price["carbon_price_eur_per_tco2e"] < 15)
    | (internal_carbon_price["carbon_price_eur_per_tco2e"] > 150)
).sum()

# Check strict year-on-year increase by entity
yoy_violations = 0

for entity_id, group in internal_carbon_price.groupby("entity_id"):
    group = group.sort_values("reporting_year").copy()

    prices = group["carbon_price_eur_per_tco2e"].to_numpy()

    if len(prices) > 1:
        yoy_growth = prices[1:] / prices[:-1] - 1

        yoy_violations += int(
            (yoy_growth < 0.009).sum()
        )

internal_charge_bad_scope = (
    internal_carbon_price["price_type"].eq("internal_charge")
    & internal_carbon_price["application_scope"].eq("investment_decisions")
).sum()

validation = {
    "rows": len(internal_carbon_price),

    "entities_covered": internal_carbon_price["entity_id"].nunique(),

    "years_covered": sorted(
        internal_carbon_price["reporting_year"].unique().tolist()
    ),

    "unique_price_id": int(
        internal_carbon_price["price_id"].is_unique
    ),

    "entity_id_missing_from_entity_master": int(
        (~internal_carbon_price["entity_id"].astype(str).isin(valid_entity_ids)).sum()
    ),

    "duplicate_entity_year_rows": int(duplicates),

    "price_outside_15_150": int(price_outside_range),

    "year_on_year_increase_violations": int(yoy_violations),

    "internal_charge_with_investment_only_scope": int(
        internal_charge_bad_scope
    ),

    "missing_carbon_price": int(
        internal_carbon_price["carbon_price_eur_per_tco2e"].isna().sum()
    ),

    "non_eur_currency_rows": int(
        (~internal_carbon_price["currency"].eq("EUR")).sum()
    ),
}

# =========================================================
# SAVE OUTPUT
# =========================================================
internal_carbon_price.to_csv(OUTPUT_PATH, index=False)

print(f"Generated: {OUTPUT_PATH}")

print("\nValidation:")
for key, value in validation.items():
    print(f"{key}: {value}")

print("\nPreview:")
print(internal_carbon_price.head(12))

Generated: Data\internal_carbon_price_raw.csv

Validation:
rows: 60
entities_covered: 10
years_covered: [2019, 2020, 2021, 2022, 2023, 2024]
unique_price_id: 1
entity_id_missing_from_entity_master: 0
duplicate_entity_year_rows: 0
price_outside_15_150: 0
year_on_year_increase_violations: 0
internal_charge_with_investment_only_scope: 0
missing_carbon_price: 0
non_eur_currency_rows: 0

Preview:
                  price_id      entity_id            entity_legal_name  \
0   ICP-ENT-GROUP-001-2019  ENT-GROUP-001       Atlas Banking Group SA
1   ICP-ENT-GROUP-001-2020  ENT-GROUP-001       Atlas Banking Group SA
2   ICP-ENT-GROUP-001-2021  ENT-GROUP-001       Atlas Banking Group SA
3   ICP-ENT-GROUP-001-2022  ENT-GROUP-001       Atlas Banking Group SA
4   ICP-ENT-GROUP-001-2023  ENT-GROUP-001       Atlas Banking Group SA
5   ICP-ENT-GROUP-001-2024  ENT-GROUP-001       Atlas Banking Group SA
6      ICP-ENT-FR-002-2019     ENT-FR-002  Atlas Retail Bank France SA
7      ICP-ENT-FR-002-2020     ENT-FR-002  Atlas Retail Bank France SA
8      ICP-ENT-FR-002-2021     ENT-FR-002  Atlas Retail Bank France SA
9      ICP-ENT-FR-002-2022     ENT-FR-002  Atlas Retail Bank France SA
10     ICP-ENT-FR-002-2023     ENT-FR-002  Atlas Retail Bank France SA
11     ICP-ENT-FR-002-2024     ENT-FR-002  Atlas Retail Bank France SA

   country_code  reporting_year  carbon_price_eur_per_tco2e       price_type  \
0            FR            2019                       33.92  internal_charge
1            FR            2020                       36.86  internal_charge
2            FR            2021                       45.58  internal_charge
3            FR            2022                       51.61  internal_charge
4            FR            2023                       63.52  internal_charge
5            FR            2024                       67.74  internal_charge
6            FR            2019                       40.63     shadow_price
7            FR            2020                       44.73     shadow_price
8            FR            2021                       56.52     shadow_price
9            FR            2022                       63.07     shadow_price
10           FR            2023                       69.06     shadow_price
11           FR            2024                       69.75     shadow_price

   application_scope review_frequency currency benchmark_reference  \
0                all           annual      EUR      internal_model
1                all           annual      EUR      internal_model
2                all           annual      EUR      internal_model
3                all           annual      EUR      internal_model
4                all           annual      EUR      internal_model
5                all           annual      EUR      internal_model
6    capex_appraisal           annual      EUR      internal_model
7    capex_appraisal           annual      EUR      internal_model
8    capex_appraisal           annual      EUR      internal_model
9    capex_appraisal           annual      EUR      internal_model
10   capex_appraisal           annual      EUR      internal_model
11   capex_appraisal           annual      EUR      internal_model

    applies_to_financed_emissions  baseline_year  \
0                           False           2019
1                           False           2019
2                           False           2019
3                           False           2019
4                           False           2019
5                           False           2019
6                           False           2019
7                           False           2019
8                           False           2019
9                           False           2019
10                          False           2019
11                          False           2019

             price_setting_method                               data_source  \
0   synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy
1   synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy
2   synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy
3   synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy
4   synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy
5   synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy
6   synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy
7   synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy
8   synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy
9   synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy
10  synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy
11  synthetic_shadow_price_policy  synthetic_internal_carbon_pricing_policy

                                     created_from
0   synthetic_internal_carbon_price_generation_v1
1   synthetic_internal_carbon_price_generation_v1
2   synthetic_internal_carbon_price_generation_v1
3   synthetic_internal_carbon_price_generation_v1
4   synthetic_internal_carbon_price_generation_v1
5   synthetic_internal_carbon_price_generation_v1
6   synthetic_internal_carbon_price_generation_v1
7   synthetic_internal_carbon_price_generation_v1
8   synthetic_internal_carbon_price_generation_v1
9   synthetic_internal_carbon_price_generation_v1
10  synthetic_internal_carbon_price_generation_v1
11  synthetic_internal_carbon_price_generation_v1

Carbon Credits

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# CONFIG
# =========================================================
rng = np.random.default_rng(42)

DATA_DIR = Path("Data")
OUTPUT_PATH = DATA_DIR / "carbon_credits_raw.csv"

reporting_years = list(range(2019, 2025))

STANDARDS = ["Gold_Standard", "VCS", "CDM", "CAR"]
STANDARD_P = [0.35, 0.40, 0.15, 0.10]

PROJECT_TYPES = [
    "forestry_REDD",
    "renewable_energy",
    "methane_capture",
    "cookstoves",
    "blue_carbon",
]
PROJECT_P = [0.30, 0.30, 0.20, 0.12, 0.08]

CREDIT_TYPES = ["avoidance_reduction", "carbon_removal"]
CREDIT_TYPE_P = [0.72, 0.28]

# =========================================================
# LOAD DEPENDENCIES
# =========================================================
entity_master = pd.read_csv(DATA_DIR / "entity_master_raw.csv")

utility_bills_path = DATA_DIR / "utility_bills_raw.csv"
emission_factors_path = DATA_DIR / "emission_factors_raw.csv"
esg_kpi_path = DATA_DIR / "esg_kpi_tracker_raw.csv"

utility_bills = pd.read_csv(utility_bills_path) if utility_bills_path.exists() else None
emission_factors = pd.read_csv(emission_factors_path) if emission_factors_path.exists() else None
esg_kpi_tracker = pd.read_csv(esg_kpi_path) if esg_kpi_path.exists() else None

# Clean column names
entity_master.columns = (
    entity_master.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

if utility_bills is not None:
    utility_bills.columns = (
        utility_bills.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

if emission_factors is not None:
    emission_factors.columns = (
        emission_factors.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

if esg_kpi_tracker is not None:
    esg_kpi_tracker.columns = (
        esg_kpi_tracker.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

# =========================================================
# REQUIRED COLUMN CHECKS
# =========================================================
required_entity_cols = [
    "entity_id",
    "legal_name",
    "country_code",
    "in_scope_esg_flag",
]

missing_entity_cols = [
    col for col in required_entity_cols
    if col not in entity_master.columns
]

if missing_entity_cols:
    raise ValueError(f"entity_master is missing columns: {missing_entity_cols}")

# =========================================================
# FILTER IN-SCOPE ENTITIES
# =========================================================
entity_master["in_scope_esg_flag"] = (
    entity_master["in_scope_esg_flag"]
    .astype(str)
    .str.lower()
    .isin(["true", "1", "yes"])
)

entities = (
    entity_master.loc[
        entity_master["in_scope_esg_flag"].eq(True),
        ["entity_id", "legal_name", "country_code"]
    ]
    .dropna(subset=["entity_id", "country_code"])
    .drop_duplicates()
    .reset_index(drop=True)
)

if entities.empty:
    raise ValueError("No in-scope ESG entities found in entity_master_raw.csv")

entities["country_code"] = entities["country_code"].astype(str).str.upper()

# =========================================================
# OPTIONAL: CALCULATE ENTITY-YEAR SCOPE 1 + 2 EMISSIONS
# Used to avoid retiring more credits than operational emissions.
# =========================================================
entity_year_emissions = None

if utility_bills is not None and emission_factors is not None:
    required_utility_cols = [
        "entity_id",
        "country_code",
        "meter_type",
        "billing_period_start",
        "quantity",
    ]

    required_ef_cols = [
        "country_code",
        "year",
        "nace_code",
        "factor_scope",
        "emission_factor",
    ]

    missing_utility_cols = [
        col for col in required_utility_cols
        if col not in utility_bills.columns
    ]

    missing_ef_cols = [
        col for col in required_ef_cols
        if col not in emission_factors.columns
    ]

    if not missing_utility_cols and not missing_ef_cols:
        utility = utility_bills.copy()

        utility["billing_period_start"] = pd.to_datetime(
            utility["billing_period_start"]
        )

        utility["reporting_year"] = utility["billing_period_start"].dt.year
        utility["country_code"] = utility["country_code"].astype(str).str.upper()

        emission_factors["country_code"] = (
            emission_factors["country_code"]
            .astype(str)
            .str.upper()
        )

        emission_factors["nace_code"] = (
            emission_factors["nace_code"]
            .astype(str)
            .str.upper()
        )

        emission_factors["factor_scope"] = (
            emission_factors["factor_scope"]
            .astype(str)
            .str.lower()
        )

        # Grid electricity factors
        grid_factors = (
            emission_factors[
                emission_factors["nace_code"].eq("GRID_ELECTRICITY")
                & emission_factors["factor_scope"].eq("scope2")
            ][["country_code", "year", "emission_factor"]]
            .drop_duplicates(subset=["country_code", "year"])
            .rename(
                columns={
                    "year": "reporting_year",
                    "emission_factor": "grid_tco2e_per_mwh",
                }
            )
        )

        # Fuel factors
        fuel_factors = (
            emission_factors[
                emission_factors["nace_code"].isin(
                    ["FUEL_NATGAS", "FUEL_DIESEL"]
                )
                & emission_factors["factor_scope"].eq("scope1")
            ][["country_code", "year", "nace_code", "emission_factor"]]
            .drop_duplicates(subset=["country_code", "year", "nace_code"])
            .rename(
                columns={
                    "year": "reporting_year",
                    "nace_code": "fuel_code",
                    "emission_factor": "fuel_tco2e_per_mwh",
                }
            )
        )

        fuel_factors["fuel_code"] = fuel_factors["fuel_code"].astype(str).str.upper()

        # Electricity Scope 2
        electricity = utility[
            utility["meter_type"].eq("electricity")
        ].copy()

        electricity = electricity.merge(
            grid_factors,
            on=["country_code", "reporting_year"],
            how="left"
        )

        electricity["scope2_tco2e"] = (
            electricity["quantity"]
            / 1000
            * electricity["grid_tco2e_per_mwh"]
        )

        # Natural gas Scope 1
        gas = utility[
            utility["meter_type"].eq("natural_gas")
        ].copy()

        gas["fuel_code"] = "FUEL_NATGAS"

        gas = gas.merge(
            fuel_factors,
            on=["country_code", "reporting_year", "fuel_code"],
            how="left"
        )

        gas["scope1_tco2e"] = (
            gas["quantity"]
            / 1000
            * gas["fuel_tco2e_per_mwh"]
        )

        # Diesel Scope 1
        diesel = utility[
            utility["meter_type"].eq("diesel_fleet")
        ].copy()

        diesel["fuel_code"] = "FUEL_DIESEL"

        diesel = diesel.merge(
            fuel_factors,
            on=["country_code", "reporting_year", "fuel_code"],
            how="left"
        )

        diesel["scope1_tco2e"] = (
            diesel["quantity"]
            * 10
            / 1000
            * diesel["fuel_tco2e_per_mwh"]
        )

        scope1 = (
            pd.concat([
                gas[["entity_id", "reporting_year", "scope1_tco2e"]],
                diesel[["entity_id", "reporting_year", "scope1_tco2e"]],
            ])
            .groupby(["entity_id", "reporting_year"], as_index=False)
            ["scope1_tco2e"]
            .sum()
        )

        scope2 = (
            electricity
            .groupby(["entity_id", "reporting_year"], as_index=False)
            ["scope2_tco2e"]
            .sum()
        )

        entity_year_emissions = scope1.merge(
            scope2,
            on=["entity_id", "reporting_year"],
            how="outer"
        ).fillna(0)

        entity_year_emissions["scope12_tco2e"] = (
            entity_year_emissions["scope1_tco2e"]
            + entity_year_emissions["scope2_tco2e"]
        )

# =========================================================
# FALLBACK EMISSION CAP IF UTILITY-BASED CALC IS NOT AVAILABLE
# =========================================================
if entity_year_emissions is None or entity_year_emissions.empty:
    fallback_rows = []

    for _, entity in entities.iterrows():
        base_emissions = rng.uniform(2_000, 25_000)

        for year in reporting_years:
            trend = 1 - 0.03 * (year - 2019)
            noise = rng.uniform(0.90, 1.10)

            fallback_rows.append({
                "entity_id": entity["entity_id"],
                "reporting_year": year,
                "scope1_tco2e": np.nan,
                "scope2_tco2e": np.nan,
                "scope12_tco2e": max(base_emissions * trend * noise, 100),
            })

    entity_year_emissions = pd.DataFrame(fallback_rows)

# Make lookup for cap
emission_cap_lookup = {
    (row["entity_id"], int(row["reporting_year"])): float(row["scope12_tco2e"])
    for _, row in entity_year_emissions.iterrows()
}

# =========================================================
# GENERATE CARBON CREDITS
# =========================================================
rows = []
credit_counter = 1

for _, entity in entities.iterrows():
    entity_id = entity["entity_id"]

    cumulative_available_credits = 0.0

    for year in reporting_years:
        # The cap is total operational Scope 1 + 2 emissions.
        # To stay realistic, annual retired volume should usually be below this.
        annual_emissions_cap = emission_cap_lookup.get(
            (entity_id, year),
            rng.uniform(2_000, 25_000)
        )

        annual_retired_so_far = 0.0

        # Number of transactions grows over time
        n_transactions = int(
            rng.integers(
                int(30 + (year - 2019) * 15),
                int(80 + (year - 2019) * 35)
            )
        )

        for _ in range(n_transactions):
            standard = rng.choice(STANDARDS, p=STANDARD_P)
            project_type = rng.choice(PROJECT_TYPES, p=PROJECT_P)
            credit_type = rng.choice(CREDIT_TYPES, p=CREDIT_TYPE_P)

            vintage_year = int(
                rng.integers(
                    max(2015, year - 6),
                    year + 1
                )
            )

            volume = float(
                np.clip(
                    rng.lognormal(mean=np.log(500), sigma=1.2),
                    10,
                    50_000
                )
            )

            # Removal credits usually cost more
            base_price = 18 if credit_type == "carbon_removal" else 12

            price = float(
                rng.uniform(
                    base_price * 0.7,
                    base_price * 1.8
                )
            )

            # Decide purchased or retired.
            # Retired volume cannot exceed available credits
            # and cannot exceed entity-year operational emissions cap.
            can_retire = (
                cumulative_available_credits > 10
                and annual_retired_so_far < annual_emissions_cap
            )

            if can_retire and rng.random() < 0.65:
                remaining_emissions_cap = (
                    annual_emissions_cap
                    - annual_retired_so_far
                )

                retire_volume = min(
                    volume,
                    cumulative_available_credits,
                    remaining_emissions_cap
                )

                # If cap is almost exhausted, make this a purchase instead
                if retire_volume <= 0:
                    status = "purchased"
                    cumulative_available_credits += volume
                else:
                    status = "retired"
                    volume = retire_volume
                    annual_retired_so_far += volume
                    cumulative_available_credits -= volume

            else:
                status = "purchased"
                cumulative_available_credits += volume

            rows.append({
                "credit_id": f"CC-{credit_counter:08d}",
                "entity_id": entity_id,
                "entity_legal_name": entity["legal_name"],
                "country_code": entity["country_code"],
                "reporting_year": year,

                "standard": standard,
                "project_type": project_type,
                "credit_type": credit_type,
                "vintage_year": vintage_year,

                "volume_tco2e": round(volume, 2),
                "price_eur_per_tco2e": round(price, 2),
                "total_cost_eur": round(volume * price, 2),

                "status": status,
                "registry_serial": (
                    f"{standard[:3].upper()}-{vintage_year}-"
                    f"{rng.integers(100_000, 999_999)}"
                ),

                "additionality_verified": bool(
                    rng.choice(
                        [True, False],
                        p=[0.88, 0.12]
                    )
                ),

                "permanence_rating": rng.choice(
                    ["high", "medium", "low"],
                    p=[0.50, 0.35, 0.15]
                ),

                "use_case": rng.choice(
                    [
                        "operational_emissions_offset",
                        "carbon_neutral_product",
                        "client_solution_inventory",
                    ],
                    p=[0.60, 0.20, 0.20]
                ),

                "currency": "EUR",
                "data_source": "synthetic_carbon_credit_registry",
                "created_from": "synthetic_carbon_credits_generation_v1",
            })

            credit_counter += 1

carbon_credits = pd.DataFrame(rows)

# =========================================================
# VALIDATION
# =========================================================
valid_entity_ids = set(entity_master["entity_id"].astype(str))

# 1) Cumulative retired volume per entity cannot exceed cumulative purchased
cumulative_violations = 0

for entity_id, group in carbon_credits.groupby("entity_id"):
    group = group.sort_values(["reporting_year", "credit_id"]).copy()

    available = 0.0

    for _, row in group.iterrows():
        volume = float(row["volume_tco2e"])

        if row["status"] == "purchased":
            available += volume

        elif row["status"] == "retired":
            available -= volume

        if available < -0.01:
            cumulative_violations += 1

# 2) Retired volume should not exceed Scope 1+2 emissions per entity-year
retired_by_entity_year = (
    carbon_credits[
        carbon_credits["status"].eq("retired")
    ]
    .groupby(["entity_id", "reporting_year"], as_index=False)
    ["volume_tco2e"]
    .sum()
    .rename(columns={"volume_tco2e": "retired_volume_tco2e"})
)

retired_check = retired_by_entity_year.merge(
    entity_year_emissions[
        ["entity_id", "reporting_year", "scope12_tco2e"]
    ],
    on=["entity_id", "reporting_year"],
    how="left"
)

retired_exceeds_scope12 = int(
    (
        retired_check["retired_volume_tco2e"]
        > retired_check["scope12_tco2e"]
    ).sum()
)

additionality_false_rate = (
    carbon_credits["additionality_verified"].eq(False).mean()
    * 100
)

validation = {
    "rows": len(carbon_credits),
    "entities_covered": carbon_credits["entity_id"].nunique(),
    "years_covered": sorted(carbon_credits["reporting_year"].unique().tolist()),
    "unique_credit_id": int(carbon_credits["credit_id"].is_unique),
    "unique_registry_serial": int(carbon_credits["registry_serial"].is_unique),

    "entity_id_missing_from_entity_master": int(
        (~carbon_credits["entity_id"].astype(str).isin(valid_entity_ids)).sum()
    ),

    "volume_non_positive": int(
        (carbon_credits["volume_tco2e"] <= 0).sum()
    ),

    "price_non_positive": int(
        (carbon_credits["price_eur_per_tco2e"] <= 0).sum()
    ),

    "total_cost_recalculation_errors": int(
        (
            np.abs(
                carbon_credits["total_cost_eur"]
                - carbon_credits["volume_tco2e"] * carbon_credits["price_eur_per_tco2e"]
            )
            > 1.0
        ).sum()
    ),

    "future_vintage_year_rows": int(
        (
            carbon_credits["vintage_year"]
            > carbon_credits["reporting_year"]
        ).sum()
    ),

    "cumulative_retired_exceeds_purchased_violations": int(
        cumulative_violations
    ),

    "entity_year_retired_exceeds_scope12_emissions": int(
        retired_exceeds_scope12
    ),

    "additionality_false_rate_pct": round(
        additionality_false_rate,
        2
    ),

    "additionality_false_rate_above_15pct": int(
        additionality_false_rate > 15
    ),

    "non_eur_currency_rows": int(
        (~carbon_credits["currency"].eq("EUR")).sum()
    ),
}

# =========================================================
# SAVE OUTPUT
# =========================================================
carbon_credits.to_csv(OUTPUT_PATH, index=False)

print(f"Generated: {OUTPUT_PATH}")

print("\nValidation:")
for key, value in validation.items():
    print(f"{key}: {value}")

print("\nPreview:")
print(carbon_credits.head(12))

Generated: Data\carbon_credits_raw.csv

Validation:
rows: 7234
entities_covered: 10
years_covered: [2019, 2020, 2021, 2022, 2023, 2024]
unique_credit_id: 1
unique_registry_serial: 0
entity_id_missing_from_entity_master: 0
volume_non_positive: 0
price_non_positive: 0
total_cost_recalculation_errors: 3619
future_vintage_year_rows: 0
cumulative_retired_exceeds_purchased_violations: 1
entity_year_retired_exceeds_scope12_emissions: 32
additionality_false_rate_pct: 12.1
additionality_false_rate_above_15pct: 0
non_eur_currency_rows: 0

Preview:
      credit_id      entity_id       entity_legal_name country_code  \
0   CC-00000001  ENT-GROUP-001  Atlas Banking Group SA           FR
1   CC-00000002  ENT-GROUP-001  Atlas Banking Group SA           FR
2   CC-00000003  ENT-GROUP-001  Atlas Banking Group SA           FR
3   CC-00000004  ENT-GROUP-001  Atlas Banking Group SA           FR
4   CC-00000005  ENT-GROUP-001  Atlas Banking Group SA           FR
5   CC-00000006  ENT-GROUP-001  Atlas Banking Group SA           FR
6   CC-00000007  ENT-GROUP-001  Atlas Banking Group SA           FR
7   CC-00000008  ENT-GROUP-001  Atlas Banking Group SA           FR
8   CC-00000009  ENT-GROUP-001  Atlas Banking Group SA           FR
9   CC-00000010  ENT-GROUP-001  Atlas Banking Group SA           FR
10  CC-00000011  ENT-GROUP-001  Atlas Banking Group SA           FR
11  CC-00000012  ENT-GROUP-001  Atlas Banking Group SA           FR

    reporting_year       standard      project_type          credit_type  \
0             2019            CDM   methane_capture  avoidance_reduction
1             2019            CAR   methane_capture       carbon_removal
2             2019            VCS       blue_carbon       carbon_removal
3             2019            VCS       blue_carbon  avoidance_reduction
4             2019            VCS        cookstoves  avoidance_reduction
5             2019  Gold_Standard     forestry_REDD       carbon_removal
6             2019            VCS  renewable_energy  avoidance_reduction
7             2019  Gold_Standard  renewable_energy       carbon_removal
8             2019            VCS  renewable_energy       carbon_removal
9             2019  Gold_Standard   methane_capture  avoidance_reduction
10            2019            CAR   methane_capture  avoidance_reduction
11            2019            CAR  renewable_energy  avoidance_reduction

    vintage_year  volume_tco2e  price_eur_per_tco2e  total_cost_eur  \
0           2017        104.79                18.45         1933.13
1           2018        104.79                17.10         1791.90
2           2015        299.05                16.45         4920.54
3           2017        188.31                14.60         2748.95
4           2015        959.48                19.39        18600.35
5           2016       1066.52                26.56        28329.13
6           2017        334.54                16.78         5612.95
7           2017        128.34                13.75         1765.20
8           2016        225.95                13.05         2948.53
9           2018        418.78                12.38         5184.48
10          2016       2377.21                18.68        44405.09
11          2018        842.11                16.05        13512.32

       status  registry_serial  additionality_verified permanence_rating  \
0   purchased  CDM-2017-745728                    True              high
1     retired  CAR-2018-899099                    True            medium
2   purchased  VCS-2015-427515                    True              high
3     retired  VCS-2017-516646                    True              high
4   purchased  VCS-2015-857521                    True            medium
5   purchased  GOL-2016-600081                    True              high
6     retired  VCS-2017-181509                    True              high
7     retired  GOL-2017-925886                    True            medium
8     retired  VCS-2016-794396                    True              high
9     retired  GOL-2018-646476                    True              high
10  purchased  CAR-2016-335025                    True              high
11  purchased  CAR-2018-592215                    True            medium

                        use_case currency                       data_source  \
0   operational_emissions_offset      EUR  synthetic_carbon_credit_registry
1         carbon_neutral_product      EUR  synthetic_carbon_credit_registry
2         carbon_neutral_product      EUR  synthetic_carbon_credit_registry
3         carbon_neutral_product      EUR  synthetic_carbon_credit_registry
4   operational_emissions_offset      EUR  synthetic_carbon_credit_registry
5   operational_emissions_offset      EUR  synthetic_carbon_credit_registry
6   operational_emissions_offset      EUR  synthetic_carbon_credit_registry
7         carbon_neutral_product      EUR  synthetic_carbon_credit_registry
8   operational_emissions_offset      EUR  synthetic_carbon_credit_registry
9      client_solution_inventory      EUR  synthetic_carbon_credit_registry
10  operational_emissions_offset      EUR  synthetic_carbon_credit_registry
11        carbon_neutral_product      EUR  synthetic_carbon_credit_registry

                              created_from
0   synthetic_carbon_credits_generation_v1
1   synthetic_carbon_credits_generation_v1
2   synthetic_carbon_credits_generation_v1
3   synthetic_carbon_credits_generation_v1
4   synthetic_carbon_credits_generation_v1
5   synthetic_carbon_credits_generation_v1
6   synthetic_carbon_credits_generation_v1
7   synthetic_carbon_credits_generation_v1
8   synthetic_carbon_credits_generation_v1
9   synthetic_carbon_credits_generation_v1
10  synthetic_carbon_credits_generation_v1
11  synthetic_carbon_credits_generation_v1

Global warming potential reference

In [3]:
import pandas as pd
from pathlib import Path

# =========================================================
# CONFIG
# =========================================================
DATA_DIR = Path("Data")

GWP_OUTPUT_PATH = DATA_DIR / "gwp_reference_raw.csv"
EMISSION_FACTORS_PATH = DATA_DIR / "emission_factors_raw.csv"

# =========================================================
# STATIC GWP REFERENCE TABLE
# =========================================================
gwp_reference = pd.DataFrame([
    {
        "gas_id": "GWP-001",
        "gas_name": "Carbon dioxide",
        "chemical_formula": "CO2",
        "gwp_ar5_100yr": 1,
        "gwp_ar6_100yr": 1,
        "atmospheric_lifetime_years": "Variable (centuries)",
        "primary_source_sector": "Energy combustion, industrial processes",
        "kyoto_protocol_gas": True,
        "gwp_basis": "IPCC_AR6",
        "reference_source": "IPCC_AR6_WG1_Chapter_7",
    },
    {
        "gas_id": "GWP-002",
        "gas_name": "Methane",
        "chemical_formula": "CH4",
        "gwp_ar5_100yr": 28,
        "gwp_ar6_100yr": 27.9,
        "atmospheric_lifetime_years": "11.8",
        "primary_source_sector": "Agriculture, natural gas systems, waste",
        "kyoto_protocol_gas": True,
        "gwp_basis": "IPCC_AR6",
        "reference_source": "IPCC_AR6_WG1_Chapter_7",
    },
    {
        "gas_id": "GWP-003",
        "gas_name": "Nitrous oxide",
        "chemical_formula": "N2O",
        "gwp_ar5_100yr": 265,
        "gwp_ar6_100yr": 273,
        "atmospheric_lifetime_years": "109",
        "primary_source_sector": "Agriculture, wastewater, combustion",
        "kyoto_protocol_gas": True,
        "gwp_basis": "IPCC_AR6",
        "reference_source": "IPCC_AR6_WG1_Chapter_7",
    },
    {
        "gas_id": "GWP-004",
        "gas_name": "Hydrofluorocarbons",
        "chemical_formula": "HFCs",
        "gwp_ar5_100yr": 1300,
        "gwp_ar6_100yr": 1530,
        "atmospheric_lifetime_years": "Variable by compound",
        "primary_source_sector": "Refrigeration, air conditioning, foam blowing",
        "kyoto_protocol_gas": True,
        "gwp_basis": "IPCC_AR6",
        "reference_source": "IPCC_AR6_WG1_Chapter_7",
        "note": "Representative value using HFC-134a. Actual GWP varies by compound.",
    },
    {
        "gas_id": "GWP-005",
        "gas_name": "Perfluorocarbons",
        "chemical_formula": "PFCs",
        "gwp_ar5_100yr": 6630,
        "gwp_ar6_100yr": 7380,
        "atmospheric_lifetime_years": "Variable, thousands of years",
        "primary_source_sector": "Aluminium production, semiconductor manufacturing",
        "kyoto_protocol_gas": True,
        "gwp_basis": "IPCC_AR6",
        "reference_source": "IPCC_AR6_WG1_Chapter_7",
        "note": "Representative value using CF4. Actual GWP varies by compound.",
    },
    {
        "gas_id": "GWP-006",
        "gas_name": "Sulphur hexafluoride",
        "chemical_formula": "SF6",
        "gwp_ar5_100yr": 23500,
        "gwp_ar6_100yr": 25200,
        "atmospheric_lifetime_years": "3200",
        "primary_source_sector": "Electrical transmission, semiconductor manufacturing",
        "kyoto_protocol_gas": True,
        "gwp_basis": "IPCC_AR6",
        "reference_source": "IPCC_AR6_WG1_Chapter_7",
    },
    {
        "gas_id": "GWP-007",
        "gas_name": "Nitrogen trifluoride",
        "chemical_formula": "NF3",
        "gwp_ar5_100yr": 16100,
        "gwp_ar6_100yr": 17400,
        "atmospheric_lifetime_years": "569",
        "primary_source_sector": "Semiconductor and flat panel display manufacturing",
        "kyoto_protocol_gas": True,
        "gwp_basis": "IPCC_AR6",
        "reference_source": "IPCC_AR6_WG1_Chapter_7",
    },
])

# Fill missing note column values
if "note" not in gwp_reference.columns:
    gwp_reference["note"] = None
else:
    gwp_reference["note"] = gwp_reference["note"].fillna("")

# =========================================================
# SAVE GWP REFERENCE TABLE
# =========================================================
gwp_reference.to_csv(GWP_OUTPUT_PATH, index=False)

print(f"Generated: {GWP_OUTPUT_PATH}")
print(f"Rows: {len(gwp_reference)}")
print(gwp_reference)

# =========================================================
# UPDATE emission_factors_raw.csv WITH gwp_basis
# =========================================================
if EMISSION_FACTORS_PATH.exists():
    emission_factors = pd.read_csv(EMISSION_FACTORS_PATH)

    # Clean column names but preserve data
    emission_factors.columns = (
        emission_factors.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

    # Add GWP basis column
    emission_factors["gwp_basis"] = "IPCC_AR6"

    # Optional: add a reference link column to the GWP reference table
    emission_factors["gwp_reference_table"] = "gwp_reference_raw.csv"

    emission_factors.to_csv(EMISSION_FACTORS_PATH, index=False)

    print(f"\nUpdated: {EMISSION_FACTORS_PATH}")
    print("Added columns: gwp_basis, gwp_reference_table")
    print(emission_factors.head())

else:
    print(f"\nWarning: {EMISSION_FACTORS_PATH} not found. GWP reference table was created, but emission_factors was not updated.")

Generated: Data\gwp_reference_raw.csv
Rows: 7
    gas_id              gas_name chemical_formula  gwp_ar5_100yr  \
0  GWP-001        Carbon dioxide              CO2              1
1  GWP-002               Methane              CH4             28
2  GWP-003         Nitrous oxide              N2O            265
3  GWP-004    Hydrofluorocarbons             HFCs           1300
4  GWP-005      Perfluorocarbons             PFCs           6630
5  GWP-006  Sulphur hexafluoride              SF6          23500
6  GWP-007  Nitrogen trifluoride              NF3          16100

   gwp_ar6_100yr    atmospheric_lifetime_years  \
0            1.0          Variable (centuries)
1           27.9                          11.8
2          273.0                           109
3         1530.0          Variable by compound
4         7380.0  Variable, thousands of years
5        25200.0                          3200
6        17400.0                           569

                               primary_source_sector  kyoto_protocol_gas  \
0            Energy combustion, industrial processes                True
1            Agriculture, natural gas systems, waste                True
2                Agriculture, wastewater, combustion                True
3      Refrigeration, air conditioning, foam blowing                True
4  Aluminium production, semiconductor manufacturing                True
5  Electrical transmission, semiconductor manufac...                True
6  Semiconductor and flat panel display manufactu...                True

  gwp_basis        reference_source  \
0  IPCC_AR6  IPCC_AR6_WG1_Chapter_7
1  IPCC_AR6  IPCC_AR6_WG1_Chapter_7
2  IPCC_AR6  IPCC_AR6_WG1_Chapter_7
3  IPCC_AR6  IPCC_AR6_WG1_Chapter_7
4  IPCC_AR6  IPCC_AR6_WG1_Chapter_7
5  IPCC_AR6  IPCC_AR6_WG1_Chapter_7
6  IPCC_AR6  IPCC_AR6_WG1_Chapter_7

                                                note
0
1
2
3  Representative value using HFC-134a. Actual GW...
4  Representative value using CF4. Actual GWP var...
5
6

Updated: Data\emission_factors_raw.csv
Added columns: gwp_basis, gwp_reference_table
                            factor_id         nace_code  year country_code  \
0  EF-GRID_ELECTRICITY-2019-BE-SCOPE2  GRID_ELECTRICITY  2019           BE
1  EF-GRID_ELECTRICITY-2020-BE-SCOPE2  GRID_ELECTRICITY  2020           BE
2  EF-GRID_ELECTRICITY-2021-BE-SCOPE2  GRID_ELECTRICITY  2021           BE
3  EF-GRID_ELECTRICITY-2022-BE-SCOPE2  GRID_ELECTRICITY  2022           BE
4  EF-GRID_ELECTRICITY-2023-BE-SCOPE2  GRID_ELECTRICITY  2023           BE

  factor_scope  emission_factor       unit source  pcaf_quality_score  \
0       scope2          0.20825  tCO2e/MWh    IEA                   3
1       scope2          0.20060  tCO2e/MWh    IEA                   3
2       scope2          0.19295  tCO2e/MWh    IEA                   3
3       scope2          0.18530  tCO2e/MWh    IEA                   3
4       scope2          0.17765  tCO2e/MWh    IEA                   3

  last_updated gwp_basis    gwp_reference_table
0   2026-05-07  IPCC_AR6  gwp_reference_raw.csv
1   2026-05-07  IPCC_AR6  gwp_reference_raw.csv
2   2026-05-07  IPCC_AR6  gwp_reference_raw.csv
3   2026-05-07  IPCC_AR6  gwp_reference_raw.csv
4   2026-05-07  IPCC_AR6  gwp_reference_raw.csv

Policy Reference