In [47]:
import pandas as pd
import numpy as np
import random
from typing import List, Dict, Any

random.seed(42)
np.random.seed(42)

In [2]:
companies = [
    {"company_id": "C001", "company_name": "NorthBank Tunis", "sector": "Banking", "subsector": "Commercial Banks", "country": "Tunisia"},
    {"company_id": "C002", "company_name": "MedInsure", "sector": "Insurance", "subsector": "Non-life Insurance", "country": "Tunisia"},
    {"company_id": "C003", "company_name": "TransLog Africa", "sector": "Transportation", "subsector": "Logistics & Freight", "country": "Tunisia"},
    {"company_id": "C004", "company_name": "IndusCem", "sector": "Industrial", "subsector": "Construction Materials", "country": "Tunisia"},
]

years = list(range(2020, 2025))

company_years = pd.DataFrame(
    [
        {
            "company_id": c["company_id"],
            "company_name": c["company_name"],
            "sector": c["sector"],
            "subsector": c["subsector"],
            "country": c["country"],
            "reporting_year": y
        }
        for c in companies
        for y in years
    ]
)

company_years.head()

,company_id,company_name,sector,subsector,country,reporting_year
0,C001,NorthBank Tunis,Banking,Commercial Banks,Tunisia,2020
1,C001,NorthBank Tunis,Banking,Commercial Banks,Tunisia,2021
2,C001,NorthBank Tunis,Banking,Commercial Banks,Tunisia,2022
3,C001,NorthBank Tunis,Banking,Commercial Banks,Tunisia,2023
4,C001,NorthBank Tunis,Banking,Commercial Banks,Tunisia,2024

In [3]:
def generate_energy_raw(row):
    sector = row["sector"]

    if sector == "Banking":
        diesel = np.random.uniform(2000, 12000)
        gas = np.random.uniform(500, 3000)
        electricity = np.random.uniform(2000, 12000)
    elif sector == "Insurance":
        diesel = np.random.uniform(1000, 8000)
        gas = np.random.uniform(300, 2000)
        electricity = np.random.uniform(1500, 9000)
    elif sector == "Transportation":
        diesel = np.random.uniform(80000, 400000)
        gas = np.random.uniform(1000, 5000)
        electricity = np.random.uniform(3000, 15000)
    else:  # Industrial
        diesel = np.random.uniform(30000, 150000)
        gas = np.random.uniform(20000, 100000)
        electricity = np.random.uniform(20000, 120000)

    return {
        "company_id": row["company_id"],
        "reporting_year": row["reporting_year"],
        "diesel_liters": round(diesel, 2),
        "natural_gas_mwh": round(gas, 2),
        "electricity_purchased_mwh": round(electricity, 2),
        "electricity_renewable_mwh": round(electricity * np.random.uniform(0.05, 0.4), 2),
        "refrigerant_leak_kg": round(np.random.uniform(5, 150), 2),
        "emission_factor_source": random.choice(["DEFRA", "EPA", "National Grid Database"]),
        "boundary_type": random.choice(["operational_control", "financial_control"]),
        "data_quality_level": random.choice(["high", "medium", "medium", "low"])
    }

energy_raw_df = pd.DataFrame([generate_energy_raw(r) for _, r in company_years.iterrows()])
energy_raw_df.head()

,company_id,reporting_year,diesel_liters,natural_gas_mwh,electricity_purchased_mwh,electricity_renewable_mwh,refrigerant_leak_kg,emission_factor_source,boundary_type,data_quality_level
0,C001,2020,5745.40,2876.79,9319.94,2418.81,27.62,National Grid Database,operational_control,high
1,C001,2021,3559.95,645.21,10661.76,2776.22,107.67,National Grid Database,financial_control,medium
2,C001,2022,2205.84,2924.77,10324.43,1283.52,31.36,DEFRA,operational_control,high
3,C001,2023,3834.05,1260.61,7247.56,1458.07,47.23,National Grid Database,operational_control,low
4,C001,2024,8118.53,848.73,4921.45,877.13,71.13,DEFRA,operational_control,high

In [37]:
energy_raw_df.to_csv("energy_raw_df.csv", index=False)
print("Saved: energy_raw_df.csv")

Saved: energy_raw_df.csv

In [4]:
def generate_scope3_raw(row):
    sector = row["sector"]

    if sector == "Banking":
        financed = np.random.uniform(100000, 800000)
        purchased_goods = np.random.uniform(500000, 3000000)
        business_travel = np.random.uniform(200000, 1000000)
    elif sector == "Insurance":
        financed = np.random.uniform(50000, 300000)
        purchased_goods = np.random.uniform(300000, 1500000)
        business_travel = np.random.uniform(100000, 500000)
    elif sector == "Transportation":
        financed = np.random.uniform(10000, 50000)
        purchased_goods = np.random.uniform(1000000, 5000000)
        business_travel = np.random.uniform(50000, 300000)
    else:
        financed = np.random.uniform(10000, 70000)
        purchased_goods = np.random.uniform(2000000, 8000000)
        business_travel = np.random.uniform(50000, 250000)

    return {
        "company_id": row["company_id"],
        "reporting_year": row["reporting_year"],
        "scope3_cat1_purchased_goods_spend_usd": round(purchased_goods, 2),
        "scope3_cat6_business_travel_km": round(business_travel, 2),
        "scope3_cat7_employee_commuting_km": round(np.random.uniform(100000, 800000), 2),
        "scope3_cat15_financed_activity_value": round(financed, 2),
        "scope3_method": random.choice(["spend-based", "activity-based", "supplier-specific", "hybrid"]),
        "scope3_data_quality_level": random.choice(["high", "medium", "medium", "low"])
    }

scope3_raw_df = pd.DataFrame([generate_scope3_raw(r) for _, r in company_years.iterrows()])
scope3_raw_df.head()

,company_id,reporting_year,scope3_cat1_purchased_goods_spend_usd,scope3_cat6_business_travel_km,scope3_cat7_employee_commuting_km,scope3_cat15_financed_activity_value,scope3_method,scope3_data_quality_level
0,C001,2020,2091026.03,451484.78,455999.48,122000.43,supplier-specific,medium
1,C001,2021,1123230.57,528306.34,628885.80,735296.53,supplier-specific,medium
2,C001,2022,692449.77,431801.16,212854.90,260158.72,activity-based,medium
3,C001,2023,2520300.95,706723.01,710022.41,750788.36,spend-based,medium
4,C001,2024,966425.15,914047.20,477539.57,662570.45,activity-based,medium

In [38]:
scope3_raw_df.to_csv("scope3_raw_df.csv", index=False)
print("Saved: scope3_raw_df.csv")

Saved: scope3_raw_df.csv

In [5]:
def generate_finance_raw(row):
    sector = row["sector"]

    if sector == "Banking":
        total_assets = np.random.uniform(5e8, 4e9)
        climate_risk_assets = total_assets * np.random.uniform(0.08, 0.35)
        capex = np.random.uniform(2e6, 2e7)
    elif sector == "Insurance":
        total_assets = np.random.uniform(2e8, 2e9)
        climate_risk_assets = total_assets * np.random.uniform(0.05, 0.25)
        capex = np.random.uniform(1e6, 8e6)
    elif sector == "Transportation":
        total_assets = np.random.uniform(5e7, 8e8)
        climate_risk_assets = total_assets * np.random.uniform(0.15, 0.45)
        capex = np.random.uniform(5e6, 5e7)
    else:
        total_assets = np.random.uniform(1e8, 1.5e9)
        climate_risk_assets = total_assets * np.random.uniform(0.2, 0.5)
        capex = np.random.uniform(1e7, 1e8)

    climate_capex = capex * np.random.uniform(0.05, 0.45)

    return {
        "company_id": row["company_id"],
        "reporting_year": row["reporting_year"],
        "total_assets_usd": round(total_assets, 2),
        "high_climate_risk_assets_usd": round(climate_risk_assets, 2),
        "total_capex_usd": round(capex, 2),
        "climate_related_capex_usd": round(climate_capex, 2),
        "current_climate_loss_usd": round(np.random.uniform(0, capex * 0.2), 2),
        "finance_data_source": random.choice(["ERP", "asset register", "finance consolidation file"])
    }

finance_raw_df = pd.DataFrame([generate_finance_raw(r) for _, r in company_years.iterrows()])
finance_raw_df.head()

,company_id,reporting_year,total_assets_usd,high_climate_risk_assets_usd,total_capex_usd,climate_related_capex_usd,current_climate_loss_usd,finance_data_source
0,C001,2020,1.693732e+09,1.873909e+08,18644485.13,7475240.47,961837.77,ERP
1,C001,2021,2.809944e+09,8.448097e+08,11993614.61,3140650.70,580136.63,ERP
2,C001,2022,8.258597e+08,2.661318e+08,18207525.03,5521260.50,1234578.68,ERP
3,C001,2023,1.722234e+09,4.753503e+08,18147984.68,7346931.57,2830633.89,finance consolidation file
4,C001,2024,2.747111e+09,2.821771e+08,4909316.85,2009980.73,595430.48,ERP

In [39]:
finance_raw_df.to_csv("finance_raw_df.csv", index=False)
print("Saved: finance_raw_df.csv")

Saved: finance_raw_df.csv

In [6]:
def generate_risk_register_raw(row):
    sector = row["sector"]

    risks = {
        "Banking": [
            "Carbon-intensive portfolio exposure",
            "Flood exposure of financed real estate",
            "Regulatory climate disclosure non-compliance"
        ],
        "Insurance": [
            "Increase in catastrophe claims",
            "Underpricing of climate-related underwriting risk",
            "Regulatory reporting gap"
        ],
        "Transportation": [
            "Fuel price and carbon cost exposure",
            "Fleet transition delay",
            "Physical disruption from extreme heat"
        ],
        "Industrial": [
            "Carbon-intensive production exposure",
            "Water stress affecting operations",
            "Transition cost from emissions regulation"
        ]
    }

    risk_desc = random.choice(risks[sector])
    likelihood = random.randint(1, 5)
    magnitude = random.randint(1, 5)

    return {
        "company_id": row["company_id"],
        "reporting_year": row["reporting_year"],
        "risk_description": risk_desc,
        "risk_type": random.choice(["physical", "transition"]),
        "likelihood_score": likelihood,
        "magnitude_score": magnitude,
        "time_horizon": random.choice(["short-term", "medium-term", "long-term"]),
        "prioritization_method": random.choice(["likelihood_x_magnitude", "expert judgement", "multi-factor scoring"]),
        "mitigation_plan_exists": random.choice([True, True, False]),
        "risk_owner_function": random.choice(["risk", "finance", "operations", "sustainability"])
    }

risk_raw_df = pd.DataFrame([generate_risk_register_raw(r) for _, r in company_years.iterrows()])
risk_raw_df.head()

,company_id,reporting_year,risk_description,risk_type,likelihood_score,magnitude_score,time_horizon,prioritization_method,mitigation_plan_exists,risk_owner_function
0,C001,2020,Regulatory climate disclosure non-compliance,transition,5,3,short-term,expert judgement,True,finance
1,C001,2021,Flood exposure of financed real estate,physical,1,3,long-term,likelihood_x_magnitude,False,operations
2,C001,2022,Regulatory climate disclosure non-compliance,physical,5,5,short-term,expert judgement,True,risk
3,C001,2023,Regulatory climate disclosure non-compliance,physical,3,4,short-term,expert judgement,True,finance
4,C001,2024,Carbon-intensive portfolio exposure,physical,2,5,short-term,multi-factor scoring,True,risk

In [40]:
risk_raw_df.to_csv("risk_raw_df.csv", index=False)
print("Saved: risk_raw_df.csv")

Saved: risk_raw_df.csv

In [41]:
def pick_one(options):
    return random.choice(options)

def pick_yes_no(prob_yes=0.7):
    return random.random() < prob_yes

In [42]:
energy_raw_df.head()

,company_id,reporting_year,diesel_liters,natural_gas_mwh,electricity_purchased_mwh,electricity_renewable_mwh,refrigerant_leak_kg,emission_factor_source,boundary_type,data_quality_level
0,C001,2020,5745.40,2876.79,9319.94,2418.81,27.62,National Grid Database,operational_control,high
1,C001,2021,3559.95,645.21,10661.76,2776.22,107.67,National Grid Database,financial_control,medium
2,C001,2022,2205.84,2924.77,10324.43,1283.52,31.36,DEFRA,operational_control,high
3,C001,2023,3834.05,1260.61,7247.56,1458.07,47.23,National Grid Database,operational_control,low
4,C001,2024,8118.53,848.73,4921.45,877.13,71.13,DEFRA,operational_control,high

In [44]:
company_base = energy_raw_df[
    ["company_id", "reporting_year"]
].drop_duplicates().reset_index(drop=True)

company_base.head()

  company_id  reporting_year
0       C001            2020
1       C001            2021
2       C001            2022
3       C001            2023
4       C001            2024

In [45]:
GHG_PROTOCOL_STANDARDS = [
    "GHG Protocol Corporate Standard",
    "GHG Protocol Corporate Accounting and Reporting Standard"
]

CONSOLIDATION_APPROACHES = [
    "operational_control",
    "financial_control",
    "equity_share"
]

SCOPE2_BASIS = [
    "location-based",
    "market-based",
    "both"
]

EF_SOURCES_SCOPE1 = [
    "DEFRA 2024",
    "EPA 2024",
    "IPCC 2006 Guidelines",
    "National emission factor database 2024"
]

EF_SOURCES_SCOPE2 = [
    "National grid factor 2024",
    "IEA electricity emission factors",
    "DEFRA electricity factors 2024",
    "Residual mix supplier factors"
]

EF_SOURCES_SCOPE3 = [
    "EPA EEIO",
    "EXIOBASE",
    "Supplier-specific data",
    "Hybrid method using spend-based and activity-based factors"
]

DATA_QUALITY_NOTES = [
    "high",
    "moderate",
    "mixed"
]

SOURCE_DOC_TYPES = [
    "internal methodology memo",
    "GHG inventory manual",
    "sustainability reporting methodology",
    "emissions calculation protocol"
]

In [48]:
def generate_ghg_methodology_row(base_row: Dict[str, Any]) -> Dict[str, Any]:
    scope2_basis = pick_one(SCOPE2_BASIS)

    scope1_stationary = pick_yes_no(0.9)
    scope1_mobile = pick_yes_no(0.8)
    scope1_refrigerants = pick_yes_no(0.6)

    third_party_verified = pick_yes_no(0.55)

    row = {
        "company_id": base_row["company_id"],
        "reporting_year": base_row["reporting_year"],

        "ghg_protocol_standard": pick_one(GHG_PROTOCOL_STANDARDS),
        "ghg_protocol_version": "revised edition",
        "consolidation_approach": pick_one(CONSOLIDATION_APPROACHES),

        "organizational_boundary_note": "Covers entities included under the selected consolidation approach.",
        "reporting_boundary_note": "Reporting boundary includes material operations and excludes immaterial activities where relevant.",

        "scope1_methodology": "Activity data multiplied by fuel, combustion and refrigerant emission factors.",
        "scope2_methodology": f"Purchased electricity emissions calculated using {scope2_basis} approach.",
        "scope3_methodology": "Scope 3 estimated using a mix of spend-based, activity-based and supplier-specific methods depending on data availability.",

        "scope2_basis_used": scope2_basis,
        "scope1_includes_refrigerants": scope1_refrigerants,
        "scope1_includes_stationary_combustion": scope1_stationary,
        "scope1_includes_mobile_combustion": scope1_mobile,

        "emission_factor_source_scope1": pick_one(EF_SOURCES_SCOPE1),
        "emission_factor_source_scope2": pick_one(EF_SOURCES_SCOPE2),
        "emission_factor_source_scope3": pick_one(EF_SOURCES_SCOPE3),

        "base_year": max(2020, int(base_row["reporting_year"]) - 2),
        "base_year_recalculation_policy": "Base year is recalculated when structural or methodological changes materially affect comparability.",
        "material_exclusions_note": "Non-material sources may be excluded where data is unavailable or immaterial.",
        "estimation_uncertainty_note": "Certain values rely on estimates, proxies, and supplier assumptions where primary data is unavailable.",
        "data_quality_note": pick_one(DATA_QUALITY_NOTES),

        "third_party_verified": third_party_verified,
        "verification_note": (
            "Limited assurance obtained for selected GHG indicators."
            if third_party_verified else
            "No external assurance obtained for methodology disclosures."
        ),

        "source_document_name": f"GHG Methodology Memo {base_row['reporting_year']}",
        "source_document_type": pick_one(SOURCE_DOC_TYPES)
    }

    # Optional passthrough if these columns exist
    for col in ["sector", "subsector", "country", "region"]:
        if col in base_row:
            row[col] = base_row[col]

    return row

In [49]:
ghg_methodology_records = [
    generate_ghg_methodology_row(row)
    for row in company_base.to_dict(orient="records")
]

ghg_methodology_raw_df = pd.DataFrame(ghg_methodology_records)
ghg_methodology_raw_df.head()

,company_id,reporting_year,ghg_protocol_standard,ghg_protocol_version,consolidation_approach,organizational_boundary_note,reporting_boundary_note,scope1_methodology,scope2_methodology,scope3_methodology,...,emission_factor_source_scope3,base_year,base_year_recalculation_policy,material_exclusions_note,estimation_uncertainty_note,data_quality_note,third_party_verified,verification_note,source_document_name,source_document_type
0,C001,2020,GHG Protocol Corporate Standard,revised edition,equity_share,Covers entities included under the selected co...,Reporting boundary includes material operation...,"Activity data multiplied by fuel, combustion a...",Purchased electricity emissions calculated usi...,"Scope 3 estimated using a mix of spend-based, ...",...,EPA EEIO,2020,Base year is recalculated when structural or m...,Non-material sources may be excluded where dat...,"Certain values rely on estimates, proxies, and...",high,True,Limited assurance obtained for selected GHG in...,GHG Methodology Memo 2020,internal methodology memo
1,C001,2021,GHG Protocol Corporate Accounting and Reportin...,revised edition,operational_control,Covers entities included under the selected co...,Reporting boundary includes material operation...,"Activity data multiplied by fuel, combustion a...",Purchased electricity emissions calculated usi...,"Scope 3 estimated using a mix of spend-based, ...",...,EPA EEIO,2020,Base year is recalculated when structural or m...,Non-material sources may be excluded where dat...,"Certain values rely on estimates, proxies, and...",high,False,No external assurance obtained for methodology...,GHG Methodology Memo 2021,emissions calculation protocol
2,C001,2022,GHG Protocol Corporate Accounting and Reportin...,revised edition,operational_control,Covers entities included under the selected co...,Reporting boundary includes material operation...,"Activity data multiplied by fuel, combustion a...",Purchased electricity emissions calculated usi...,"Scope 3 estimated using a mix of spend-based, ...",...,Supplier-specific data,2020,Base year is recalculated when structural or m...,Non-material sources may be excluded where dat...,"Certain values rely on estimates, proxies, and...",high,True,Limited assurance obtained for selected GHG in...,GHG Methodology Memo 2022,emissions calculation protocol
3,C001,2023,GHG Protocol Corporate Accounting and Reportin...,revised edition,equity_share,Covers entities included under the selected co...,Reporting boundary includes material operation...,"Activity data multiplied by fuel, combustion a...",Purchased electricity emissions calculated usi...,"Scope 3 estimated using a mix of spend-based, ...",...,EPA EEIO,2021,Base year is recalculated when structural or m...,Non-material sources may be excluded where dat...,"Certain values rely on estimates, proxies, and...",mixed,True,Limited assurance obtained for selected GHG in...,GHG Methodology Memo 2023,GHG inventory manual
4,C001,2024,GHG Protocol Corporate Accounting and Reportin...,revised edition,equity_share,Covers entities included under the selected co...,Reporting boundary includes material operation...,"Activity data multiplied by fuel, combustion a...",Purchased electricity emissions calculated usi...,"Scope 3 estimated using a mix of spend-based, ...",...,Supplier-specific data,2022,Base year is recalculated when structural or m...,Non-material sources may be excluded where dat...,"Certain values rely on estimates, proxies, and...",moderate,True,Limited assurance obtained for selected GHG in...,GHG Methodology Memo 2024,GHG inventory manual

In [50]:
print(ghg_methodology_raw_df.shape)
ghg_methodology_raw_df.isna().sum()

(20, 26)

company_id                               0
reporting_year                           0
ghg_protocol_standard                    0
ghg_protocol_version                     0
consolidation_approach                   0
organizational_boundary_note             0
reporting_boundary_note                  0
scope1_methodology                       0
scope2_methodology                       0
scope3_methodology                       0
scope2_basis_used                        0
scope1_includes_refrigerants             0
scope1_includes_stationary_combustion    0
scope1_includes_mobile_combustion        0
emission_factor_source_scope1            0
emission_factor_source_scope2            0
emission_factor_source_scope3            0
base_year                                0
base_year_recalculation_policy           0
material_exclusions_note                 0
estimation_uncertainty_note              0
data_quality_note                        0
third_party_verified                     0
verification_note                        0
source_document_name                     0
source_document_type                     0
dtype: int64

In [51]:
ghg_methodology_raw_df.to_csv("ghg_methodology_raw_df.csv", index=False)

In [52]:
BOARD_OVERSIGHT_BODIES = [
    "Board of Directors",
    "Board Sustainability Committee",
    "Board Risk Committee",
    "Board Audit Committee"
]

MANAGEMENT_OVERSIGHT_BODIES = [
    "Executive Committee",
    "Chief Sustainability Officer",
    "Chief Risk Officer",
    "ESG Steering Committee",
    "Sustainability Department"
]

REVIEW_FREQUENCIES = [
    "monthly",
    "quarterly",
    "semi-annually",
    "annually"
]

COMPETENCY_APPROACHES = [
    "board training sessions",
    "external expert briefings",
    "internal sustainability workshops",
    "cross-functional governance updates"
]

REMUNERATION_LINK_TYPES = [
    "climate targets",
    "emissions reduction objectives",
    "broader ESG performance",
    "safety and sustainability KPIs"
]

SOURCE_DOC_TYPES_GOV = [
    "board charter",
    "committee terms of reference",
    "governance policy",
    "remuneration policy",
    "annual governance memo"
]

In [53]:
def generate_governance_row(base_row: Dict[str, Any]) -> Dict[str, Any]:
    board_oversight = random.random() < 0.85
    management_oversight = random.random() < 0.92
    remuneration_linked = random.random() < 0.45
    formal_responsibility = random.random() < 0.88
    competency_process = random.random() < 0.72

    board_body = pick_one(BOARD_OVERSIGHT_BODIES) if board_oversight else None
    management_body = pick_one(MANAGEMENT_OVERSIGHT_BODIES) if management_oversight else None

    row = {
        "company_id": base_row["company_id"],
        "reporting_year": base_row["reporting_year"],

        "board_oversight_exists": board_oversight,
        "board_oversight_body": board_body,
        "board_review_frequency": pick_one(REVIEW_FREQUENCIES) if board_oversight else None,
        "board_oversight_note": (
            f"{board_body} reviews climate and sustainability-related matters."
            if board_oversight else
            "No formal board-level oversight identified."
        ),

        "management_oversight_exists": management_oversight,
        "management_oversight_body": management_body,
        "management_review_frequency": pick_one(REVIEW_FREQUENCIES) if management_oversight else None,
        "management_oversight_note": (
            f"{management_body} is responsible for day-to-day oversight of ESG and climate issues."
            if management_oversight else
            "No formal management-level oversight identified."
        ),

        "formal_roles_documented": formal_responsibility,
        "formal_roles_note": (
            "Roles and responsibilities are documented in governance policies or committee charters."
            if formal_responsibility else
            "Roles and responsibilities are not formally documented."
        ),

        "board_competency_process_exists": competency_process,
        "board_competency_approach": pick_one(COMPETENCY_APPROACHES) if competency_process else None,
        "board_competency_note": (
            "Board competency on sustainability-related issues is maintained through structured updates and training."
            if competency_process else
            "No formal competency-building process identified."
        ),

        "executive_remuneration_linked_to_esg": remuneration_linked,
        "executive_remuneration_link_type": pick_one(REMUNERATION_LINK_TYPES) if remuneration_linked else None,
        "executive_remuneration_note": (
            "Executive remuneration includes selected ESG- or climate-related performance indicators."
            if remuneration_linked else
            "No explicit ESG or climate linkage identified in executive remuneration."
        ),

        "governance_escalation_process_exists": random.random() < 0.7,
        "governance_integration_with_risk_exists": random.random() < 0.75,

        "source_document_name": f"Governance Source Pack {base_row['reporting_year']}",
        "source_document_type": pick_one(SOURCE_DOC_TYPES_GOV)
    }

    # derive notes for the two extra flags
    row["governance_escalation_process_note"] = (
        "Material sustainability matters can be escalated from management to board-level governance bodies."
        if row["governance_escalation_process_exists"] else
        "No formal escalation process identified."
    )

    row["governance_risk_integration_note"] = (
        "Governance bodies review sustainability matters in coordination with enterprise risk management processes."
        if row["governance_integration_with_risk_exists"] else
        "Governance and risk management processes appear only partially connected."
    )

    for col in ["sector", "subsector", "country", "region"]:
        if col in base_row:
            row[col] = base_row[col]

    return row

In [54]:
governance_records = [
    generate_governance_row(row)
    for row in company_base.to_dict(orient="records")
]

governance_raw_df = pd.DataFrame(governance_records)
governance_raw_df.head()

,company_id,reporting_year,board_oversight_exists,board_oversight_body,board_review_frequency,board_oversight_note,management_oversight_exists,management_oversight_body,management_review_frequency,management_oversight_note,...,board_competency_note,executive_remuneration_linked_to_esg,executive_remuneration_link_type,executive_remuneration_note,governance_escalation_process_exists,governance_integration_with_risk_exists,source_document_name,source_document_type,governance_escalation_process_note,governance_risk_integration_note
0,C001,2020,True,Board Sustainability Committee,quarterly,Board Sustainability Committee reviews climate...,False,NaN,NaN,No formal management-level oversight identified.,...,Board competency on sustainability-related iss...,False,NaN,No explicit ESG or climate linkage identified ...,True,True,Governance Source Pack 2020,annual governance memo,Material sustainability matters can be escalat...,Governance bodies review sustainability matter...
1,C001,2021,True,Board Sustainability Committee,monthly,Board Sustainability Committee reviews climate...,True,Executive Committee,quarterly,Executive Committee is responsible for day-to-...,...,No formal competency-building process identified.,True,climate targets,Executive remuneration includes selected ESG- ...,True,True,Governance Source Pack 2021,committee terms of reference,Material sustainability matters can be escalat...,Governance bodies review sustainability matter...
2,C001,2022,True,Board of Directors,annually,Board of Directors reviews climate and sustain...,False,NaN,NaN,No formal management-level oversight identified.,...,Board competency on sustainability-related iss...,False,NaN,No explicit ESG or climate linkage identified ...,False,True,Governance Source Pack 2022,governance policy,No formal escalation process identified.,Governance bodies review sustainability matter...
3,C001,2023,True,Board of Directors,annually,Board of Directors reviews climate and sustain...,True,Executive Committee,monthly,Executive Committee is responsible for day-to-...,...,Board competency on sustainability-related iss...,False,NaN,No explicit ESG or climate linkage identified ...,True,True,Governance Source Pack 2023,committee terms of reference,Material sustainability matters can be escalat...,Governance bodies review sustainability matter...
4,C001,2024,False,NaN,NaN,No formal board-level oversight identified.,True,Sustainability Department,semi-annually,Sustainability Department is responsible for d...,...,Board competency on sustainability-related iss...,False,NaN,No explicit ESG or climate linkage identified ...,True,True,Governance Source Pack 2024,board charter,Material sustainability matters can be escalat...,Governance bodies review sustainability matter...

In [55]:
governance_raw_df.to_csv("governance_raw_df.csv", index=False)

In [56]:
TARGET_TYPES = [
    "absolute emissions reduction",
    "emissions intensity reduction",
    "renewable electricity target",
    "energy efficiency target",
    "net zero target"
]

TARGET_SCOPES = [
    "Scope 1",
    "Scope 2",
    "Scope 1 and 2",
    "Scope 1, 2 and 3"
]

TARGET_STATUSES = [
    "on track",
    "partially on track",
    "delayed",
    "not assessed"
]

VALIDATION_STATUSES = [
    "SBTi validated",
    "internally approved",
    "under review",
    "not validated"
]

TRANSITION_PLAN_STATUSES = [
    "formal published plan",
    "board-approved internal plan",
    "partial transition actions only",
    "no formal transition plan"
]

CARBON_CREDIT_TYPES = [
    "nature-based credits",
    "removal credits",
    "avoidance credits",
    "mixed portfolio"
]

CARBON_CREDIT_USE = [
    "residual emissions only",
    "interim target support",
    "voluntary offsetting only"
]

SOURCE_DOC_TYPES_TARGETS = [
    "climate transition plan",
    "target approval memo",
    "sustainability strategy",
    "board-approved decarbonization roadmap",
    "net zero commitment document"
]

In [58]:
def generate_target_transition_row(base_row):
    has_target = random.random() < 0.85
    has_transition_plan = random.random() < 0.70
    uses_carbon_credits = random.random() < 0.35

    if has_target:
        target_type = pick_one(TARGET_TYPES)
        target_scope = pick_one(TARGET_SCOPES)
        base_year = random.choice([2019, 2020, 2021, 2022, 2023])
        target_year = random.choice([2030, 2035, 2040, 2045, 2050])

        # keep target year after reporting year
        if target_year <= base_row["reporting_year"]:
            target_year = base_row["reporting_year"] + 5

        interim_target_year = random.choice([2025, 2026, 2027, 2028, 2030])
        if interim_target_year >= target_year:
            interim_target_year = max(base_year + 3, target_year - 5)

        target_value_pct = random.choice([20, 25, 30, 40, 45, 50, 60, 75, 90])
        interim_target_value_pct = max(10, int(target_value_pct * random.uniform(0.3, 0.7)))

        target_status = pick_one(TARGET_STATUSES)
        validation_status = pick_one(VALIDATION_STATUSES)
    else:
        target_type = None
        target_scope = None
        base_year = None
        target_year = None
        interim_target_year = None
        target_value_pct = None
        interim_target_value_pct = None
        target_status = None
        validation_status = None

    if has_transition_plan:
        transition_plan_status = pick_one(TRANSITION_PLAN_STATUSES[:3])
        plan_covers_operations = random.random() < 0.85
        plan_covers_supply_chain = random.random() < 0.60
        plan_covers_capex_alignment = random.random() < 0.70
    else:
        transition_plan_status = "no formal transition plan"
        plan_covers_operations = False
        plan_covers_supply_chain = False
        plan_covers_capex_alignment = False

    if uses_carbon_credits:
        carbon_credit_type = pick_one(CARBON_CREDIT_TYPES)
        carbon_credit_planned_use = pick_one(CARBON_CREDIT_USE)
    else:
        carbon_credit_type = None
        carbon_credit_planned_use = None

    row = {
        "company_id": base_row["company_id"],
        "reporting_year": base_row["reporting_year"],

        "has_climate_target": has_target,
        "target_type": target_type,
        "target_scope": target_scope,
        "target_base_year": base_year,
        "target_year": target_year,
        "target_value_pct": target_value_pct,
        "interim_target_year": interim_target_year,
        "interim_target_value_pct": interim_target_value_pct,
        "target_status": target_status,
        "target_validation_status": validation_status,

        "has_transition_plan": has_transition_plan,
        "transition_plan_status": transition_plan_status,
        "transition_plan_covers_operations": plan_covers_operations,
        "transition_plan_covers_supply_chain": plan_covers_supply_chain,
        "transition_plan_covers_capex_alignment": plan_covers_capex_alignment,

        "uses_carbon_credits": uses_carbon_credits,
        "carbon_credit_type": carbon_credit_type,
        "carbon_credit_planned_use": carbon_credit_planned_use,

        "target_note": (
            f"The company has a {target_type} covering {target_scope} emissions."
            if has_target else
            "No formal climate target identified."
        ),

        "transition_plan_note": (
            "The company has a transition plan describing decarbonization actions and implementation priorities."
            if has_transition_plan else
            "No formal transition plan identified."
        ),

        "source_document_name": f"Target and Transition Pack {base_row['reporting_year']}",
        "source_document_type": pick_one(SOURCE_DOC_TYPES_TARGETS)
    }

    for col in ["sector", "subsector", "country", "region"]:
        if col in base_row:
            row[col] = base_row[col]

    return row

In [59]:
target_transition_records = [
    generate_target_transition_row(row)
    for row in company_base.to_dict(orient="records")
]

target_transition_plan_raw_df = pd.DataFrame(target_transition_records)
target_transition_plan_raw_df.head()

,company_id,reporting_year,has_climate_target,target_type,target_scope,target_base_year,target_year,target_value_pct,interim_target_year,interim_target_value_pct,...,transition_plan_covers_operations,transition_plan_covers_supply_chain,transition_plan_covers_capex_alignment,uses_carbon_credits,carbon_credit_type,carbon_credit_planned_use,target_note,transition_plan_note,source_document_name,source_document_type
0,C001,2020,True,net zero target,"Scope 1, 2 and 3",2020.0,2040.0,25.0,2028.0,14.0,...,False,False,False,True,avoidance credits,interim target support,The company has a net zero target covering Sco...,No formal transition plan identified.,Target and Transition Pack 2020,net zero commitment document
1,C001,2021,True,emissions intensity reduction,Scope 2,2019.0,2045.0,50.0,2028.0,25.0,...,True,True,False,False,NaN,NaN,The company has a emissions intensity reductio...,The company has a transition plan describing d...,Target and Transition Pack 2021,climate transition plan
2,C001,2022,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,NaN,NaN,No formal climate target identified.,No formal transition plan identified.,Target and Transition Pack 2022,climate transition plan
3,C001,2023,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,True,False,False,False,NaN,NaN,No formal climate target identified.,The company has a transition plan describing d...,Target and Transition Pack 2023,target approval memo
4,C001,2024,True,energy efficiency target,Scope 1 and 2,2022.0,2035.0,30.0,2028.0,20.0,...,True,True,True,False,NaN,NaN,The company has a energy efficiency target cov...,The company has a transition plan describing d...,Target and Transition Pack 2024,target approval memo

In [60]:
target_transition_plan_raw_df.to_csv("target_transition_plan_raw_df.csv", index=False)

In [61]:
SCENARIO_NAMES = [
    "IEA NZE 2050",
    "IEA STEPS",
    "NGFS Orderly Transition",
    "NGFS Delayed Transition",
    "NGFS Hot House World",
    "IPCC SSP1-1.9",
    "IPCC SSP2-4.5"
]

TEMPERATURE_PATHWAYS = [
    "1.5C",
    "1.7C",
    "2.0C",
    "2.5C",
    "3.0C+"
]

TIME_HORIZONS_SHORT = ["2025", "2026", "2027"]
TIME_HORIZONS_MEDIUM = ["2030", "2035"]
TIME_HORIZONS_LONG = ["2040", "2050"]

BUSINESS_SCOPE_OPTIONS = [
    "own operations only",
    "operations and supply chain",
    "portfolio / financed activities",
    "selected high-risk assets only",
    "group-wide operations"
]

ANALYSIS_SOURCE_TYPES = [
    "internal scenario analysis",
    "external consultant study",
    "enterprise risk team assessment",
    "climate stress testing model"
]

RESILIENCE_OUTCOMES = [
    "business model resilient under orderly transition",
    "moderate exposure under delayed transition",
    "significant vulnerability under high warming scenario",
    "resilience depends on accelerated mitigation actions",
    "high uncertainty with mixed resilience across business units"
]

ASSUMPTION_THEMES = [
    "carbon price increase",
    "energy price volatility",
    "higher physical climate losses",
    "technology adoption acceleration",
    "policy tightening",
    "customer demand shift",
    "insurance cost escalation",
    "asset impairment pressure"
]

SOURCE_DOC_TYPES_SCENARIO = [
    "scenario analysis memo",
    "climate resilience assessment",
    "climate stress test output",
    "strategy and resilience working paper"
]

In [64]:
def generate_scenario_analysis_row(base_row):
    scenario_used = random.random() < 0.65

    if scenario_used:
        scenario_1_name = pick_one(SCENARIO_NAMES)
        scenario_2_name = pick_one([s for s in SCENARIO_NAMES if s != scenario_1_name])

        scenario_1_temp = pick_one(TEMPERATURE_PATHWAYS[:3])
        scenario_2_temp = pick_one(TEMPERATURE_PATHWAYS[2:])

        short_term_horizon = pick_one(TIME_HORIZONS_SHORT)
        medium_term_horizon = pick_one(TIME_HORIZONS_MEDIUM)
        long_term_horizon = pick_one(TIME_HORIZONS_LONG)

        business_scope = pick_one(BUSINESS_SCOPE_OPTIONS)
        source_type = pick_one(ANALYSIS_SOURCE_TYPES)
        resilience_outcome = pick_one(RESILIENCE_OUTCOMES)

        assumptions = random.sample(ASSUMPTION_THEMES, k=3)
        assumptions_text = "; ".join(assumptions)

        row = {
            "company_id": base_row["company_id"],

            "reporting_year": base_row["reporting_year"],

            "scenario_analysis_used": True,
            "scenario_1_name": scenario_1_name,
            "scenario_2_name": scenario_2_name,
            "scenario_1_temperature_pathway": scenario_1_temp,
            "scenario_2_temperature_pathway": scenario_2_temp,

            "short_term_horizon": short_term_horizon,
            "medium_term_horizon": medium_term_horizon,
            "long_term_horizon": long_term_horizon,

            "business_scope_covered": business_scope,
            "analysis_source_type": source_type,
            "key_assumptions_summary": assumptions_text,
            "resilience_assessment_conclusion": resilience_outcome,

            "scenario_analysis_note": (
                f"Scenario analysis considered {scenario_1_name} and {scenario_2_name} across short-, medium-, and long-term horizons."
            ),

            "source_document_name": f"Scenario Analysis Pack {base_row['reporting_year']}",
            "source_document_type": pick_one(SOURCE_DOC_TYPES_SCENARIO)
        }
    else:
        row = {
            "company_id": base_row["company_id"],
            "reporting_year": base_row["reporting_year"],

            "scenario_analysis_used": False,
            "scenario_1_name": None,
            "scenario_2_name": None,
            "scenario_1_temperature_pathway": None,
            "scenario_2_temperature_pathway": None,

            "short_term_horizon": None,
            "medium_term_horizon": None,
            "long_term_horizon": None,

            "business_scope_covered": None,
            "analysis_source_type": None,
            "key_assumptions_summary": None,
            "resilience_assessment_conclusion": None,

            "scenario_analysis_note": "No formal scenario analysis identified for the reporting year.",

            "source_document_name": f"Scenario Analysis Pack {base_row['reporting_year']}",
            "source_document_type": pick_one(SOURCE_DOC_TYPES_SCENARIO)
        }

    for col in ["sector", "subsector", "country", "region"]:
        if col in base_row:
            row[col] = base_row[col]

    return row

In [65]:
scenario_analysis_records = [
    generate_scenario_analysis_row(row)
    for row in company_base.to_dict(orient="records")
]

scenario_analysis_raw_df = pd.DataFrame(scenario_analysis_records)
scenario_analysis_raw_df.head()

,company_id,reporting_year,scenario_analysis_used,scenario_1_name,scenario_2_name,scenario_1_temperature_pathway,scenario_2_temperature_pathway,short_term_horizon,medium_term_horizon,long_term_horizon,business_scope_covered,analysis_source_type,key_assumptions_summary,resilience_assessment_conclusion,scenario_analysis_note,source_document_name,source_document_type
0,C001,2020,True,IPCC SSP2-4.5,NGFS Delayed Transition,1.5C,2.5C,2026,2035,2050,portfolio / financed activities,internal scenario analysis,customer demand shift; technology adoption acc...,moderate exposure under delayed transition,Scenario analysis considered IPCC SSP2-4.5 and...,Scenario Analysis Pack 2020,strategy and resilience working paper
1,C001,2021,True,NGFS Delayed Transition,IPCC SSP1-1.9,1.5C,2.5C,2025,2035,2050,portfolio / financed activities,internal scenario analysis,carbon price increase; customer demand shift; ...,resilience depends on accelerated mitigation a...,Scenario analysis considered NGFS Delayed Tran...,Scenario Analysis Pack 2021,strategy and resilience working paper
2,C001,2022,True,IEA STEPS,IPCC SSP1-1.9,1.7C,3.0C+,2026,2035,2040,operations and supply chain,enterprise risk team assessment,higher physical climate losses; asset impairme...,high uncertainty with mixed resilience across ...,Scenario analysis considered IEA STEPS and IPC...,Scenario Analysis Pack 2022,strategy and resilience working paper
3,C001,2023,True,IPCC SSP1-1.9,NGFS Hot House World,1.5C,3.0C+,2025,2035,2040,group-wide operations,climate stress testing model,technology adoption acceleration; insurance co...,business model resilient under orderly transition,Scenario analysis considered IPCC SSP1-1.9 and...,Scenario Analysis Pack 2023,strategy and resilience working paper
4,C001,2024,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No formal scenario analysis identified for the...,Scenario Analysis Pack 2024,climate resilience assessment

In [66]:
scenario_analysis_raw_df.to_csv("scenario_analysis_raw_df.csv", index=False)

Emissions calculations

In [7]:
EMISSION_FACTORS = {
    "diesel_liters_to_tco2e": 0.00268,          # tCO2e per liter
    "natural_gas_mwh_to_tco2e": 0.202,          # tCO2e per MWh
    "refrigerant_kg_to_tco2e": 0.0015,          # simplified placeholder
    "grid_electricity_mwh_to_tco2e": 0.42       # tCO2e per MWh
}

In [8]:
def calculate_scope1_scope2(energy_df: pd.DataFrame) -> pd.DataFrame:
    df = energy_df.copy()

    # Scope 1
    df["scope1_diesel_tco2e"] = df["diesel_liters"] * EMISSION_FACTORS["diesel_liters_to_tco2e"]
    df["scope1_natural_gas_tco2e"] = df["natural_gas_mwh"] * EMISSION_FACTORS["natural_gas_mwh_to_tco2e"]
    df["scope1_refrigerants_tco2e"] = df["refrigerant_leak_kg"] * EMISSION_FACTORS["refrigerant_kg_to_tco2e"]

    df["scope1_emissions_tco2e"] = (
        df["scope1_diesel_tco2e"] +
        df["scope1_natural_gas_tco2e"] +
        df["scope1_refrigerants_tco2e"]
    )

    # Scope 2 location-based
    df["scope2_location_based_tco2e"] = (
        df["electricity_purchased_mwh"] * EMISSION_FACTORS["grid_electricity_mwh_to_tco2e"]
    )

    # Scope 2 market-based
    residual_mwh = df["electricity_purchased_mwh"] - df["electricity_renewable_mwh"]
    residual_mwh = residual_mwh.clip(lower=0)

    df["scope2_market_based_tco2e"] = (
        residual_mwh * EMISSION_FACTORS["grid_electricity_mwh_to_tco2e"]
    )

    # Total energy
    df["total_energy_consumption_mwh"] = (
        df["natural_gas_mwh"] + df["electricity_purchased_mwh"]
    )

    # Methodology / disclosure-ready fields
    df["ghg_measurement_methodology"] = (
        "Scope 1 and Scope 2 calculated from activity data using emission factors."
    )
    df["emission_factor_source_disclosure"] = df["emission_factor_source"]
    df["organizational_boundary_disclosure"] = df["boundary_type"]

    keep_cols = [
        "company_id", "reporting_year",
        "scope1_diesel_tco2e", "scope1_natural_gas_tco2e", "scope1_refrigerants_tco2e",
        "scope1_emissions_tco2e",
        "scope2_location_based_tco2e", "scope2_market_based_tco2e",
        "total_energy_consumption_mwh",
        "ghg_measurement_methodology",
        "emission_factor_source_disclosure",
        "organizational_boundary_disclosure",
        "data_quality_level"
    ]
    return df[keep_cols]

In [9]:
emissions_df = calculate_scope1_scope2(energy_raw_df)
emissions_df.head()

,company_id,reporting_year,scope1_diesel_tco2e,scope1_natural_gas_tco2e,scope1_refrigerants_tco2e,scope1_emissions_tco2e,scope2_location_based_tco2e,scope2_market_based_tco2e,total_energy_consumption_mwh,ghg_measurement_methodology,emission_factor_source_disclosure,organizational_boundary_disclosure,data_quality_level
0,C001,2020,15.397672,581.11158,0.041430,596.550682,3914.3748,2898.4746,12196.73,Scope 1 and Scope 2 calculated from activity d...,National Grid Database,operational_control,high
1,C001,2021,9.540666,130.33242,0.161505,140.034591,4477.9392,3311.9268,11306.97,Scope 1 and Scope 2 calculated from activity d...,National Grid Database,financial_control,medium
2,C001,2022,5.911651,590.80354,0.047040,596.762231,4336.2606,3797.1822,13249.20,Scope 1 and Scope 2 calculated from activity d...,DEFRA,operational_control,high
3,C001,2023,10.275254,254.64322,0.070845,264.989319,3043.9752,2431.5858,8508.17,Scope 1 and Scope 2 calculated from activity d...,National Grid Database,operational_control,low
4,C001,2024,21.757660,171.44346,0.106695,193.307815,2067.0090,1698.6144,5770.18,Scope 1 and Scope 2 calculated from activity d...,DEFRA,operational_control,high

In [10]:
SCOPE3_FACTORS = {
    "cat1_spend_to_tco2e": 0.00035,         # purchased goods per USD
    "cat6_business_travel_km_to_tco2e": 0.00018,
    "cat7_commuting_km_to_tco2e": 0.00009,
    "cat15_financed_to_tco2e": 0.0008
}

In [11]:
def calculate_scope3(scope3_df: pd.DataFrame) -> pd.DataFrame:
    df = scope3_df.copy()

    df["scope3_cat1_tco2e"] = (
        df["scope3_cat1_purchased_goods_spend_usd"] * SCOPE3_FACTORS["cat1_spend_to_tco2e"]
    )

    df["scope3_cat6_tco2e"] = (
        df["scope3_cat6_business_travel_km"] * SCOPE3_FACTORS["cat6_business_travel_km_to_tco2e"]
    )

    df["scope3_cat7_tco2e"] = (
        df["scope3_cat7_employee_commuting_km"] * SCOPE3_FACTORS["cat7_commuting_km_to_tco2e"]
    )

    df["scope3_cat15_tco2e"] = (
        df["scope3_cat15_financed_activity_value"] * SCOPE3_FACTORS["cat15_financed_to_tco2e"]
    )

    df["scope3_total_tco2e"] = (
        df["scope3_cat1_tco2e"] +
        df["scope3_cat6_tco2e"] +
        df["scope3_cat7_tco2e"] +
        df["scope3_cat15_tco2e"]
    )

    df["scope3_methodology_note"] = (
        "Scope 3 estimated using a mix of spend-based, activity-based and proxy methods depending on data availability."
    )

    df["scope3_categories_disclosed"] = "1, 6, 7, 15"

    keep_cols = [
        "company_id", "reporting_year",
        "scope3_cat1_tco2e",
        "scope3_cat6_tco2e",
        "scope3_cat7_tco2e",
        "scope3_cat15_tco2e",
        "scope3_total_tco2e",
        "scope3_methodology_note",
        "scope3_categories_disclosed",
        "scope3_method",
        "scope3_data_quality_level"
    ]
    return df[keep_cols]

In [12]:
scope3_metrics_df = calculate_scope3(scope3_raw_df)
scope3_metrics_df.head()

,company_id,reporting_year,scope3_cat1_tco2e,scope3_cat6_tco2e,scope3_cat7_tco2e,scope3_cat15_tco2e,scope3_total_tco2e,scope3_methodology_note,scope3_categories_disclosed,scope3_method,scope3_data_quality_level
0,C001,2020,731.859111,81.267260,41.039953,97.600344,951.766668,"Scope 3 estimated using a mix of spend-based, ...","1, 6, 7, 15",supplier-specific,medium
1,C001,2021,393.130699,95.095141,56.599722,588.237224,1133.062787,"Scope 3 estimated using a mix of spend-based, ...","1, 6, 7, 15",supplier-specific,medium
2,C001,2022,242.357419,77.724209,19.156941,208.126976,547.365545,"Scope 3 estimated using a mix of spend-based, ...","1, 6, 7, 15",activity-based,medium
3,C001,2023,882.105333,127.210142,63.902017,600.630688,1673.848179,"Scope 3 estimated using a mix of spend-based, ...","1, 6, 7, 15",spend-based,medium
4,C001,2024,338.248803,164.528496,42.978561,530.056360,1075.812220,"Scope 3 estimated using a mix of spend-based, ...","1, 6, 7, 15",activity-based,medium

In [13]:
def calculate_climate_finance_metrics(finance_df: pd.DataFrame) -> pd.DataFrame:
    df = finance_df.copy()

    df["climate_capex_pct"] = np.where(
        df["total_capex_usd"] > 0,
        (df["climate_related_capex_usd"] / df["total_capex_usd"]) * 100,
        np.nan
    )

    df["high_climate_risk_assets_pct"] = np.where(
        df["total_assets_usd"] > 0,
        (df["high_climate_risk_assets_usd"] / df["total_assets_usd"]) * 100,
        np.nan
    )

    df["financial_effect_current_year_level"] = pd.cut(
        df["current_climate_loss_usd"] / df["total_assets_usd"],
        bins=[-np.inf, 0.005, 0.02, np.inf],
        labels=["low", "medium", "high"]
    )

    df["climate_financial_disclosure_note"] = (
        "Climate-related financial metrics derived from asset exposure, climate-tagged capital expenditure and current climate-related losses."
    )

    keep_cols = [
        "company_id", "reporting_year",
        "total_assets_usd",
        "high_climate_risk_assets_usd",
        "total_capex_usd",
        "climate_related_capex_usd",
        "current_climate_loss_usd",
        "climate_capex_pct",
        "high_climate_risk_assets_pct",
        "financial_effect_current_year_level",
        "climate_financial_disclosure_note",
        "finance_data_source"
    ]
    return df[keep_cols]

In [14]:
finance_metrics_df = calculate_climate_finance_metrics(finance_raw_df)
finance_metrics_df.head()

,company_id,reporting_year,total_assets_usd,high_climate_risk_assets_usd,total_capex_usd,climate_related_capex_usd,current_climate_loss_usd,climate_capex_pct,high_climate_risk_assets_pct,financial_effect_current_year_level,climate_financial_disclosure_note,finance_data_source
0,C001,2020,1.693732e+09,1.873909e+08,18644485.13,7475240.47,961837.77,40.093574,11.063785,low,Climate-related financial metrics derived from...,ERP
1,C001,2021,2.809944e+09,8.448097e+08,11993614.61,3140650.70,580136.63,26.186023,30.064999,low,Climate-related financial metrics derived from...,ERP
2,C001,2022,8.258597e+08,2.661318e+08,18207525.03,5521260.50,1234578.68,30.324058,32.224825,low,Climate-related financial metrics derived from...,ERP
3,C001,2023,1.722234e+09,4.753503e+08,18147984.68,7346931.57,2830633.89,40.483457,27.600803,low,Climate-related financial metrics derived from...,finance consolidation file
4,C001,2024,2.747111e+09,2.821771e+08,4909316.85,2009980.73,595430.48,40.942168,10.271779,low,Climate-related financial metrics derived from...,ERP

In [15]:
def calculate_climate_risk_metrics(risk_df: pd.DataFrame) -> pd.DataFrame:
    df = risk_df.copy()

    df["climate_risk_score"] = df["likelihood_score"] * df["magnitude_score"]

    df["climate_risk_level"] = pd.cut(
        df["climate_risk_score"],
        bins=[-np.inf, 6, 12, np.inf],
        labels=["low", "medium", "high"]
    )

    df["risk_assessment_methodology"] = (
        "Climate risks assessed using likelihood and magnitude scoring from the enterprise risk register."
    )

    df["risk_prioritization_basis"] = df["prioritization_method"]

    df["risk_assessment_structured_disclosure"] = (
        "Likelihood and magnitude are used to assess climate-related risks and opportunities."
    )

    keep_cols = [
        "company_id", "reporting_year",
        "risk_description",
        "risk_type",
        "likelihood_score",
        "magnitude_score",
        "climate_risk_score",
        "climate_risk_level",
        "time_horizon",
        "mitigation_plan_exists",
        "risk_owner_function",
        "risk_assessment_methodology",
        "risk_prioritization_basis",
        "risk_assessment_structured_disclosure"
    ]
    return df[keep_cols]

In [16]:
risk_metrics_df = calculate_climate_risk_metrics(risk_raw_df)
risk_metrics_df.head()

,company_id,reporting_year,risk_description,risk_type,likelihood_score,magnitude_score,climate_risk_score,climate_risk_level,time_horizon,mitigation_plan_exists,risk_owner_function,risk_assessment_methodology,risk_prioritization_basis,risk_assessment_structured_disclosure
0,C001,2020,Regulatory climate disclosure non-compliance,transition,5,3,15,high,short-term,True,finance,Climate risks assessed using likelihood and ma...,expert judgement,Likelihood and magnitude are used to assess cl...
1,C001,2021,Flood exposure of financed real estate,physical,1,3,3,low,long-term,False,operations,Climate risks assessed using likelihood and ma...,likelihood_x_magnitude,Likelihood and magnitude are used to assess cl...
2,C001,2022,Regulatory climate disclosure non-compliance,physical,5,5,25,high,short-term,True,risk,Climate risks assessed using likelihood and ma...,expert judgement,Likelihood and magnitude are used to assess cl...
3,C001,2023,Regulatory climate disclosure non-compliance,physical,3,4,12,medium,short-term,True,finance,Climate risks assessed using likelihood and ma...,expert judgement,Likelihood and magnitude are used to assess cl...
4,C001,2024,Carbon-intensive portfolio exposure,physical,2,5,10,medium,short-term,True,risk,Climate risks assessed using likelihood and ma...,multi-factor scoring,Likelihood and magnitude are used to assess cl...

In [17]:
climate_report_ready_df = (
    emissions_df
    .merge(scope3_metrics_df, on=["company_id", "reporting_year"], how="outer")
    .merge(finance_metrics_df, on=["company_id", "reporting_year"], how="outer")
    .merge(risk_metrics_df, on=["company_id", "reporting_year"], how="outer")
)

climate_report_ready_df.head()

,company_id,reporting_year,scope1_diesel_tco2e,scope1_natural_gas_tco2e,scope1_refrigerants_tco2e,scope1_emissions_tco2e,scope2_location_based_tco2e,scope2_market_based_tco2e,total_energy_consumption_mwh,ghg_measurement_methodology,...,likelihood_score,magnitude_score,climate_risk_score,climate_risk_level,time_horizon,mitigation_plan_exists,risk_owner_function,risk_assessment_methodology,risk_prioritization_basis,risk_assessment_structured_disclosure
0,C001,2020,15.397672,581.11158,0.041430,596.550682,3914.3748,2898.4746,12196.73,Scope 1 and Scope 2 calculated from activity d...,...,5,3,15,high,short-term,True,finance,Climate risks assessed using likelihood and ma...,expert judgement,Likelihood and magnitude are used to assess cl...
1,C001,2021,9.540666,130.33242,0.161505,140.034591,4477.9392,3311.9268,11306.97,Scope 1 and Scope 2 calculated from activity d...,...,1,3,3,low,long-term,False,operations,Climate risks assessed using likelihood and ma...,likelihood_x_magnitude,Likelihood and magnitude are used to assess cl...
2,C001,2022,5.911651,590.80354,0.047040,596.762231,4336.2606,3797.1822,13249.20,Scope 1 and Scope 2 calculated from activity d...,...,5,5,25,high,short-term,True,risk,Climate risks assessed using likelihood and ma...,expert judgement,Likelihood and magnitude are used to assess cl...
3,C001,2023,10.275254,254.64322,0.070845,264.989319,3043.9752,2431.5858,8508.17,Scope 1 and Scope 2 calculated from activity d...,...,3,4,12,medium,short-term,True,finance,Climate risks assessed using likelihood and ma...,expert judgement,Likelihood and magnitude are used to assess cl...
4,C001,2024,21.757660,171.44346,0.106695,193.307815,2067.0090,1698.6144,5770.18,Scope 1 and Scope 2 calculated from activity d...,...,2,5,10,medium,short-term,True,risk,Climate risks assessed using likelihood and ma...,multi-factor scoring,Likelihood and magnitude are used to assess cl...

In [18]:
climate_report_ready_df.isnull().sum().sort_values(ascending=False).head(20)

company_id                            0
reporting_year                        0
scope1_diesel_tco2e                   0
scope1_natural_gas_tco2e              0
scope1_refrigerants_tco2e             0
scope1_emissions_tco2e                0
scope2_location_based_tco2e           0
scope2_market_based_tco2e             0
total_energy_consumption_mwh          0
ghg_measurement_methodology           0
emission_factor_source_disclosure     0
organizational_boundary_disclosure    0
data_quality_level                    0
scope3_cat1_tco2e                     0
scope3_cat6_tco2e                     0
scope3_cat7_tco2e                     0
scope3_cat15_tco2e                    0
scope3_total_tco2e                    0
scope3_methodology_note               0
scope3_categories_disclosed           0
dtype: int64

In [19]:
climate_report_ready_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
company_id,20,4,C001,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reporting_year,20.0,NaN,NaN,NaN,2022.0,1.450953,2020.0,2021.0,2022.0,2023.0,2024.0
scope1_diesel_tco2e,20.0,NaN,NaN,NaN,275.165009,359.474943,4.969444,14.851079,70.309586,405.412953,1045.915774
scope1_natural_gas_tco2e,20.0,NaN,NaN,NaN,3962.084964,6523.313245,119.15778,170.49305,339.21456,3743.07111,16503.72926
scope1_refrigerants_tco2e,20.0,NaN,NaN,NaN,0.098468,0.061872,0.01761,0.047535,0.076695,0.143471,0.22215
scope1_emissions_tco2e,20.0,NaN,NaN,NaN,4237.348441,6518.236586,133.452841,190.768972,782.905639,4587.420008,16818.610665
scope2_location_based_tco2e,20.0,NaN,NaN,NaN,9041.68923,11998.880142,738.3222,2202.5661,4125.3177,7373.7762,40352.97
scope2_market_based_tco2e,20.0,NaN,NaN,NaN,7161.08757,9322.980047,466.4268,1691.6739,3105.2007,6047.24085,30408.1008
total_energy_consumption_mwh,20.0,NaN,NaN,NaN,41142.1135,59133.279805,2577.78,5939.7025,11751.85,41057.415,173138.08
ghg_measurement_methodology,20,1,Scope 1 and Scope 2 calculated from activity d...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emission_factor_source_disclosure,20,3,DEFRA,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
organizational_boundary_disclosure,20,2,operational_control,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
data_quality_level,20,3,high,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
scope3_cat1_tco2e,20.0,NaN,NaN,NaN,886.320326,665.569582,242.357419,379.410225,717.177162,1235.797711,2454.135239
scope3_cat6_tco2e,20.0,NaN,NaN,NaN,59.658273,37.295563,19.69369,33.100793,46.117462,78.609972,164.528496
scope3_cat7_tco2e,20.0,NaN,NaN,NaN,35.422769,18.280848,10.045033,20.559271,28.658559,45.953328,70.222271
scope3_cat15_tco2e,20.0,NaN,NaN,NaN,139.512198,196.320285,9.64732,23.518918,41.277716,158.190604,600.630688
scope3_total_tco2e,20.0,NaN,NaN,NaN,1120.913565,609.54213,426.022728,630.663656,1013.789444,1543.684171,2507.7679
scope3_methodology_note,20,1,"Scope 3 estimated using a mix of spend-based, ...",20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
scope3_categories_disclosed,20,1,"1, 6, 7, 15",20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
scope3_method,20,4,activity-based,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
scope3_data_quality_level,20,3,medium,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_assets_usd,20.0,NaN,NaN,NaN,1093814612.9275,700642608.146243,216554692.91,644376697.765,852690727.38,1270755014.7875,2809944161.12
high_climate_risk_assets_usd,20.0,NaN,NaN,NaN,297825079.5915,197678308.57901,15222562.41,179629447.4925,246295545.215,433481974.9075,844809695.33
total_capex_usd,20.0,NaN,NaN,NaN,29738774.7895,27676100.23238,1655723.37,5981791.9625,18426005.08,46751539.885,88036508.67
climate_related_capex_usd,20.0,NaN,NaN,NaN,8860675.144,9554010.397939,293653.69,1916271.8,6582288.705,10405896.445,36561229.36
current_climate_loss_usd,20.0,NaN,NaN,NaN,2484427.046,3228067.162257,87820.35,553494.11,1133164.39,3114738.695,10901842.91
climate_capex_pct,20.0,NaN,NaN,NaN,28.632476,10.632186,5.202463,19.781919,29.063253,40.191045,43.544799
high_climate_risk_assets_pct,20.0,NaN,NaN,NaN,28.394774,13.369954,7.029431,18.219971,27.723164,41.587319,49.701616
financial_effect_current_year_level,20,2,low,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
climate_financial_disclosure_note,20,1,Climate-related financial metrics derived from...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
finance_data_source,20,3,finance consolidation file,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
risk_description,20,11,Regulatory climate disclosure non-compliance,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
risk_type,20,2,physical,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
likelihood_score,20.0,NaN,NaN,NaN,3.35,1.424411,1.0,2.0,4.0,4.25,5.0
magnitude_score,20.0,NaN,NaN,NaN,3.05,1.276302,1.0,2.0,3.0,4.0,5.0
climate_risk_score,20.0,NaN,NaN,NaN,10.8,7.082967,1.0,5.5,10.0,15.25,25.0
climate_risk_level,20,3,medium,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
time_horizon,20,3,short-term,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mitigation_plan_exists,20,2,True,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
risk_owner_function,20,4,sustainability,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
risk_assessment_methodology,20,1,Climate risks assessed using likelihood and ma...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
risk_prioritization_basis,20,3,likelihood_x_magnitude,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
risk_assessment_structured_disclosure,20,1,Likelihood and magnitude are used to assess cl...,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
climate_report_ready_df[
    [
        "company_id", "reporting_year",
        "scope1_emissions_tco2e",
        "scope2_location_based_tco2e",
        "scope3_total_tco2e",
        "climate_capex_pct",
        "high_climate_risk_assets_pct",
        "climate_risk_score"
    ]
].head(10)

,company_id,reporting_year,scope1_emissions_tco2e,scope2_location_based_tco2e,scope3_total_tco2e,climate_capex_pct,high_climate_risk_assets_pct,climate_risk_score
0,C001,2020,596.550682,3914.3748,951.766668,40.093574,11.063785,15
1,C001,2021,140.034591,4477.9392,1133.062787,26.186023,30.064999,3
2,C001,2022,596.762231,4336.2606,547.365545,30.324058,32.224825,25
3,C001,2023,264.989319,3043.9752,1673.848179,40.483457,27.600803,12
4,C001,2024,193.307815,2067.0090,1075.812220,40.942168,10.271779,10
5,C002,2020,146.596406,2249.8392,739.675900,5.202463,7.029431,4
6,C002,2021,133.452841,834.9138,510.095395,13.970772,18.837904,10
7,C002,2022,183.152440,937.6668,431.950674,30.985316,11.507994,20
8,C002,2023,235.676824,738.3222,426.022728,19.708632,16.366172,25
9,C002,2024,182.798449,2268.2142,658.429693,40.681862,24.460211,2

Raw governance schema

In [21]:
governance_raw_df = pd.DataFrame([
    {
        "company_id": "C001",
        "reporting_year": 2024,
        "board_reviews_climate": True,
        "board_review_frequency_per_year": 4,
        "board_has_sustainability_committee": True,
        "committee_name": "Sustainability and Risk Committee",
        "committee_reports_to_board": True,
        "management_climate_role_exists": True,
        "management_role_title": "Chief Sustainability Officer",
        "climate_kpis_in_executive_remuneration": True,
        "board_climate_training_provided": True,
        "governance_policy_formalized": True,
        "climate_escalation_process_exists": True,
        "internal_reporting_frequency_per_year": 12,
        "external_assurance_on_climate_disclosures": True
    },
    {
        "company_id": "C002",
        "reporting_year": 2024,
        "board_reviews_climate": True,
        "board_review_frequency_per_year": 2,
        "board_has_sustainability_committee": False,
        "committee_name": None,
        "committee_reports_to_board": False,
        "management_climate_role_exists": True,
        "management_role_title": "Head of ESG",
        "climate_kpis_in_executive_remuneration": False,
        "board_climate_training_provided": False,
        "governance_policy_formalized": True,
        "climate_escalation_process_exists": True,
        "internal_reporting_frequency_per_year": 4,
        "external_assurance_on_climate_disclosures": False
    },
    {
        "company_id": "C003",
        "reporting_year": 2024,
        "board_reviews_climate": False,
        "board_review_frequency_per_year": 0,
        "board_has_sustainability_committee": False,
        "committee_name": None,
        "committee_reports_to_board": False,
        "management_climate_role_exists": False,
        "management_role_title": None,
        "climate_kpis_in_executive_remuneration": False,
        "board_climate_training_provided": False,
        "governance_policy_formalized": False,
        "climate_escalation_process_exists": False,
        "internal_reporting_frequency_per_year": 1,
        "external_assurance_on_climate_disclosures": False
    }
])

governance_raw_df

,company_id,reporting_year,board_reviews_climate,board_review_frequency_per_year,board_has_sustainability_committee,committee_name,committee_reports_to_board,management_climate_role_exists,management_role_title,climate_kpis_in_executive_remuneration,board_climate_training_provided,governance_policy_formalized,climate_escalation_process_exists,internal_reporting_frequency_per_year,external_assurance_on_climate_disclosures
0,C001,2024,True,4,True,Sustainability and Risk Committee,True,True,Chief Sustainability Officer,True,True,True,True,12,True
1,C002,2024,True,2,False,NaN,False,True,Head of ESG,False,False,True,True,4,False
2,C003,2024,False,0,False,NaN,False,False,NaN,False,False,False,False,1,False

In [22]:
def classify_frequency(freq: int) -> str:
    if pd.isna(freq):
        return "unknown"
    if freq >= 12:
        return "monthly_or_more"
    elif freq >= 4:
        return "quarterly"
    elif freq >= 2:
        return "semi_annual"
    elif freq >= 1:
        return "annual"
    return "none"


def classify_governance_maturity(score: int) -> str:
    if score >= 8:
        return "high"
    elif score >= 5:
        return "medium"
    return "low"

In [23]:
def calculate_governance_metrics(governance_df: pd.DataFrame) -> pd.DataFrame:
    df = governance_df.copy()

    # Core flags
    df["board_oversight_exists"] = df["board_reviews_climate"]
    df["committee_oversight_exists"] = (
        df["board_has_sustainability_committee"] & df["committee_reports_to_board"]
    )
    df["management_oversight_exists"] = df["management_climate_role_exists"]
    df["remuneration_linked_to_climate"] = df["climate_kpis_in_executive_remuneration"]

    # Frequency labels
    df["board_oversight_frequency_label"] = df["board_review_frequency_per_year"].apply(classify_frequency)
    df["internal_reporting_frequency_label"] = df["internal_reporting_frequency_per_year"].apply(classify_frequency)

    # Governance score
    score_cols = [
        "board_reviews_climate",
        "board_has_sustainability_committee",
        "committee_reports_to_board",
        "management_climate_role_exists",
        "climate_kpis_in_executive_remuneration",
        "board_climate_training_provided",
        "governance_policy_formalized",
        "climate_escalation_process_exists",
        "external_assurance_on_climate_disclosures"
    ]

    df["governance_score"] = df[score_cols].fillna(False).astype(int).sum(axis=1)
    df["governance_maturity"] = df["governance_score"].apply(classify_governance_maturity)

    # Structured disclosure fields
    df["governance_oversight_disclosure"] = np.where(
        df["board_oversight_exists"],
        "The board oversees climate-related matters.",
        "Climate-related matters are not formally overseen by the board."
    )

    df["management_role_disclosure"] = np.where(
        df["management_oversight_exists"],
        "Management has assigned responsibility for climate-related matters.",
        "Management responsibility for climate-related matters is not formally assigned."
    )

    df["remuneration_disclosure"] = np.where(
        df["remuneration_linked_to_climate"],
        "Executive remuneration includes climate-related performance considerations.",
        "Executive remuneration is not linked to climate-related performance."
    )

    df["committee_disclosure"] = np.where(
        df["committee_oversight_exists"],
        "A committee supports board oversight of climate-related matters.",
        "No formal committee structure supports climate-related oversight."
    )

    df["skills_and_competencies_disclosure"] = np.where(
        df["board_climate_training_provided"],
        "Climate-related training or capability development is provided to the board.",
        "No formal board climate-related training was identified."
    )

    keep_cols = [
        "company_id",
        "reporting_year",
        "board_oversight_exists",
        "committee_oversight_exists",
        "committee_name",
        "management_oversight_exists",
        "management_role_title",
        "remuneration_linked_to_climate",
        "board_oversight_frequency_label",
        "internal_reporting_frequency_label",
        "external_assurance_on_climate_disclosures",
        "governance_score",
        "governance_maturity",
        "governance_oversight_disclosure",
        "committee_disclosure",
        "management_role_disclosure",
        "remuneration_disclosure",
        "skills_and_competencies_disclosure"
    ]

    return df[keep_cols]

In [24]:
governance_metrics_df = calculate_governance_metrics(governance_raw_df)
governance_metrics_df

,company_id,reporting_year,board_oversight_exists,committee_oversight_exists,committee_name,management_oversight_exists,management_role_title,remuneration_linked_to_climate,board_oversight_frequency_label,internal_reporting_frequency_label,external_assurance_on_climate_disclosures,governance_score,governance_maturity,governance_oversight_disclosure,committee_disclosure,management_role_disclosure,remuneration_disclosure,skills_and_competencies_disclosure
0,C001,2024,True,True,Sustainability and Risk Committee,True,Chief Sustainability Officer,True,quarterly,monthly_or_more,True,9,high,The board oversees climate-related matters.,A committee supports board oversight of climat...,Management has assigned responsibility for cli...,Executive remuneration includes climate-relate...,Climate-related training or capability develop...
1,C002,2024,True,False,NaN,True,Head of ESG,False,semi_annual,quarterly,False,4,low,The board oversees climate-related matters.,No formal committee structure supports climate...,Management has assigned responsibility for cli...,Executive remuneration is not linked to climat...,No formal board climate-related training was i...
2,C003,2024,False,False,NaN,False,NaN,False,none,annual,False,0,low,Climate-related matters are not formally overs...,No formal committee structure supports climate...,Management responsibility for climate-related ...,Executive remuneration is not linked to climat...,No formal board climate-related training was i...

In [25]:
full_ifrs_ready_df = climate_report_ready_df.merge(
    governance_metrics_df,
    on=["company_id", "reporting_year"],
    how="left"
)

full_ifrs_ready_df.head()

,company_id,reporting_year,scope1_diesel_tco2e,scope1_natural_gas_tco2e,scope1_refrigerants_tco2e,scope1_emissions_tco2e,scope2_location_based_tco2e,scope2_market_based_tco2e,total_energy_consumption_mwh,ghg_measurement_methodology,...,board_oversight_frequency_label,internal_reporting_frequency_label,external_assurance_on_climate_disclosures,governance_score,governance_maturity,governance_oversight_disclosure,committee_disclosure,management_role_disclosure,remuneration_disclosure,skills_and_competencies_disclosure
0,C001,2020,15.397672,581.11158,0.041430,596.550682,3914.3748,2898.4746,12196.73,Scope 1 and Scope 2 calculated from activity d...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,C001,2021,9.540666,130.33242,0.161505,140.034591,4477.9392,3311.9268,11306.97,Scope 1 and Scope 2 calculated from activity d...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C001,2022,5.911651,590.80354,0.047040,596.762231,4336.2606,3797.1822,13249.20,Scope 1 and Scope 2 calculated from activity d...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,C001,2023,10.275254,254.64322,0.070845,264.989319,3043.9752,2431.5858,8508.17,Scope 1 and Scope 2 calculated from activity d...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,C001,2024,21.757660,171.44346,0.106695,193.307815,2067.0090,1698.6144,5770.18,Scope 1 and Scope 2 calculated from activity d...,...,quarterly,monthly_or_more,True,9.0,high,The board oversees climate-related matters.,A committee supports board oversight of climat...,Management has assigned responsibility for cli...,Executive remuneration includes climate-relate...,Climate-related training or capability develop...

In [26]:
full_ifrs_ready_df.to_csv("full_ifrs_ready_df.csv", index=False)
print("Saved: full_ifrs_ready_df.csv")

Saved: full_ifrs_ready_df.csv

In [27]:
governance_metrics_df.isnull().sum()

company_id                                   0
reporting_year                               0
board_oversight_exists                       0
committee_oversight_exists                   0
committee_name                               2
management_oversight_exists                  0
management_role_title                        1
remuneration_linked_to_climate               0
board_oversight_frequency_label              0
internal_reporting_frequency_label           0
external_assurance_on_climate_disclosures    0
governance_score                             0
governance_maturity                          0
governance_oversight_disclosure              0
committee_disclosure                         0
management_role_disclosure                   0
remuneration_disclosure                      0
skills_and_competencies_disclosure           0
dtype: int64

In [33]:
print(full_ifrs_ready_df.columns.tolist())

['company_id', 'reporting_year', 'scope1_diesel_tco2e', 'scope1_natural_gas_tco2e', 'scope1_refrigerants_tco2e', 'scope1_emissions_tco2e', 'scope2_location_based_tco2e', 'scope2_market_based_tco2e', 'total_energy_consumption_mwh', 'ghg_measurement_methodology', 'emission_factor_source_disclosure', 'organizational_boundary_disclosure', 'data_quality_level', 'scope3_cat1_tco2e', 'scope3_cat6_tco2e', 'scope3_cat7_tco2e', 'scope3_cat15_tco2e', 'scope3_total_tco2e', 'scope3_methodology_note', 'scope3_categories_disclosed', 'scope3_method', 'scope3_data_quality_level', 'total_assets_usd', 'high_climate_risk_assets_usd', 'total_capex_usd', 'climate_related_capex_usd', 'current_climate_loss_usd', 'climate_capex_pct', 'high_climate_risk_assets_pct', 'financial_effect_current_year_level', 'climate_financial_disclosure_note', 'finance_data_source', 'risk_description', 'risk_type', 'likelihood_score', 'magnitude_score', 'climate_risk_score', 'climate_risk_level', 'time_horizon', 'mitigation_plan_exists', 'risk_owner_function', 'risk_assessment_methodology', 'risk_prioritization_basis', 'risk_assessment_structured_disclosure', 'board_oversight_exists', 'committee_oversight_exists', 'committee_name', 'management_oversight_exists', 'management_role_title', 'remuneration_linked_to_climate', 'board_oversight_frequency_label', 'internal_reporting_frequency_label', 'external_assurance_on_climate_disclosures', 'governance_score', 'governance_maturity', 'governance_oversight_disclosure', 'committee_disclosure', 'management_role_disclosure', 'remuneration_disclosure', 'skills_and_competencies_disclosure']